### ISSUE TITLE
Invalid CSS Media Query Syntax

### ISSUE THREAD

**Issue by minig0d** [daneden/animate.css#1000]
Firefox flags the media query syntax as invalid with print being in parentheses on line 3616:
`@media (print), (prefers-reduced-motion: reduce) {`
should be
`@media print, (prefers-reduced-motion: reduce) {`

This does appear to be accurate per the official CSS3 and 4 specs.

**Comment by WarenGonzaga** [comment]
alright we will take a look on this...

**Comment by WarenGonzaga** [comment]
@minig0d fix in 0f35cf3 at #1029 

Reference:
```prefers-reduced-motion```
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
```print```
https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by WarenGonzaga** [comment]
@eltonmesquita kindly review and close if necessary.
