### ISSUE TITLE
Animations not working in Firefox 71.0

### ISSUE THREAD

**Issue by wapcrazut** [daneden/animate.css#1001]
Hello,

Recently I came across with buggy animations or not animations at all while using Firefox 71 on Ubuntu 18. Also the same issue seems to affect the main website. This seems to be related with #928 

Example [fiddle](https://jsfiddle.net/hojurtas/2/)

![Peek 03-01-2020 16-42](https://user-images.githubusercontent.com/12850505/71732811-78f3fb80-2e48-11ea-8292-4eb3252a6ca0.gif)

_Issue Example_

![image](https://user-images.githubusercontent.com/12850505/71732785-6b3e7600-2e48-11ea-81a6-42ae8418fa78.png)

_Browser version_

**Comment by tomdol** [comment]
Same here, exactly the same SW setup. Going back to 3.6.2 helped me though.

**Comment by LukeTOBrien** [comment]
I think it is to do with the [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).  
In my opinion it is not what you want as a developer, it's obtrusive and not obvious for users, how are we going to explain this to our users and get them to turn it on?

Anywhoo, I noticed you are using Ubuntu:

> In GTK/Gnome, if gtk-enable-animations is set to false. This is configurable via GNOME Tweaks (Appearance tab or General tab, depending on version).
> Alternately, add gtk-enable-animations = false to the [Settings] block of the GTK 3 configuration file.

In Windows:
> Settings > Ease of Access > Display > Show animations in Windows.

**Comment by wapcrazut** [comment]
@LukeTOBrien Thanks for the reference, I don't know why this is set to false in my setup (by default) but enabling this fixed the issue. 

I'll close the issue because that's the expected behavior on Firefox.
