### ISSUE TITLE
Feature request - Concave/Convex (CSS 3D transformations)

### ISSUE THREAD

**Issue by LukeTOBrien** [daneden/animate.css#1002]
Hello there,

I just stumbled upon your project and I really like your animation, I can't wait now to go and try them out in my project.  

One thing that I did notice that you don't have, which I think would be quite awesome, is **CSS 3D transformations** more specifically I was thinking about Concave/Convex In/Out animations.  
I envisage that these animation would spin on the Y axis from a point behind the screen.

Just an idea ;-)

**Comment by WarenGonzaga** [comment]
Hi @LukeTOBrien can you give us an idea on how it looks like how it moves? Thanks... any reference would be a great help!

**Comment by LukeTOBrien** [comment]
Yes soz I was going to say.  
I was thinking about the [Concave/Convex transitions in Reveal.js](https://revealjs.com/?transition=convex#/transitions)

[Here I have a lil demo uploaded to my GitHub](https://luketobrien.github.io/slides-convex.html#/)

:-)

**Comment by WarenGonzaga** [comment]
@LukeTOBrien look interesting it looks like my local project for animating pages in a website. Great suggestion but I will think of it if it is really necessary to add in animate.css @eltonmesquita what do you think?

**Comment by eltonmesquita** [comment]
I do understand the request but I think it doesn't suit animate.css.
I'm closing this.
