### ISSUE TITLE
Feature request - Glow animation

### ISSUE THREAD

**Issue by LukeTOBrien** [daneden/animate.css#1003]
Hello me again.

I think a glow animation would be a nice addition, this would be animating the [box-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow) property.  
You could also use CSS variables `--glow-colour` (or color).  
Even you could also have something like `--glow-size` and then use: `calc(var(--glow-size) * 1px)`:  
[See my pen](https://codepen.io/luketobrien/pen/yLyPdRj):  
`box-shadow: 0 0 calc((var(--glow-size) * 2) * 1px) calc(var(--glow-size) * 1px) blue;`

Just an idea ;-)

**Comment by WarenGonzaga** [comment]
great! I'm gonna give it a try... thanks for your suggestion.

**Comment by eltonmesquita** [comment]
I do understand the request but I think this is out of the animate's scope which has never included or planned to add style to elements.
