### ISSUE TITLE
lightSpeedInLeft?

### ISSUE THREAD

**Issue by aibar** [daneden/animate.css#1004]
How to get lightSpeedInLeft/lightSpeedOutLeft animation?

**Comment by WarenGonzaga** [comment]
I don't think so if it is already on our collection of animation. Please specify.

**Comment by aibar** [comment]
Yes, there is no that animation.
lightSpeedIn - is actually lightSpeedInRight.
I need lightSpeedInLeft.
Can we achieve that behavior with some hack or  a little extra code?

**Comment by WarenGonzaga** [comment]
now I understand let me do the code...

**Comment by raxraj** [comment]
Is it open to work?

**Comment by raxraj** [comment]
@WarenGonzaga Had a shot on #1027

**Comment by WarenGonzaga** [comment]
@aibar and @raxraj done! check commit 6f47729 in #1029

**Comment by aibar** [comment]
thx! Exactly what I need
