### ISSUE TITLE
Start Animation after element comes into viewport

### ISSUE THREAD

**Issue by MadhabaPatra** [daneden/animate.css#1006]
This will make the make the CSS animation either start before or after it has entered the viewport by scrolling.when an user will scroll to that element by some size animation will happen!

**Comment by DanielRuf** [comment]
> This

Was this meant to be with an example code or PR?

**Comment by MadhabaPatra** [comment]
suppose there is a element at the end of my html page which i am not able to see  element. when i will scroll to that element,  that animation has already gone. so i want to see that animation at that time

**Comment by DanielRuf** [comment]
You might want to use scrollreveal or aos for that or a scroll listener / observer and the some clientBoundingRect checks.

https://stackoverflow.com/questions/123999/how-can-i-tell-if-a-dom-element-is-visible-in-the-current-viewport

https://gomakethings.com/how-to-test-if-an-element-is-in-the-viewport-with-vanilla-javascript/

This is out of scope of this library which is a pure CSS library for animations.

**Comment by WarenGonzaga** [comment]
@eltonmesquita kindly close this!
