### ISSUE TITLE
Additive CSS discussion

### ISSUE THREAD

**Issue by LukeTOBrien** [daneden/animate.css#1010]
Hi guys,

I stumbledd upon a great discussion about a new proposal for CSS which I think is relivent to you guy so I want to link you in here in case you've interested.  
[The discussion is here](https://github.com/w3c/csswg-drafts/issues/1594)

They are talking about additive CSS, and I was thinking it would be interesting for your preoject.  
For example you have an animation for each direction - Left, Right, Up and Down.  
With new additive CSS you might be able to have animations for each direction and add them to the base animation:
```html
<div class="animated bounce right"></div>
<div class="animated fade up"></div>
```  

Exciting stuff.

**Comment by WarenGonzaga** [comment]
hmmmm cool stuff! I might look into it...

**Comment by WarenGonzaga** [comment]
great suggestion @LukeTOBrien btw....

**Comment by eltonmesquita** [comment]
Yeah, t

**Comment by eltonmesquita** [comment]
Cool. We might use it in the future, but I'll close the issue to keep the repo clean. Thanks!
