### ISSUE TITLE
Input with autoFocus in React wrecks animate

### ISSUE THREAD

**Issue by willvlad** [daneden/animate.css#1011]
Easy to repro = 

create a slideInRight around a form with input fields with an autofocus

The sliding effect will look really weird - instead of the form just sliding in from the right, the page underneath the form (background, other divs) will slide in from the left as if it was that that was animated and not the form.

If autoFocus is removed, the sliding behaviour is back to normal. 

I've seen this issue raised before (5 years ago), but still no solution?

**Comment by WarenGonzaga** [comment]
Hi, @willvlad thanks for reporting I'm gonna look into this.

**Comment by eltonmesquita** [comment]
Hi, could someone please provide a reduced case on codepen so I can have a look?

**Comment by eltonmesquita** [comment]
This is almost certain a browser bug or simple misusage. I'll close this as there's no reduced case.
