### ISSUE TITLE
Chrome Same-site cookie warning

### ISSUE THREAD

**Issue by rafill** [daneden/animate.css#1015]
Chrome has this warning in developer console:

`A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by darylknight** [comment]
This is completely unrelated to CSS animation

**Comment by rafill** [comment]
This is not unrelated to animate.css. It only appears when I include this in my project and disappears when I remove it from my project. The same thing happens on multiple projects

**Comment by darylknight** [comment]
It's related to Cloudflare, not animate.css
