### ISSUE TITLE
Datatable Issues

### ISSUE THREAD

**Issue by aximuseng** [daneden/animate.css#1016]
I was trying to add some callbacks on my Datatables and add an animation to cell content.  At first I thought it was an issue with the fact these are rendered vis AJAX or it was jQuery but I suspect it's perhaps a CSS conflict with datatables.

Here is a sample:

`http://live.datatables.net/tacaduqe/2/edit`

Here I am adding my animation after the table loads:

`element.classList.add('animated', 'bounceIn', 'slower');`

Notice how it flashes but the bouncing action is missing.  Try 'bounceInDown' and you see the same issue.  Plain 'bounce' does not even work at all.  'flash' works in this example but in my development code the flash sort of works but then the element disappears completely.

**Comment by WarenGonzaga** [comment]
Hi, @aximuseng so the only issue is in DataTables rendering right? I saw the behavior of the animations. I will try it on my local and find out what's wrong.

**Comment by aximuseng** [comment]
It seems to be just in the table cells.  Try this in the live demo:

`$('#example_filter').addClass("animated bounce")`

The search field will bounce as suspected.  My hunch is that the CSS of DataTables is perhaps preventing the animation from displaying properly.

**Comment by eltonmesquita** [comment]
Sorry, but this seems like an usage problem and you won't get much help here because this is an issue tracker dedicated to the problems of the library itself.
Please use stackoverflow for this kind of question.
