### ISSUE TITLE
Suggestion: Have 100-1000ms delays built in

### ISSUE THREAD

**Issue by MollyUrs** [daneden/animate.css#1017]
90% of the time when using the library I create custom delays from 100ms to 1000ms I think this would be a really great addition to an already amazing library.

**Comment by wonexo** [comment]
Hi @MollyUrs,

If you do find this useful then, you might not just be the only one.
I'll add that up to the library and send a pull request.

**Comment by eltonmesquita** [comment]
This will be easily addressable in the next version which will include css custom properties. I'm closing this as it will be added (ish) in the near future.
