### ISSUE TITLE
bootstrap tooltip position move to the top after i add animation class

### ISSUE THREAD

**Issue by 3l33t** [daneden/animate.css#1021]
when I add animation to bootstrap tooltip, tooltip position move to the top . 
is there something wrong with my code. 
please help me find a solution.

![2](https://user-images.githubusercontent.com/33633735/73817857-9e48a080-481e-11ea-8096-06a900854ffb.PNG)

 **my html code**:
`<button type="button" class="btn btn-primary" data-toggle="tooltip" title="hello world" data-placement="bottom">Hover me</button>`

**my javascript code:**

```
<script>
		$(document).ready(function() {
			$('[data-toggle="tooltip"]').tooltip();
			$('[data-toggle="tooltip"]').on('shown.bs.tooltip', function() {
				$('.tooltip').addClass('animated swing');
			});	
		});
</script>
```

**Comment by eltonmesquita** [comment]
The tooltip is probably positioned with some transform property, which gets overwritten by animate. There's no easy fix for this and not actually a bug, just an usage issue. You won't get much help about this kind of stuff here as this is an issue tracker dedicated to the library's issues. Please use stackoverflow for usage help.
