### ISSUE TITLE
Usage of Font Awesome 4.7.0, causes conflict with FA^5.1.0

### ISSUE THREAD

**Issue by Abarth77** [daneden/animate.css#1022]
Hey guys, I'm running into issues with FontAwesome v5, they suggest for backwards compatibility that you use a Kit, when doing so (since nothing worked) you can run a diagnostics with the Kit, and a single conflict shows, which is ```animate.css``` that uses 4.7.0.

Any known work around for this?

**Comment by XONOSNET** [comment]
I am also experiencing this exact same issue, using the latest version of Font Awesome Pro. Please advise.

**Comment by eltonmesquita** [comment]
Sorry, but could you please share the documentation link for this advise on FontAwesome and a proper reduced case so we can have a look on the issue?

**Comment by WarenGonzaga** [comment]
Can you guys create a codepen for this? So we can understand the issue...

**Comment by Abarth77** [comment]
Will create one and come back to you.

**Comment by WarenGonzaga** [comment]
@Abarth77 thank you... so I can add this to my PR...

**Comment by Abarth77** [comment]
@eltonmesquita @WarenGonzaga 

In the process of creating a codepen for you, we ended up trying both 3.7.0, and 3.7.2, in the last version we could not reproduce the error outside of our system, but within it, we still had issues.

I think we should consider this "Not a bug", and we will keep researching how to get around the issue. But as said, it seems with the latest version, the issue is not animate.css but on our side.

**Comment by WarenGonzaga** [comment]
Alright, thank you!
