### ISSUE TITLE
Relative positioning of the animation - Included in animated.css?

### ISSUE THREAD

**Issue by FreddyCrugger** [daneden/animate.css#1024]
Hello,

I am having problems where sometime I wish to have the animation only passing through a single div and not coming from its container, a basic example would be a bootstrap 4 popup and a bounceInRight effect. The BounceInRight fields from the form come over the black background filter of the popup and then reach the popup box. Ideally, this animation should only show within the white popup(and not from the outside).

How can animated.css deals with this please?
ie:
```
<popup>
//The Animation should be here and not outside this popup element.
<div class="animated bounceInRight"></div>
</popup>
```

**Comment by WarenGonzaga** [comment]
I'll take a look at this...

**Comment by cguweb-com** [comment]
any idea how to pull this off?  I have the same issue, for example, with animations like "fadeInLeftBig", it always seems to come from the left of the page / viewport.  It'd be nice to be able to restrict it to staying within its parent, so the animation starts from the parent element's left side, rather than the page / viewport left side.

much appreciated if you can suggest how to get around this problem!

**Comment by cguweb-com** [comment]
I found a work around, at least... if you set the animated item's parent to overflow:hidden;, hides the animation until it enters the parent.  This causes a slight delay in seeing the animation, but it works nonetheless.

**Comment by eltonmesquita** [comment]
This is purely an implementation detail and is the dev's responsibility as this can't be dealt with on the library side. As @cguweb-com noted, the `overflow: hidden` property can help you with the issues.

I'm closing this as it's not related to the library itself.

**Comment by FreddyCrugger** [comment]
If I were you, I would add this to your front page, this is something people need and need a lot when using animations. Why not add it as "tips",  it can only help people. Unless you prefer people to create posts and enquire about it.
https://github.com/daneden/animate.css/issues?q=positioning

It will limit your work over the years by just adding 1 more line of "tips" on your github page.
