### ISSUE TITLE
Feature Request - Typescript function call for entrance

### ISSUE THREAD

**Issue by Jay-PC** [daneden/animate.css#1026]
I have a stack of 6 panels that are fading in from the bottom on scroll, and it all works very nicely (thanks!). However, from a user-story standpoint, I want the 3rd element to remain hidden until they complete something on the 2nd panel. Once that action is complete, I'd like to trigger the fade in of the 3rd panel from a typescript function but look exactly like the rest, and then continue the fade in from the bottom on scroll for the remaining panels. Can that be done already, or is this request truly a new feature? Thanks!

**Comment by eltonmesquita** [comment]
Hi, sorry but I didn't get the problem. Typescript is just Javascript in the end, so you need help with Javascript.
This is the issue tracker, so you won't get much help about usage. Please use stackoverflow for that.
I'm closing this as it's unrelated.
