### ISSUE TITLE
zoomIn flashes element before disappearing and then zooming in!

### ISSUE THREAD

**Issue by jgoldsworthy** [daneden/animate.css#1028]
I have an image that I wanted to zoomIn on page refresh. The image is located at the very top of the page. When you open the page from another page the image is there for a split second, disappears and then zooms in as the element is supposed to. How do I get the appearance for the split second to not show at all and just have the image zoomIn from 0 opacity?

Here is my code for this project:

html:
<div class="Header-Image-Container rellax">
    <img src="images/Calibrator_Logo_Text_NoBackground.png" alt="Header Picture" class="Header-Image 
    wow zoomIn" data-wow-duration="3s"  />
</div>

css:
@keyframes zoomIn {
  from {
    opacity: 0;
    -webkit-transform: scale3d(0.3, 0.3, 0.3);
    transform: scale3d(0.3, 0.3, 0.3);
  }

  100% {
    opacity: 1;
  }
}

.zoomIn {
    -webkit-animation-name: zoomIn;
    animation-name: zoomIn;
}

Here is a link to the actual site where I am having the issue: www.calibrator.ca/TestSite. I am just trying to have the image start from a 0 opacity and then zoom to a 1. To me it looks as if the css code would accomplish this but when it renders in chrome and firefox it has this flash of the image before it disappears. Any help is appreciated.

**Comment by eltonmesquita** [comment]
Sorry, but if I got this right it's not possible to do this with CSS only. What you'd have to do is to listen to the image's load event, show the image and then adding the animate's class through Javascript.
As this is the library's issue tracker you won't get much help as this is not a problem with the library itself. A better place to seek for help is stackoverflow.
I'm closing this as it's unrelated.
