### ISSUE TITLE
Release in ESM format

### ISSUE THREAD

**Issue by nainardev** [daneden/animate.css#1031]
No web-optimized 'module' entrypoint was found in package.json manifest

https://github.com/rollup/rollup/wiki/pkg.module

![Screenshot (130)](https://user-images.githubusercontent.com/59839368/76145390-1240c780-60af-11ea-8592-8e338c2cc8e9.png)

**Comment by WarenGonzaga** [comment]
Thank you for reporting we will look into it...

**Comment by eltonmesquita** [comment]
Correct me if I'm wrong, but this is a javascript format and doesn't apply to animate.**CSS**...
