### ISSUE TITLE
Add news ticker style

### ISSUE THREAD

**Issue by ryangugcloudca** [daneden/animate.css#1032]
Hope someone can add new style newticker similar to [ticker](https://www.cssscript.com/demo/create-a-simple-news-ticker-using-pure-css-css3/#)

**Comment by WarenGonzaga** [comment]
Good suggestion... I'll look into it... will probably add this to v4 update...

**Comment by daneden** [comment]
This feels hard for us to support natively in animate.css since it requires some knowledge about, for example, the number of steps to “tick” and the height(s) of objects to animate. Going to close this and recommend building something bespoke for this sort of animation!
