### ISSUE TITLE
Add rotateClockwise & rotateCounterClockwise Class

### ISSUE THREAD

**Issue by CheneyLin** [daneden/animate.css#1034]
Hi,
I want to show a cool image as background, and need it keep rotation status.
Can we add RotationLeft & RotationRight Class?
Thanks!

Cheney

**Comment by CheneyLin** [comment]
Can I pull a request?

**Comment by WarenGonzaga** [comment]
Before you can PR please show us a codepen version of it.

**Comment by CheneyLin** [comment]
Codepen Here
https://codepen.io/CheneyLin/pen/JjdwORd

**Comment by WarenGonzaga** [comment]
> Codepen Here
> https://codepen.io/CheneyLin/pen/JjdwORd

For me its approve kindly submit a PR and we will review it again together with @eltonmesquita

**Comment by CheneyLin** [comment]
Hi, My first pull request at GITHUB!
https://github.com/daneden/animate.css/pull/1036
Thanks

**Comment by CheneyLin** [comment]
Change PR on dev branch
https://github.com/daneden/animate.css/pull/1037

**Comment by CheneyLin** [comment]
Change PR on dev branch
https://github.com/daneden/animate.css/pull/1038

Hello World Again!

**Comment by CheneyLin** [comment]
Add rotateClockwise & rotateCounterClockwise Class
Change Css Name and new PR.
https://github.com/daneden/animate.css/pull/1039
There are 3 commits, is it ok?

**Comment by CheneyLin** [comment]
https://github.com/daneden/animate.css/pull/1040
New Clean PR

**Comment by eltonmesquita** [comment]
Let's keep the conversation  on #1040
