### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by desaifly** [daneden/animate.css#1042]
I love the animate.css. It has helped me lot to make the UI look great! 

The only thing I am unable to do is a collapse x or y animation. This may be available; however I am unable to find it. 
If it's not possible. It would be nice to get a simple collapse animation.

**Comment by WarenGonzaga** [comment]
@desaifly can you give us an example of the animation so I can check if it is available on our collection of animation?

**Comment by eltonmesquita** [comment]
If I got this right, you need some sort of animation that would make an element collapse on itself, like in an accordion component.

This kind of animation doesn't fit animate.css as it would be required to write animations for more than an element at once and it would have to be based on a certain HTML structure. This is beyond animate's proposal and is more suited for a framework like Bootstrap.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I guess you need to close this issue...
