### ISSUE TITLE
Does not work at all on iOs devices running CHROME

### ISSUE THREAD

**Issue by zagarskas** [daneden/animate.css#1044]
**Describe the bug**
Load up https://daneden.github.io/animate.css/ on your iPhone or iPad using Chrome
Watch animations "struggle" to work, then fail.

**To Reproduce**
1. Install CHROME on any iOS device
2. Load up https://daneden.github.io/animate.css/ 
3. watch animations fail

**Expected behavior**
Animations should work

**Desktop (please complete the following information):**
 - OS: iOS 11
 - Browser CHROME
 - Version: any

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPad Pro, iPad

**Additional context**
N/A - works fine on Safari

**Comment by eltonmesquita** [comment]
Please check this https://github.com/daneden/animate.css#accessibility first and set your accessibility options on your device's settings.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I guess this one has been solved, kindly close this...
