### ISSUE TITLE
Repeat animation

### ISSUE THREAD

**Issue by Ricox88** [daneden/animate.css#1048]
Hello everyone,
First of all thank you for the animation to the creators.

I would like my image repeat the animation after 12sec.
How can i do it? Could you kindly help me with this, please?

This would be much appreciated.

Thank you

**Comment by eltonmesquita** [comment]
That's only possible using javascript and is not in the scope of the library itself. Sorry, but you better seek for help on StackOverflow as there are lots of people willing to help on this.

I'm closing this as it's unrelated to the library itself.
