### ISSUE TITLE
Background Image Disappeared

### ISSUE THREAD

**Issue by pratikchaskar** [daneden/animate.css#201]
Hi,

We have an issue with animate.css - If animation is applied at any position above the fixed background image in the layout, then background image is blinking or disappearing completely. While its working perfect for scroll background image. Is there any idea to fix this issue?

Here is demo: http://ultimate.sharkslab.com/animate-css/

Please help us to fix this issue.

Thanks in advance.

Regards,
Pratik

**Comment by procodeing** [comment]
@pratikchaskar The link you put is coming up as a 404
