### ISSUE TITLE
Animating text gets really ugly in Safari

### ISSUE THREAD

**Issue by cookierebes** [daneden/animate.css#252]
This seems to be a non-version browser-specific issue.  You can see an example on the site I am developing (http://bmgz.rtcgraphics.com/#5) when you click on one of the thumbnails.  I have three divs with text which are animating using fadeInUp.  During the animation they look really ugly and bitmapped, and then they adjust to look normal once the animation has run its course.  

I have -webkit-font-smoothing:subpixel-antialiased; running on the entire body to beef up the fonts in Safari.  Wondering if that might be the issue.  Any insight would be appreciated!  Thank you!

**Comment by elixirgraphics** [comment]
> It’s fixed by using -webkit-font-smoothing:antialiased; — but that doesn’t work when I need subpixel-antialiased.  However, I found that adding a background to the container that is animating fixes the problem.  Not ideal, but it works.

Have the same problem here. Need subpixel antialiasing, so I can use the `-webkit-font-smoothing:antialiased;` hack. Tried using both a background color. Didn't work for me here. Also tried `background: transparent;` with no luck either. Would rather not use a background though. 

Any thoughts on keeping this ugliness from happening?
