### ISSUE TITLE
Can't fullscreen videos embedded in an element with an animation applied

### ISSUE THREAD

**Issue by BenDTU** [daneden/animate.css#313]
We're currently using <a href="http://www.jquerypowertour.com">Power Tour</a> with videos embedded on Wistia. We're finding a weird issue where applying an animate.css transition to the power tour window will cause the video to not go full screen on Firefox or Chrome.

This can be seen stepping through Tour 1 on the Power Tour website when the Youtube video slide is playing. Is this a known issue?

**Comment by eltonmesquita** [comment]
Can you isolate the problem? It's hard to debug with so much happening. Make a pen or a fiddle with only the modal, the video and the animation so we can try to figure what's the problem.

**Comment by daneden** [comment]
Stale issue. Closing.

**Comment by kruser** [comment]
I was having this issues, but upgrading to the latest animate.css fixed it up.

Another reference of the old bug: http://stackoverflow.com/questions/23245709/vimeo-fullscreen-video-appears-under-the-websites-elements

**Comment by BenDTU** [comment]
This is unfortunately still having issues for me. Firefox appears to now be working but Chrome is still weird.

I'll try and create a fiddle and get that up today.

**Comment by BenDTU** [comment]
Ok, that's good to go at:

https://jsfiddle.net/snq8bk0o/1/

I've embedded a Youtube video and a Wistia video, though the Wistia video isn't loading in Chrome so that's probably not going to be much use. The Youtube issue should demonstrate fairly easily though.

**Comment by BenDTU** [comment]
Forgot to mention - you'll have to add allowfullscreen to the iFrame there and run again.

**Comment by BenDTU** [comment]
Would it be possible to have this one re-looked at? Updating to the latest animate.css this is working in every browser but Chrome.

In our application we've got a div with a fixed position to make room for a topbar, and going fullscreen while using 'fadeInRight' is causing it to start at the top of the div and then go off the bottom of the page. That fiddle should still demonstrate the issue pretty well.

**Comment by farlop** [comment]
I know this issue was closed a long time ago, but I'm facing this problem right now. I managed to create a simple repro for this. I hope this can help to fix the problem, (but I actually think that this is more a Chrome related bug than an animate.css one...)

    <!DOCTYPE html>
    <html>
	<head>
		<link href="animate.css" rel="stylesheet">
	</head>
	<body>
		<div class="animated fadeInUp">
			<iframe width="425" height="349" src="http://www.youtube.com/embed/bwj2s_5e12U" frameborder="0" allowfullscreen></iframe>
		</div>
	</body>
    </html>

**Comment by rolivav** [comment]
In my case, the iframe went into fullscreen but didn't take up all the screen, only the container. I was able to isolate the problem to animate.css after hours of removing libraries. Apparently, only in Chrome, for some strange strange reason, the names of some classes in animate.css conflict with Youtube. I used these keyframes:

```
@-webkit-keyframes moveFromLeftFade {
    from {
        opacity: 0.3;
        -webkit-transform: translateX(-100%);
    }
}

@keyframes moveFromLeftFade {
    from {
        opacity: 0.3;
        -webkit-transform: translateX(-100%);
        transform: translateX(-100%);
    }
}

@-webkit-keyframes moveToRightFade {
    from {}
    to {
        opacity: 0.3;
        -webkit-transform: translateX(100%);
    }
}

@keyframes moveToRightFade {
    from {}
    to {
        opacity: 0.3;
        -webkit-transform: translateX(100%);
        transform: translateX(100%);
    }
}
@-webkit-keyframes moveFromLeftFade {
    from {
        opacity: 0.3;
        -webkit-transform: translateX(-100%);
    }
}

@keyframes moveFromLeftFade {
    from {
        opacity: 0.3;
        -webkit-transform: translateX(-100%);
        transform: translateX(-100%);
    }
}

@-webkit-keyframes  moveToRightFade {
    from {}
    to {
        opacity: 0.3;
        -webkit-transform: translateX(100%);
    }
}

@keyframes moveToRightFade {
    from {}
    to {
        opacity: 0.3;
        -webkit-transform: translateX(100%);
        transform: translateX(100%);
    }
}
```
I really don't know why, but changing the name of these classes fixed the problem for me. I don't know if all of them where the problem or just a few.

**Comment by rserro** [comment]
```animation-fill-mode: both;``` in parent elements seems to cause this kind of issue in fullscreen videos.

**Comment by hienduchuynh** [comment]
`:-webkit-full-screen-ancestor:not(iframe) {
  .animated {
    -webkit-animation-fill-mode: none;
    animation-fill-mode: none;
  }
}`

I added the style and my site works find.
