### ISSUE TITLE
Webkit and perspective causing object position to be higher than intended position.

### ISSUE THREAD

**Issue by elipeters** [daneden/animate.css#315]
I recently had an issue with webkit browsers which showed up in iPad and Chrome for Android where transformations were causing the object to be positioned in a random location higher than where it was meant to be positioned. Scrolling or hovering over buttons seemed to correct the error. 

I resolved this by removing all "perspective(400px)" references in animate.css. I'm guessing that the redraw in webkit was occuring during the transformation phase but I cant be certain.

**Comment by daneden** [comment]
@elipeters was this only happening on animations which used the perspective transform value?

**Comment by elipeters** [comment]
I can not be certain as I was only using a subset of animate.css - the flip and bounce animations. I also used
`-webkit-transform: translateZ(0);`
`-webkit-transform: scale(1);`
`transform-style: preserve-3d;`
`-webkit-transform: translate3D(0, 0, 0);`

for the `.animate` class.

**Comment by daGUY** [comment]
@daneden I just had a similar issue where if I animated an element that had absolutely positioned child elements, the child elements would appear in the wrong spot (too low) during the animation and then snap into the correct place once it completed.

It only occurred in Safari, and it happened with any animation – not just ones with perspective – but I found that any of the lines that @elipeters posted above fixed it (I went with `scale(1)`).

(The child elements in my case didn't have top/left/bottom/right values, just margins. So maybe that has something to do with it).

**Comment by samDonald** [comment]
@daneden I have found the same issue. Though there seems to be an anomaly. In one instance I have an `<ul>` and the `<li>s` have a `relative` position. Inside each `<li>` are two `<div>` elements. One containing a `<h2>` and a `<p>` and the other `<div>` containing an `<img>`. The `<div>` elements both have an `absolute` position. Depending on where they display some `<div>s` are positioned to the `right` and some the `left`. The animations been used on these `<div>s` are `fadeInUp` and `slideInRight` or `slideInLeft`. In this instance everything works and positions as expected.

In the other instance I have a `<section>` with `relative` positioning. Inside which is a `<div>` with `absolute` positioning. Inside this `<div>` is a `<h2>` and `<p>`. If any animation is attached to this `<div>` all positioning with `transform` is ignored.

At first I thought is was some bug that wouldn't let you attach animate to a `<div>` but then I realised I had done so in the first instance. I tried removing every plugin and even made a copy on codepen. After all that I can confirm it is animate.css that's the cause.

One quick solution I guess would be to just place my second, faulty instance in a `<ul>`, even though it would just have one `<li>`.

I have not done any investigation into the `animate.css` file itself.

**Comment by samDonald** [comment]
@daneden seems to be related to % values only

**Comment by samDonald** [comment]
@daneden Actually I think you can probably go ahead and call this a non issue. All you need to do overcome this is apply the animation to the parent or child of the `absolute` positioned element.

**Comment by eltonmesquita** [comment]
Closing this as it's stale and seems to be specific to usage and not the library itself.
