### ISSUE TITLE
better bower configuration

### ISSUE THREAD

**Issue by lorvent** [daneden/animate.css#317]
currently when installing from bower, its copying all files which are not necessary
so please modify bower.json to ignore files which are not necessary

**Comment by daneden** [comment]
@lorvent what files would you suggest ignoring? For people creating custom builds, all the files in the repo may be desired.

**Comment by lorvent** [comment]
@daneden for bower.json only two files are important (main files) animate.css animate.min.css

for custom builds, i guess people will download from repo or they can hack animate.css

**Comment by daneden** [comment]
@lorvent hmm, I think given that the Bower package has thus far included *everything*, and this is the first time this issue has come up, I’m going to leave the config unchanged.

I’ll consider this with the upcoming 4.0 release, but I’m betting that there are more people who will use the Bower package to get all of Animate.css—those who just want the compiled CSS will probably download it directly.

**Comment by joneldiablo** [comment]
min!!!! please XD
