### ISSUE TITLE
Bower Installation broken?

### ISSUE THREAD

**Issue by Sepix** [daneden/animate.css#320]
I switched over to bower on an existing Project that had all animations working properly, however with the animate.css file that comes from bower all animations that were already working before, are broken. I just copied a new download from your website in and it works again.

In short

- All animations are working with your download version 
- No animations work when installed over bower ( Version 3.2.0 )
- The path is correct and the file is loaded in both cases (The CSS can be viewed in the browser)

Am I just missing something?

**Comment by daneden** [comment]
This should be resolved by 813a666.
