### ISSUE TITLE
flipInX and flipInY not working on mobile

### ISSUE THREAD

**Issue by goosehub** [daneden/animate.css#322]
Designing a website with animate.css. Noticed that on my iPhone5s, headings with the class flipInX or flipInY were not visible. They took up the expected amount of space, and could be clicked on, but were invisible. All other animations worked on mobile, and flipInX and flipInY worked on chrome, firefox, and explorer.

**Comment by sferoze** [comment]
I noticed this too. I am using this script and can verify that flipInX and flipInY is not working on iOS8

**Comment by daneden** [comment]
Browser bug :cry:

Closing/nofix.
