### ISSUE TITLE
make it in .SCSS

### ISSUE THREAD

**Issue by leandroruel** [daneden/animate.css#325]
please, would be great if you do it in SCSS.

**Comment by fricks** [comment]
i cant download the sass version in my project. im trying to add to my workflow. i type bower install animate.css --save-dev and the source folder just come with .css files, where the .scss files? anybody get this issue too? thanks

**Comment by benhodgson87** [comment]
You can't use bower to install the Sass version, as it hasn't been merged into the Master branch yet - which is where the bower version is built from.

You have to do it manually:
```git clone -b sass git@github.com:daneden/animate.css.git```

**Comment by fricks** [comment]
thanks @benhodgson87. im using right now this version https://github.com/tgdev/animate-sass

**Comment by benhodgson87** [comment]
Reading into the docs, you can actually do branches in bower too - didn't realise:

```bower install animate.css#sass```

**Comment by fricks** [comment]
ow, sounds good @benhodgson87. thank you!!!
