### ISSUE TITLE
Animations does not work in browser running on touchscreen devices

### ISSUE THREAD

**Issue by csabagb** [daneden/animate.css#327]
Hi,

Animat.css does not work on windows 8.1 laptops with touchscreen. Any update on that?

Thanks

Csaba

**Comment by eltonmesquita** [comment]
This makes no sense, actually. Which browser and which browser version is the issue happening? Is it in Desktop mode or in the "metro mode"? How are you adding the classes?

**Comment by csabagb** [comment]
Browsers: Chrome Version 39.0.2171.95 m
                 Firefox 34.0.5

Windows 8.1 Desktop Mode

Interestingly the IE works.

classes added as i.e. <H1 data-animate="fadeInUp"

**Comment by eltonmesquita** [comment]
Are you adding the classes on scrolling? If so, I believe that's the problem. I can't confirm, but maybe Chrome and Firefox disable the scroll events on touch enabled devices, so no classes will be added.

Are you using a custom script or using a plugin? It you're using a plugin, try issuing the case to the developer(s) as it is not a problem related to animate.css and we can't help much.

**Comment by ShaunGuarini** [comment]
Animations work fine in my windows 8.1 laptop with touchscreen....

**Comment by csabagb** [comment]
Could you give me the url where the animate.css works on yours?

**Comment by ShaunGuarini** [comment]
Jerseycityplumbers.com

**Comment by csabagb** [comment]
Hi checked it out. Intereseting it works fine. However, The emphais of elements such as drop object shaking is only works if you load the website in the second time. Windows 8.1 plus android phone chrome browser. Do you mind to let me know your implementation method then?

**Comment by ShaunGuarini** [comment]
Quick question. Do you have to scroll down to see your animation? It might
just be animating before you see it.

**Comment by csabagb** [comment]
yes you have to. I dont think that is happening because i have elements animating on the top of the page. And they ont animate.

**Comment by ShaunGuarini** [comment]
If you have the css set up properly. Also, don't just copy the code for the
animation you are doing. Every animation needs the animated class as well.

Or wherever your CSS is located and make sure you are using min or min.css
whatever you pulled in.

<head>
  <link rel="stylesheet" href="animate.min.css">
</head>

Then use the right class.

<h1 class="animated bounce">Example</h1>

It should work.

I'm using it along with WOW http://mynameismatthieu.com/WOW/docs.html
which lets you start the animation when you scroll to it.


Shaun Guarini

**Comment by csabagb** [comment]
I am using data-animate https://github.com/sadiqevani/data-animate scroll on function. I have to dig into that I thing that is a problem why the animation does not work.
