### ISSUE TITLE
Animation load only once (FireFox)

### ISSUE THREAD

**Issue by PiKkoO** [daneden/animate.css#335]
live link: http://trickstemplates.com/themepr/theme3/
Animation in the 2nd tabs only once.
All other browsers are doing good ...
Thanks in advance for your reply!

**Comment by gskalinskii** [comment]
@PiKkoO  you need to add classes 'animated bounceInLeft' each time you want the animation to fire.
See fiddle: http://jsfiddle.net/5pduaktb/1/

**Comment by PiKkoO** [comment]
@gskalinskii 
Very many thanks!!!!!!!!!!!!!!!!!!!!
