### ISSUE TITLE
Can you add an example for animating an SVG file?

### ISSUE THREAD

**Issue by Emasoft** [daneden/animate.css#339]
Can you add an example for displaying and animating an SVG external image? I have to animate a company logo appearance and the logo is an svg file created with Inkscape.

**Comment by eltonmesquita** [comment]
You do the same way as with DOM elements, just add the classes. If you need "chained" animations you'll have to add delays or use javascript to add the classes.

Just search for examples of animated SVG's in [codepen.io](codepen.io).
