### ISSUE TITLE
slideInDown

### ISSUE THREAD

**Issue by Gabrielmtn** [daneden/animate.css#340]
slideInDown seems to be missing from the css on the animate.css demo page. I'd add it myself, but can't find the repo.

**Comment by daneden** [comment]
@Gabrielmtn if you want to make the change, you can find the demo site on the [gh-pages branch](https://github.com/daneden/animate.css/tree/gh-pages) of this repo!

**Comment by Gabrielmtn** [comment]
Thanks Dan. Will do :)

**Comment by Gabrielmtn** [comment]
Alright :+1:  all set! I also updated the .css and .min.css files, and added the standard entrance and exit optgroups to the zoom keyframes. Thanks for the great resource!

**Comment by daneden** [comment]
@Gabrielmtn I made a few changes to gh-pages while you were working on this. You mind resolving the conflicts yourself so I can merge?

**Comment by Gabrielmtn** [comment]
I'm only seeing the update to animate.min.css, happy to merge that into the request if that's all it is.

**Comment by daneden** [comment]
That’s it!

**Comment by Gabrielmtn** [comment]
It is implemented, and everything looks good, :+1:

**Comment by Gabrielmtn** [comment]
Absolute pleasure contributing. Thanks again for this excellent resource.
