### ISSUE TITLE
3d Animations using Touch Interactions

### ISSUE THREAD

**Issue by mappmechanic** [daneden/animate.css#346]
Does this library support 3d animations using touch interactions on mobile devices ?

**Comment by eltonmesquita** [comment]
[Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/animation) are unrelated to touch support, so you can use it  according to [browser support](http://caniuse.com/#feat=css-animation) for animations.

Beware that most mobile browsers don't support scroll events so you can't add the animations at scrolling. Also the 3d animations will be bounded to [3d transforms support](http://caniuse.com/#feat=transforms3d).
