### ISSUE TITLE
animate.css broken in firefox?

### ISSUE THREAD

**Issue by ludbek** [daneden/animate.css#347]
I am using [animate.css][1]. I have following styles for animating a div with ng-hide.

    .slide-down.ng-hide-remove {
        -webkit-animation: fadeInDown 0.5s;
        -moz-animation: fadeInDown 0.5s;
        -o-animation: fadeInDown 0.5s;
        animation: fadeInDown 0.5s;
    }

    .slide-down.ng-hide-add {
        -webkit-animation: fadeOutUp 0.5s;
        -moz-animation: fadeOutUp 0.5s;
        -o-animation: fadeOutUp 0.5s;
        animation: fadeOutUp 0.5s;
    }

Unlike in chrome, `.slide-down.ng-hide-add` does not work in firefox while `.slide-down.ng-hide-remove` works fine.

***[You can see it here.][2]***

Is there anything I am missing to make it work?

Update
-----
I am using `angularjs 1.3.9` and `firefox 35`.

  [1]: http://daneden.github.io/animate.css/
  [2]: http://plnkr.co/edit/bzjn6ToLdll018AkYyRI?p=preview

**Comment by daneden** [comment]
Hmm. This is a strange one. @ludbek did you find a solution for this? Seems like a Firefox bug at first glance.

**Comment by ludbek** [comment]
I am using javascript to animate. Although I wish i cud do it with css.

You can see it in action [here](http://ludbek.com).

**Comment by daneden** [comment]
I have to close this issue. It’s definitely a browser bug, and trying to “fix” it will cause more headaches.

I’ll do what I can to bring this to the attention of people who may be able to fix it.
