### ISSUE TITLE
Animate.css does not work properyl in Safari

### ISSUE THREAD

**Issue by mappmechanic** [daneden/animate.css#348]
What version of Safari in Windows & Mac does this support ?

**Comment by eltonmesquita** [comment]
Apple dropped support for Safari for Windows, so you shouldn't care. Animate.css should work in any browser that support [CSS animations](http://caniuse.com/#feat=css-animation) and [CSS 3d transforms](http://caniuse.com/#feat=transforms3d).

If it's not working for you, check if added all the classes required.
