### ISSUE TITLE
Disable animations on mobile and tablets

### ISSUE THREAD

**Issue by kokoda** [daneden/animate.css#349]
Hello,

 How to disable all animations on mobile and tablet devices?

Thank you!

**Comment by eltonmesquita** [comment]
There are so many ways that it's hard to list, but let me show some ways:
* You can do UA sniffing (that's a bad idea);
* You can use media queries and just activate animations at some screen sizes (far from precise, but the most practical way);
* You can use js and detect some things like touch and enable only on non-touch devices (not so good idea);
* Or you can just let them on as most mobile devices, even old ones, can handle it pretty good, unless you're doing some heavy animations (the best idea in my opinion).

**Comment by joshi-mehul** [comment]
Yes that's true. But still depends on your requirement you can use either
ways. I liked the way using laizy load of CSS after detecting touch using
js.

Mehul Joshi.
Bitbix creative solutions

**Comment by kokoda** [comment]
Thanks for both of you. Josh, could you please explain by example on how to laizy load of CSS after detecting touch using
js? Thank you!

**Comment by ShaunGuarini** [comment]
I'm trying to figure this out as well since the animations are so choppy on tablets.
In you css file create the noanimated class to stop transitions and use javascript to find out if its a mobile browser. Go to http://detectmobilebrowsers.com/ for full list.. not included here for brevity.
It works on the tablet until you go to landscape. Let me know if you have any luck.

CSS:
    .noanimated {
        -webkit-animation-duration: none;
                animation-duration: none;
        -webkit-animation-fill-mode: none;
                animation-fill-mode: none;
    }

Javascript
```javascript
    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) 
    {
        $('body').addClass('noanimated'); // to remove transition
    }
```

**Comment by joshi-mehul** [comment]
Hi,
Can you give us a link where you have a demo??
I would love to help you..

**Comment by daneden** [comment]
Lots of solutions given here. Thanks everyone. Closing.

**Comment by gerardjp** [comment]
Imho, these are not solutions but workarounds. The theme does distinct support for different devices elsewhere. Hence the option to change padding choices and whatever via the builder GUI for the different devices. And for animations it's a all or nothing deal.

Where can I put in an RFE? 😃
