### ISSUE TITLE
Animate Broken on direction:rtl

### ISSUE THREAD

**Issue by danniejpt** [daneden/animate.css#352]
Hi Everyone. 
I have a site use animate.css.
Its broken my site when I use direction:rtl;
You can check here: http://shinetheme.com/demosd/doc/Oneclick_Demo/
Dose anyone know about this issue.

Thanks

**Comment by eltonmesquita** [comment]
Can you be more specific? What's broken? What's the browsers and browser version that have the problem? Can you isolate the problem?

**Comment by danniejpt** [comment]
Hi
Im using Chrome Version 40.0.2214.111 (64-bit) on Mac osx 10.10.1
You can see this video for the problem. http://youtu.be/ixgyZiAtNwc

Thanks

**Comment by eltonmesquita** [comment]
What exactly is the problem? It's not clear. Describe it the best you can.

**Comment by danniejpt** [comment]
Hi
http://shinetheme.com/demosd/doc/Oneclick_Demo/
Please follow this link.
When you scroll down, you can see the site dancing from side to side 
I found the problem( CSS attribute: direction:rtl of the body and html tag). But dont know how to fix it

**Comment by eltonmesquita** [comment]
[Fix your markup](http://validator.w3.org/check?uri=http%3A%2F%2Fshinetheme.com%2Fdemosd%2Fdoc%2FOneclick_Demo%2F&charset=%28detect+automatically%29&doctype=Inline&group=0) and everything should work.

Don't forget to close the issue if this fixes the issue.

**Comment by daneden** [comment]
Assuming fixed & closing. Thanks for helping here, @eltonmesquita!

**Comment by amraei** [comment]
I have the same issue and can't realize how this issue has been solved.
