### ISSUE TITLE
When animate to right side, getting bottom scroll bar

### ISSUE THREAD

**Issue by RajeshYukta** [daneden/animate.css#353]
Hello,

When we use some right side animations like fadeOutRight, bounceOutRight.. 
getting the scroll bar in the bottom.

Thanks _/\_

**Comment by eltonmesquita** [comment]
You've got to use `overflow-x: hidden` in its container or body, as the animations, literally translate the element beyond the page's width.

**Comment by run2death** [comment]
It helps a lot, thanks.
