### ISSUE TITLE
Color changing title

### ISSUE THREAD

**Issue by rosco1502** [daneden/animate.css#354]
In the example site ( http://daneden.github.io/animate.css ) you have the title (Animate.css) slowly change color, I would love if you could tell me how you do such a thing, and if I can use it on my project aswell. Thanks

**Comment by joshi-mehul** [comment]
It's a CSS animation in a file named animate.css you need to add the file
in your page and use call in particular element ie. Div to animate it using
javascript ie. JQuery or you can use them plain as per your requirements..

**Comment by joshi-mehul** [comment]
Changing a Color is only a property backgroud color.

**Comment by daneden** [comment]
This is actually pretty simple: https://github.com/daneden/animate.css/blob/gh-pages/style.css#L217-L225
