### ISSUE TITLE
Alter animation speed

### ISSUE THREAD

**Issue by zealmurapa** [daneden/animate.css#357]
How do I slow down all animations, or individually

**Comment by Yeswanth-JG** [comment]
@zealmurapa for individual elements, use the 'ID' value & change the timing & delay!

<pre>
#yourElement {
  -vendor-animation-duration: 3s;
  -vendor-animation-delay: 2s;
  -vendor-animation-iteration-count: infinite;
}
</pre>

Or

you can declare a separate set of class, which focus only on slow timing.

Though not 'recomended', yet we can use <code> !important </code> for the new utility classes
