### ISSUE TITLE
Mismatched version in bower.json in 3.2.0 tag

### ISSUE THREAD

**Issue by kwn** [daneden/animate.css#358]
Hi @daneden 

In 3.2.0 tag version there is still 3.1.1 version annotation. It causes an error during bower components installation. I saw the problem is fixed, but on a master branch only. Could you bump version to 3.2.1, please? And remember to change version to 3.2.1 in bower.json again.

Thanks

**Comment by daneden** [comment]
This should be resolved by 813a666.

**Comment by kwn** [comment]
@daneden Thanks!
