### ISSUE TITLE
Hover animation? Question not a issue..

### ISSUE THREAD

**Issue by Hero-Appelmoes** [daneden/animate.css#360]
Hello,

I'm new on GitHub and I immideatly wanted to ask something about this project. I now know how to animate things but I want to animate something if I ask on it.

BTW: This project is really in one word: awesome!

Kind regards,

Musa.

**Comment by CylonSK** [comment]
Welcome on GitHub,
The effect you want to chieve could be done by javascript(JQuery). For example you popup notification(#notification). If you click on that it fade out. You simply listen to click event. after that add desired effect with .addClass method. Do not forget add class animated before you add your desired effect. 

It is also described in readme https://github.com/daneden/animate.css#usage

Hope it helps

**Comment by Yeswanth-JG** [comment]
> check below sample.

```javascript
$(ABC).on('hover',function(e){
$(target).toggleClass('animation...');
});
//'ABC' is the element where you want to hover
//'target' is the element you want to apply 'animations'
```

**Comment by daneden** [comment]
@CylonSK @Yeswanth-JG @Hero-Appelmoes it’s 2015 and we’re still talking about JS hover events?

Here’s how I’d recommend animating an element on hover:

```css
.element:hover {
  animation: bounce 1s;
}
```

Don’t forget vendor prefixes (`-webkit-animation`, `-moz-animation`, etc.) may be necessary.

**Comment by CylonSK** [comment]
Yes it's 2015 an we are still talking about JS because he did not ask about hover, but how to implement animate.css , so JS is still the best answer.
Also I would recommend using hover with JS, because it is better to have all animation together for maintenance purposes.
