### ISSUE TITLE
Where is the "Less" version of animate file?

### ISSUE THREAD

**Issue by alexsimkovich** [daneden/animate.css#361]
Hi, cant find .less version of the file

**Comment by benhodgson87** [comment]
There isn't one, Animate was written in pure CSS, not LESS.

There is a Sass branch in progress however: https://github.com/daneden/animate.css/tree/sass
And discussion around it: https://github.com/daneden/animate.css/pull/277

**Comment by Mayccoll** [comment]
Here is one unofficial LESS
https://github.com/Mayccoll/animate.less

**Comment by arcanedev-maroc** [comment]
https://github.com/machito/animate.less
