### ISSUE TITLE
is it possible to use animation on  owl carousel?

### ISSUE THREAD

**Issue by woopass** [daneden/animate.css#362]
Hello.
i am trying to make a picture slider using owl carousel autoplay, i was wundering if you could make it fade out and in using animation?

http://www.owlcarousel.owlgraphic.com/demos/autoplay.html
http://www.owlcarousel.owlgraphic.com/demos/animate.html

Thanks in advance

Hope you understad my question my english isn't that good.

**Comment by daneden** [comment]
If you’re trying to animate the entire carousel in/out, I don’t see why Animate.css wouldn’t work for you. That’s about the best support I can give here. The issues posted here should be concerning Animate.css as a standalone library, not in relation to other libraries.

**Comment by jasperf** [comment]
I am trying to use it to on slides. Perhaps the animation is already fired before the slide comes into view? Perhaps that is the issue? But if each slide is in view 5 seconds.. there will not be enough delay class wise to wait for let's say 15 seconds now will there be?
