### ISSUE TITLE
FadeInUpBig Causes Funky Scroll

### ISSUE THREAD

**Issue by anthony-pinskey** [daneden/animate.css#368]
Animation: FadeInUpBig

Whenever I load a URL directly it is animating fine, however there appears to be a bug when you click a link to the page. It causes the scroll to get all funky and the whole page/body scrolls out of the browser and all you can see is white. If you scroll a bit it will come back though. Any thoughts on this?

**Comment by daneden** [comment]
Where are you experiencing this issue?

**Comment by daneden** [comment]
Stale issue. Closing.
