### ISSUE TITLE
Scrollbar Issue

### ISSUE THREAD

**Issue by HelloKadyn** [daneden/animate.css#371]
Hello,

So a quick background of my current website I am working on, it has the following:
-wow.js
-animate.css
-lightbox 2
I removed each of them to test what was causing it and its animate.css. 

To get the thumbnail images I used inline-block and when I remove that piece of code the thumbnails load straight down the left like they would but fit in within the browser. So my guess is animate.css is thinking it shouldn't be inline but straight down in a single line thus the extended scroll bar.

![preview 1](https://cloud.githubusercontent.com/assets/11513674/6680831/948fd0ce-cc2a-11e4-8785-ae04aae50efd.png)
![preview 2](https://cloud.githubusercontent.com/assets/11513674/6680830/948feb4a-cc2a-11e4-81f5-d8a319379bfa.png)

hopefully this makes sense..

Thanks in advance.

UPDATE 1: It seems to be only a problem in Chrome. But it is still an effect of animate.css I believe.
UPDATE 2: I referenced #1 but it didn't fix the problem in Chrome.

**Comment by Yeswanth-JG** [comment]
@HelloKadyn Please post any test case using jsfiddle OR codepen.

**Comment by HelloKadyn** [comment]
@Yeswanth-JG I read about Google Chrome having a bug with display: inline-block and someone had commented saying if you put  between the elements with inline-block it fixes it which it does. So I am sure this thread can be closed, but thank you anyways.
