### ISSUE TITLE
filteration of vendor prefixes.

### ISSUE THREAD

**Issue by Yeswanth-JG** [daneden/animate.css#372]
We all support the cross-browser consistency. I am happy that "animate.css" is supporting the same.

But simple thing is, we are 3D transforms in the project. As of the support, 3D transforms are supported in

IE10+
Firefox
Chrome
Safari(IOS)

Here only Safari is needed the prefix & some times Chrome & firefox.

But for IE10+, we don't need any vendor prefixes. IE started supporting 3D transforms from IE10 & dropped vendor prefixes for the same.

IE prefixes are needed  for IE9 & (-). 

I think we can remove un-needed vendor prefixes from the code.

**Comment by daneden** [comment]
Autoprefixer is included in the Gruntfile and removes all unnecessary prefixes for us automatically. Those left in the code are required for support for the last 2 versions of browsers.

**Comment by eltonmesquita** [comment]
Actually @daneden, the Autoprefixer task is configured to the 3 last versions of the browsers, and this end up including IE9 and its prefixes. A simple change to the 2 last versions would exclude the `-ms-` prefixes.

Mind if I PR it?

**Comment by daneden** [comment]
@eltonmesquita nice catch. Go ahead!

**Comment by Yeswanth-JG** [comment]
Thanks for considering my point.
Thanks @eltonmesquita , @danedan
