### ISSUE TITLE
FadeInUp and  doesn't work in iphone 6 plus?

### ISSUE THREAD

**Issue by nelsonkuang** [daneden/animate.css#378]
Has anyone encountered the same issue? I fixed it by changing 'translate3d' back to 'translateY'.

**Comment by klopfdreh** [comment]
For me it is working on iPhone 6s Plus 64GB iOS 9.2.1.@nelsonkuang Would you be so kind and recheck it? If this is working I think this ticket can be closed @daneden.

**Comment by eltonmesquita** [comment]
Close as it's stale.
