### ISSUE TITLE
about sass branch - chrome error in 'animation-name' unknow property name.

### ISSUE THREAD

**Issue by leandroruel** [daneden/animate.css#380]
when i tryed use animate SCSS files, in my website,but,  he not work,need "-webkit-" prefix to work.

**Comment by daneden** [comment]
@leandroruel the SCSS files are intended to be used with Autoprefixer, which is called for in `package.json`.

**Comment by leandroruel** [comment]
thanks, i solved this problem with autoprefixer before you answer me
