### ISSUE TITLE
Video can't go fullscreen when container is animated

### ISSUE THREAD

**Issue by Sundypha** [daneden/animate.css#387]
When I animate a container which has a video inside, the video can't go correctly in fullscreen mode:

https://jsfiddle.net/snq8bk0o/3/embedded/result/
(scroll down to see video, the breaks are there to simulate a long site)

https://jsfiddle.net/snq8bk0o/3/

is there a way around it?

**Comment by Leezlee** [comment]
+1

**Comment by UiCandy** [comment]
It's because of this property 
```
.animated{ 
  -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
}
``` 

Changing that to 

```
.animated{ 
  -webkit-animation-fill-mode: none;
    animation-fill-mode: none;
}
``` 

resolves the issue. 

Cheers!

**Comment by tunnckoCore** [comment]
:+1: works, PR?

@daneden is this introduce some other issue? lol

**Comment by UiCandy** [comment]
@tunnckoCore I posted a quick fix at the time, I'm going to initiate a PR.

**Comment by BenDTU** [comment]
This is great, it fixed an issue with fullscreen video I was having. Thanks heaps.

**Comment by BenDTU** [comment]
@UiCandy Is there a pull request for this up?

**Comment by procodeing** [comment]
@BenDTU That is the pull request for it

**Comment by procodeing** [comment]
@UiCandy Wasnt there an issue that was fixed by 

`.animated{ 
  -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
}`

**Comment by BenDTU** [comment]
I could be wrong on account of not having used Github for long, but isn't that just the commit? I can't see any related pull request.

**Comment by procodeing** [comment]
@BenDTU Yes, I copied the wrong thing

**Comment by procodeing** [comment]
@BenDTU Yeah put the wrong thing

**Comment by BenDTU** [comment]
As a follow up here - this fix creates issues when trying to animate out. I'm using it with a component called "Power Tour", using "FadeInRight" and "FadeOutRight". The component would animate out and then reappear where it was before.

I ended up using animation-fill-mode: both with the powertour classes to only apply when it was definitely in a 'visible' state, but yeah - that likely won't work here as is.

**Comment by nickcernis** [comment]
Perhaps this?

~~~CSS
:-webkit-full-screen-ancestor {
    animation: none !important;
}
~~~

**Comment by eltonmesquita** [comment]
Closing the issue as it seems to be solved.
