### ISSUE TITLE
Reverse animation

### ISSUE THREAD

**Issue by emage** [daneden/animate.css#392]
Anyone got a good tip to do a reverse animation of the same name?

Example:  

For an app, I had the bottom tool panel slide up from the bottom when the page is in view.  Upon clicking the "next" step I want the tool panel to slide back down before the next page is load into view.

So basically reverse the "slideInUp" 

Or is it easier to just  on click addClass "slideOutDown"

Thanks

**Comment by procodeing** [comment]
you could use mootools with more:
$('nextbutton').addEvent('click',function(event) {
event.stop();
$('toolbar').erase('class');
$('toolbar').addClass('animated hinge');
setTimeout(function() {window.location.href = '/whateverthepath'},1001)
}
)


sorry i didnt use the slide

**Comment by procodeing** [comment]
here is the pen: http://codepen.io/procodeing/pen/MwWdBa

**Comment by procodeing** [comment]
@emage any reason that this is still open?
