### ISSUE TITLE
Issue with Chrome Mobile 

### ISSUE THREAD

**Issue by Mefistofer** [daneden/animate.css#395]
Hi
I am experiencing an issue with the latest version of Chrome for mobile, tested it on a Galaxy Tab Pro 8.4 and a Galaxy Note 3, items disappear and distort after being animated... is there a solution for this?

https://youtu.be/_bcRkVNmabU

Chrome version 42.0.2311.109

Thanks!

**Comment by eltonmesquita** [comment]
Try to add `transform: translateZ(0)` to the parent of the animated elements. It seems to be GPU related.
