### ISSUE TITLE
The Animation End events don't fire on my setup

### ISSUE THREAD

**Issue by custa1200** [daneden/animate.css#399]
Hi i am putting together some work and hoped to drop animate.css in and it's going ok except the animation end events don't seem to be firing is there something that could be causing this you can easily think of?

**Comment by eltonmesquita** [comment]
Can you give more details? Maybe post a [pen](http://codepen.io/) with your problem? What's the browser, its version, OS and so on?
The more details you can give, the easier is to help.

**Comment by custa1200** [comment]
https://gist.github.com/anonymous/34c11c40a4cc9a2c8a1a

This is probably as simple as I could make it

**Comment by eltonmesquita** [comment]
Please, just transform it into a pen, as we can visualize it into the browser.

**Comment by custa1200** [comment]
http://codepen.io/anon/pen/dooVYG

Sorry t he Pen location was at the top of the Gist. The way to trigger things is to type a credit card number, i.e. starting with 34,37,4,51,52,53,54,55

**Comment by custa1200** [comment]
Problem solved, I was using transition end events rather than animation end events.
