### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by FelixZYY** [daneden/animate.css#401]
Not support IE9 and below?

**Comment by procodeing** [comment]
It does.

**Comment by rnyberg** [comment]
Was just wondering about the IE9 support since

`.client.flash {
	background: rgba(49, 102, 174, 1);
	-webkit-animation-iteration-count: infinite;
	-moz-animation-iteration-count: infinite;
	-ms-animation-iteration-count: infinite;
	-o-animation-iteration-count: infinite;
	animation-iteration-count: infinite;
	-webkit-animation-duration: 3s;
	-moz-animation-duration: 3s;
	-ms-animation-duration: 3s;
	-o-animation-duration: 3s;
	animation-duration: 3s;
}`

Works in Moz/Webkit but not IE9.

**Comment by procodeing** [comment]
animation-iteration-count: infinite;


IS the support for IE9

**Comment by procodeing** [comment]
wait i dont think ie9 supports rgba

**Comment by procodeing** [comment]
Alpha

**Comment by rnyberg** [comment]
It does. http://caniuse.com/#search=rgba

**Comment by procodeing** [comment]
Well then it's an error on your part, or it's IE being IE again

**Comment by rnyberg** [comment]
http://jsfiddle.net/tn21sz8x/

Works in Chrome/Firefox. No animations in IE.

**Comment by eltonmesquita** [comment]
(IE9 or less don't support CSS animations)[http://caniuse.com/#feat=css-animation]. There's no polyfill or anything to help here, just build in a way it won't break without animations and you're good to go (you know, progressive enhancement ...).

**Comment by rnyberg** [comment]
Yup, was just wondering if there's some neater way than for example using Modernizr and it's no-transitions class to add some jQuery effects instead.

**Comment by eltonmesquita** [comment]
Yep, like you said, Modernizr + jQuery is your best option. But before make sure you answer this question: "Is it worth?""
Usually it isn't...

**Comment by rnyberg** [comment]
If it was for my own personal use, hell no. Sadly, in the realm of business and clients mostly in the bureau sector, it's required. :)

More likely that I just won't use Animate.css for projects that require IE9 and only do some jQuery animations. Still love the concept.

**Comment by eltonmesquita** [comment]
Or you could drop animate.css and use Velocity.js for these kind of projects, I think it's a better option, although you'll lose the animate.css convenience you'll gain in using only a code base and still use some kick-ass animations.

**Comment by procodeing** [comment]
In my opinion, using mootools is easier.

I really dont like 
IE

**Comment by fritx** [comment]
it does support..
