### ISSUE TITLE
Enhancement Request: Wipe Animation

### ISSUE THREAD

**Issue by robinzimmermann** [daneden/animate.css#402]
Another useful animation would be the wipe animation. For example, I have an arrow, and I want the arrow to reveal from the base toward the head of the arrow.

The FadeInLeft animation is close, but I want the arrow to stay in place, and simply wipe in, in place.

Like the other animations, you'd be able to wipe left, right, up, and down.

**Comment by EvanRicks** [comment]
Currently taking a look at this

**Comment by daneden** [comment]
This isn’t really possible with CSS animations, since it requires a masking element.
