### ISSUE TITLE
Please Remove ".css" from the label on bower package

### ISSUE THREAD

**Issue by drdiv** [daneden/animate.css#406]
I'm working on an application where the .css being in the directory name is breaking the app. Any chance you can call it, perhaps something like "animate-css"?

**Comment by BenShaw** [comment]
+1

**Comment by BenShaw** [comment]
i have a PR in for the name change in the bower.json however you should think about using animate-css everywhere

**Comment by daneden** [comment]
It's not quite as straightforward as changing the package name, sadly. If I change the package name, I’ll lose all the previous versions of the package registered with Bower and have duplicate packages in the registry.

If I delete the old package, then everyone currently using it will run into issues.

Punting on this for now.

**Comment by BenShaw** [comment]
What happens if you kept the current package name for users of the current version but changed it for future versions ? This is something you are going to need to tackle eventually so why not sooner rather than later ...
