### ISSUE TITLE
Animations stops layering of Twitter Bootstrap dropdowns from working properly. 

### ISSUE THREAD

**Issue by desduvauchelle** [daneden/animate.css#408]
Hi, 

First of all thanks for this great plugin. 

Back to the issue. I was using "animated fadeIn" on comments in a project along with Twitter Bootstrap, and I had a layering issue where the dropdowns would appear behind other comments. 

Couldn't figure it out until someone pointed it out for me. Here is the stackoverflow: http://stackoverflow.com/questions/30189899/twitter-bootstrap-button-dropdown-z-index-layering-issue/30190900#30190900

And a jsfiddle with the issue: http://jsfiddle.net/ssL1yydx/29/

Don't know if there is anything you can do about it, but thought I would point it out. 

Hope it helps.

**Comment by DanFeather** [comment]
I would add my experience: I used animate.css on pages built with Foundation 5 framework, and have similar issues. The navigation (Foundations's "top-bar") gets totally wonky on pages with animate.css. I thought I could correct it with z- settings, but it didn't work. I saw other comments that hinted it was fruitless, so I haven't pursued it. But it sure would be nice to use this. Maybe it's something that would occur with any animation scheme that is jquery-based?
