### ISSUE TITLE
CDNjs release

### ISSUE THREAD

**Issue by procodeing** [daneden/animate.css#412]
@daneden Hey, There should be a release to cdnjs for the new jello animations.

**Comment by procodeing** [comment]
could you make a new release,since the latest relese is alredy 52 comments behind master?
I use codepen A LOT, and it is a bit of a hassle to readd the jello keyframes and classes.

**Comment by procodeing** [comment]
@daneden thanks

**Comment by daneden** [comment]
@procodeing just released the new tag :)

**Comment by procodeing** [comment]
@daneden Wait. you have to change the base files, and reupdate it manually: https://github.com/cdnjs/cdnjs

**Comment by procodeing** [comment]
I geuss It does not auto-inplement the new update

**Comment by procodeing** [comment]
@daneden so, I guess as soon as you do those commands, it should fix it.

**Comment by procodeing** [comment]
@daneden Actually, I will try and do it for you

**Comment by procodeing** [comment]
@daneden actually, i think its more complacated than that, so I think you have to doo it
