### ISSUE TITLE
animate relative to an element

### ISSUE THREAD

**Issue by oceatoon** [daneden/animate.css#415]
I love your lib thanks !!
when animations are applied they are global meaning an element would bounceIn from the top of the screen 
is it possible to make the bounce relative to another element ? 
to make it look like it's coming out off taht element ?

**Comment by billybonks** [comment]
Same thoughts here

**Comment by daneden** [comment]
The short answer is no; the animations are using transforms which are either absolute or relative to the element itself. You'd have to create your own custom animations.
