### ISSUE TITLE
error compiling with grunt and sass

### ISSUE THREAD

**Issue by washaweb** [daneden/animate.css#419]
Hi, I had to change those lines in order to compile with a grunt cli : 

    .#{$AnimateHook} {
      animation-duration: $AnimateDuration;
      animation-fill-mode: both;
      // Modifier for infinite repetition
      &--infinite {
       animation-iteration-count: infinite;
      }
    }

to this:

    .#{$AnimateHook} {
      animation-duration: $AnimateDuration;
      animation-fill-mode: both;
    }
    // Modifier for infinite repetition
    .#{$AnimateHook}--infinite {
      animation-iteration-count: infinite;
    }

Was causing this error :

    Syntax error: Invalid CSS after "  &-": expected number or function, was "-infinite {"
    on line 39 of source/animate.scss

**Comment by daneden** [comment]
This sounds like you're using an old version of Sass. Try updating.
