### ISSUE TITLE
RubberBand Hover issues in Firefox 38.0.1

### ISSUE THREAD

**Issue by webras** [daneden/animate.css#421]
Hi
I'm using the rubberband effect on hover in the main menu.
The classes are activated by jquery. Look bellow:
$('.menu-baixo ul li a').on('mouseover', function(){
     $(this).addClass("rubberBand");
});
$('.menu-baixo ul li a').on('mouseout', function() {
	$(this).removeClass("rubberBand");
});

I've tested in IE11, Chrome, Safari and Firefox 38.0.1.
The only browser that isn't working unfortunately is Firefox.

Sorry by my bad english!

**Comment by daneden** [comment]
Can you isolate the issue and post a link here?

**Comment by procodeing** [comment]
@webras so what is the issue?

**Comment by daneden** [comment]
Stale issue. Closing!
