### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by jrpetersjr** [daneden/animate.css#422]
Quick Question...Is there a reason why you aren't using all of the transform and animation calls? 

such as:
-moz-transform
-ms-transform
-o-transform

-moz-animation
-o-animation

and all of the various subcalls of them.

**Comment by bisubus** [comment]
They add a considerable amount of extra size to the build. Afaik O12 support (which is targeted with -o-) was dropped a while ago, and keyframe animation isn't supported in IE9, transforms don't make a sense there. FF is considered an evergreen browser, legacy versions can be potentially omitted.

You can re-enable them for your build in autoprefixer config.

**Comment by daneden** [comment]
Like @bisubus said, these prefixes are added by autoprefixer (in the Gruntfile).
