### ISSUE TITLE
display style has to be set to block

### ISSUE THREAD

**Issue by gregorybleiker** [daneden/animate.css#424]
Hi 
I've just spent a few hours figuring out why my zoomIn animation wasn't working. It seems it only works if the display style of the element that should be animated is set to block (the default if not specified is inline). Is this a bug or expected? If so maybe update the README.md?

**Comment by daneden** [comment]
This isn't entirely true: `position: relative` (or any non-static `position` value would have worked too). I think this is an exceptional case, but if the issue keeps coming up, I’ll add a note to the documentation.
