### ISSUE TITLE
animate within a modal?

### ISSUE THREAD

**Issue by netwire88** [daneden/animate.css#425]
Hi, with bootstrap modal, is there a way to animate content appearing within a modal instead of full screen? I've tried adding `animated slideInRight` to `modal-content`, the entire modal animates in from the right side of the screen. I'm trying to animate just the contents of the modal from the right edge of the modal, not right of entire screen. Any thoughts?

**Comment by daneden** [comment]
Cross-compatibility with other libraries is outside of the scope of issues discussed here.

My two cents, though, is to try applying an overflow value to the modal.
