### ISSUE TITLE
Official LESS port

### ISSUE THREAD

**Issue by bisubus** [daneden/animate.css#426]
I've successfully prototyped the converter for 3.x (currently in php but it has to be implemented in grunt js later, I guess) which generates LESS rig from CSS, it also wraps all the prefix fuss within mixins.

Something would change with 4.x because not all continuously added SCSS features could be easily translated to LESS with regexps (they are fragile but work fine while the code style is consistent). But generally this makes maintaining an additional preprocessor option for the project a breeze (existing LESS forks are obviously prone to errors and delays when merging from the original repo).

I would prefer to donate code to the project instead of forking and maintaining my own build.

**Comment by daneden** [comment]
I’m intending on always only maintaining one codebase. Adding official support for another preprocessor will add unwanted complexity to the project.

**Comment by goodpixels** [comment]
@daneden this is very short-sighted, especially considering that @bisubus already wrote the converter.

right now looking for either `animate.less` or `animate.scss` returns dozes of different forks, most of them being out-of-date.

i definitely understand that you might not be comfortable maintaining 3 branches (CSS, LESS, SASS), but you could resort to something like [@madebysource](https://github.com/madebysource) did with LESShat - they wrote their mixins in JavaScript.

your project is very, very popular and i can't really see why wouldn't you want to support such wildly used preprocessors as LESS and SASS. i think you should reconsider implementing `animate.css` in other flavours too.
