### ISSUE TITLE
Browser Support...

### ISSUE THREAD

**Issue by joetidee** [daneden/animate.css#429]
Hi,

Are you able to note in you GitHub docs which browsers will support this?

**Comment by coliff** [comment]
Good idea. By looking at the source code and comparing against: http://caniuse.com/#feat=css-animation - it looks like it should support the latest versions of all modern browsers; Chrome, Safari, Internet Explorer 10+ and Firefox 15+.

**Comment by gleenk** [comment]
On safari it causes empty spaces at the end of pages so i think it's not supported...

**Comment by daneden** [comment]
CSS animation support can be seen here: http://caniuse.com/#feat=css-animation

**Comment by chamnap** [comment]
@daneden, should mention it on readme, wiki, or somewhere.
