### ISSUE TITLE
Website ( and animation ) currently doesn't work on Safari

### ISSUE THREAD

**Issue by oO** [daneden/animate.css#432]
And because the animation starts offscreen and transparent, it doesn't degrade gracefully. 
Safari 8.0.6 / Mac OS X 10.10.3

![screen shot 2015-06-21 at 4 31 04 pm](https://cloud.githubusercontent.com/assets/181864/8273849/fec3f084-1832-11e5-9519-a03268b7b3f5.png)

**Comment by eltonmesquita** [comment]
I can't confirm this, as I'm running the same versions and everything is ok. Maybe related to your configurations or maybe it's an isolated rare bug...

**Comment by oO** [comment]
Glad to hear that. I couldn't find anything wrong with my Safari settings, but restarting the laptop cured the problem. I guess this is a "Close, Can't Repro" or "User Error" issue.
