### ISSUE TITLE
Hinge

### ISSUE THREAD

**Issue by imapangolin** [daneden/animate.css#444]
This works well under Safari and IE - but for me, under Chrome and under Firefox the item falls off the page, but then when the animation completes it goes back to the top.  Using WOW.JS to trigger it.  Is there something else I should be setting so that it will remain off the page and not revert to initial state?  Thanks.

http://www.ilovetownandcountry.com/pagenotfound.php

**Comment by Doing93** [comment]
You didn't add the 'animated' class for your animate element. In the source code of animate.css, it set the  
animation-fill-mode property 'both' to make the element stay at the last keyframe.

**Comment by daneden** [comment]
+1 to @Doing93’s point. If you apply `animation-fill-mode: both;` to the element, this should no longer be the case. I’d also advise removing the element from the DOM with JavaScript once the animation completes to remove it from the document flow.
