### ISSUE TITLE
the class .slideInRight acts weird on mobile phone.

### ISSUE THREAD

**Issue by littlee** [daneden/animate.css#449]
![qq 20150729214112](https://cloud.githubusercontent.com/assets/7534668/8958999/d4f9a476-363a-11e5-89cd-7c18a3aa9371.jpg)

It create an extra area, because of that, user can scroll right and see an blank area. How to fix it?
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>Animate It</title>
	<link rel="stylesheet" href="animate.min.css">

	<style>
		div {
			background-color: orange;
		}
	</style>
</head>
<body>
	<div class="animated slideInRight">animate</div>
</body>
</html>
```

**Comment by eltonmesquita** [comment]
`overflow: hidden` in your container...
It's basic, if you translate or change the position of any element you're risking increase your page's dimensions. If you don't want this to happens, you'll have to use overflow hidden.

**Comment by littlee** [comment]
It doesn't work. I tried to add it to body.
```html
<body style="overflow:hidden;width:100%">
```
![qq 20150729215809](https://cloud.githubusercontent.com/assets/7534668/8959354/eefa0bc0-363c-11e5-8be5-b22553c68d0f.jpg)

**Comment by c9n** [comment]
apply `overflow:hidden` to `html` too.

**Comment by littlee** [comment]
Nice try.
May I ask, should I remove all animation class after the animation finished?

**Comment by eltonmesquita** [comment]
Nope. You may break something and won't gain in performance.

**Comment by procodeing** [comment]
@c9n you never want to apply  css to the html tag unless youre __SURE__ you want it to affect everything. use a surounding div.

**Comment by lachlanjc** [comment]
Just noticed this on the homepage of Animate. Definitely an issue.

**Comment by eltonmesquita** [comment]
Not an issue.. This is the way the DOM works. If you get an element out of the visible canvas it doesn't cease to exist, it creates more space in the document (in this case, the page) and stay there. Animate uses translations to move the element. If the element break the document's boundaries while animating this will happen.

That's why there's the overflow property. It "masks" the area, but the leftover parts don't cease to exist...

Again, not an issue.

**Comment by littlee** [comment]
Why the demo page remove class after animation finished?
https://daneden.github.io/animate.css/
![qq 20150916134633](https://cloud.githubusercontent.com/assets/7534668/9897336/79035986-5c79-11e5-90b6-ea9e897552f0.png)

**Comment by kafeltz** [comment]
as far as i know, overflow hidden does not work with width 100%, it must be fixed not "fluid"

**Comment by eltonmesquita** [comment]
@littlee  It wouldn't make sense to keep the classes as it have to re-animate the same element over and over with any different animation chose by the user.

In a real case scenario you could do this if you're chaining animations.

@kafeltz I never heard about this. Is it in the specs or is it a bug? I've never had any issue with it...
