### ISSUE TITLE
Bug in sliding entrance

### ISSUE THREAD

**Issue by wahono77** [daneden/animate.css#462]
SlideInDown, SlideInLeft, SlideInTop, SlideInUp always visible before animation starting.
I try to replace visibility: visible; to opacity:0; and it's OK now.

Thanks for this great animation.

**Comment by eltonmesquita** [comment]
This is not a bug, the developer should deal with the element's visibility before and after the animation by him/herself. If there's no more question to ask, please close the issue ;D
