### ISSUE TITLE
Update iOS8 effect slideInLeft bug (with textillate.js)

### ISSUE THREAD

**Issue by aureliePrd** [daneden/animate.css#464]
I am using animate.css with textillate.js
After the update of my iPad on iOS8, 
the effect I choosed, "slideInLeft" doesn't work anymore.
(I change it to "flipInY" and this one is ok)

**Comment by procodeing** [comment]
@aureliePrd  What element did you apply the animation to? and what was its CSS?

**Comment by aureliePrd** [comment]
I applied my animation to several elements paragraph, each one is included in div element :
<div class="h1">
     <p>Text animated</p>
</div>
The css included is animate.css and 
div.h1 {
  visibility: hidden;
  text-transform: uppercase;
  position: absolute;
  top: 50px;
  width: 1000px;
}

I use textillate.js with animate.css. (and I created a web app with phonegap)

It was ok before the update of my ipad. And, the others animations seems to be ok !

**Comment by procodeing** [comment]
@aureliePrd What was the particular animation, I think i might know what's wrong

**Comment by procodeing** [comment]
@aureliePrd This might mess it up, but try applying ```div.h1 {
visibility: hidden;
text-transform: uppercase;
position: absolute;
top: 50px;
width: 1000px;
transform-origin:left;
}```

**Comment by aureliePrd** [comment]
It doesn't work. 
I need to tell you that it was ok (always been) and still is ok in the navigator. The problem appear only in the webapp. I can see sometimes the letters in blue. (instead of red in my case) and both animations appears together (I have two text animated in one slide)

**Comment by procodeing** [comment]
@aureliePrd ok, But I have one more Idea: try putting the element inline.
