### ISSUE TITLE
New animation proposal: headShake

### ISSUE THREAD

**Issue by FelipeMartinin** [daneden/animate.css#466]
Hello

I've created an animation called "headShake", amazing for natural negative feedbacks

check out the preview:
http://codepen.io/FelipeMartinin/pen/ZbOvxr

Pull request link: https://github.com/daneden/animate.css/pull/465

How about merge it? :D

**Comment by alasdairmackenzie** [comment]
:+1:

**Comment by tnga** [comment]
Nice! :+1:

**Comment by jnovack** [comment]
Github REALLY needs a Like and vote counters.  I HATE commenting to say that I like something and show support. "+1" just clogs comment areas and hinders discussions. :/

On that note, I love it. +1.
