### ISSUE TITLE
New animation proposal: squash

### ISSUE THREAD

**Issue by FelipeMartinin** [daneden/animate.css#468]
Inspired in the first animation principle, Squash & Stretch, follow a new animation proposal, just called Squash:

http://codepen.io/FelipeMartinin/pen/dYXabb

Pull request link:  https://github.com/daneden/animate.css/pull/467

**Comment by jnovack** [comment]
If you are taking comments, it's very jarring and a single animation happens way to quick to know what happened.

**Comment by daneden** [comment]
Agreed, this is a little aggressive with a lot going on. How does this animation look applied to, say, a text-heavy form? Think about the use case first and try experimenting with something simpler :)

**Comment by daneden** [comment]
Closing this issue and relaying my feedback on the original PR.
