### ISSUE TITLE
bounceInUp not working anymore - iPhone 6 Plus/iOS9

### ISSUE THREAD

**Issue by ReaVerHC** [daneden/animate.css#472]
Just noticed looking at the my site today that bounceInUp is not working anymore on my iPhone 6 Plus. It was fine on my iOS8 but seem to have stopped working in iOS9. I tested this with the Github example page and it rendered the same result. Have not touched my code in any way in the last month.

This is just a heads up if you need to look into it, not sure what the fix is.

**Comment by YuraRudkovskiy** [comment]
The same problem with Safari on iOS9.

**Comment by YuraRudkovskiy** [comment]
I have added ' -webkit-transform-origin: 0 0;' to bounceInLeft:
0% {
    opacity: 0;
    -webkit-transform-origin: 0 0;
    -webkit-transform: translate3d(-3000px, 0, 0);
    transform: translate3d(-3000px, 0, 0);
  }
and the animation worked.

**Comment by klopfdreh** [comment]
See https://github.com/daneden/animate.css/pull/541
