### ISSUE TITLE
Duration presets

### ISSUE THREAD

**Issue by aalaap** [daneden/animate.css#473]
I know it's possible to add custom durations and delays for the animations, but I'm wondering if it would be possible to add some presets for different animation durations and delays, for eg:

* `faster` (0.1s)
* `fast` (0.5s)
* `normal` (default)
* `slow` (1s)
* `slower` (3s)

Preset delays:

* `immediately`
* `soon`
* `later`
* `latest`

These preset delay names are just to give an idea.

**Comment by AlexPashley** [comment]
+1

**Comment by erilyth** [comment]
+1

**Comment by ColtraneNadler** [comment]
hmm, maybe suffix the classes- fadeIn-slow, fadeIn-fast, etc

**Comment by daneden** [comment]
Many of the animations are designed for a specific speed (typically 1s), and I’d rather steer clear of including presents for modifying these conscious speeds.
