### ISSUE TITLE
Use a namespace.

### ISSUE THREAD

**Issue by Alvargon75** [daneden/animate.css#474]
I suggest doing that to prevent conflicts with other animations users may have.

Something like `an-fadeIn`.

**Comment by daneden** [comment]
Agree with this totally, but I think I’ll defer this to the next major release of Animate.css.

**Comment by mablae** [comment]
Yeah, this would definitively break BC, so a new major version is needed for it. 

However when you have a big CSS codebase, there is no way around namespaced classes for 3rd party css. FontAwesome does it. Animated.css should do it, too. 

Why closed the issue? Better mark it with BC-Break Label and reopen? 

Is there already a new major version scheduled?
