### ISSUE TITLE
bounceInRight in Chrome 45.0.2452.94 mobile scrolls to the top of the page.

### ISSUE THREAD

**Issue by brlebtag** [daneden/animate.css#475]
When I tried to access my website (www.lebtag.com) using bounceInRight in the bottom of the page, the browser scrolls to the top of the page.

First, It was adding a horizontal bar, but I added overflow-x:hidden and fixed it. 

My mobile is a samsung phone.

**Comment by daneden** [comment]
This seems like something caused by JS—animate.css should have no effect on the vertical scroll position of a page.
