### ISSUE TITLE
Is it possible to modify animate.css for react.js animation?

### ISSUE THREAD

**Issue by kevinxh** [daneden/animate.css#480]
Hi,

Just wondering if anyone know how can I use this for my react components?

thanks!

**Comment by daneden** [comment]
All you need to do to use Animate.css is add the class names for the animation you want.

Example: `class="animated bounceInLeft"`

**Comment by morajabi** [comment]
May I correct your example to `className="animated bounceInLeft"`

**Comment by kiranps** [comment]
```jsx
<ReactCSSTransitionGroup
  transitionName={{
    appear: 'animated',
    appearActive: 'bounceInLeft'
  }}
  transitionAppear={true}
  transitionEnter={false}
  transitionLeave={false} 
  transitionAppearTimeout={2000}
>
  <div key="1">hello world</div>
</ReactCSSTransitionGroup>
```

**Comment by OleDakotaJoe** [comment]
How do you import it into a component
