### ISSUE TITLE
How to add interval in between each iteration of animation?

### ISSUE THREAD

**Issue by lzl124631x** [daneden/animate.css#481]
Is there a easy way to add interval in between each iteration of animation, say, `shake`?

**Comment by daneden** [comment]
I’m afraid not—you can only add an initial delay.

**Comment by smknstd** [comment]
would love to get this feature, seams usefull !

**Comment by eltonmesquita** [comment]
@smknstd, you can`t do this with CSS only (or hacking the animations itself, which can be troublesome).
Better use some javascript for this (a simple `setInterval` + add/remove class should do it).
