### ISSUE TITLE
Version without -vendor- prefixes

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [daneden/animate.css#482]
It would be great to have a version without -vendor prefixes -- for those of us who are using AutoPrefixer

**Comment by kafeltz** [comment]
Isn't possible to compile yourself without autoprefixer option in param? See gruntfile.js

**Comment by JohnnyWalkerDesign** [comment]
I use Gulp, but it's an unnecessary nuisance to have to make exceptions for one file. Everyone should be using AutoPrefixer these days. Manually adding vendor prefixes is inefficient, prone to mistakes, and constantly changing -- as every project targets different sets of browsers.

**Comment by tnViking** [comment]
Just get the source and compile it yourself

**Comment by kafeltz** [comment]
Would be nice someone create an alternative with gulp =D

**Comment by thecodechef** [comment]
I Created animate.styl a while back with gulp

**Comment by zhudashu** [comment]
你们都用英文 我就用中文 引用了animate.css，然后比如用了class="animated slideInUp"  div出现下效果然后就消失了 其实还在  就是看不见  怎么回事？

**Comment by kafeltz** [comment]
https://translate.google.com.br/#auto/en/%E4%BD%A0%E4%BB%AC%E9%83%BD%E7%94%A8%E8%8B%B1%E6%96%87%20%E6%88%91%E5%B0%B1%E7%94%A8%E4%B8%AD%E6%96%87%20%E5%BC%95%E7%94%A8%E4%BA%86animate.css%EF%BC%8C%E7%84%B6%E5%90%8E%E6%AF%94%E5%A6%82%E7%94%A8%E4%BA%86class%3D%22animated%20slideInUp%22%20div%E5%87%BA%E7%8E%B0%E4%B8%8B%E6%95%88%E6%9E%9C%E7%84%B6%E5%90%8E%E5%B0%B1%E6%B6%88%E5%A4%B1%E4%BA%86%20%E5%85%B6%E5%AE%9E%E8%BF%98%E5%9C%A8%20%E5%B0%B1%E6%98%AF%E7%9C%8B%E4%B8%8D%E8%A7%81%20%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F

**Comment by coliff** [comment]
+1 for a version without -vendor prefixes

**Comment by tnga** [comment]
Fortunately, there is a script to compile with or without prefixes!!! Just RTFM. For those who like **sass** like me, there is a branch for that in the repo; just checkout.

**Comment by JohnnyWalkerDesign** [comment]
Care to point to this script, @tnga? Anyone can modify the gruntfile and compile their own, but many of us don't use Grunt, which just makes is a huge pain every time you want to grab the latest version for a project.

**Comment by tnga** [comment]
@JohnnyWalkerDesign 
>but many of us don't use Grunt ...

Yes i like **gulp** and i preferred its implementation and usage approach. But the difference of interest between it and **grunt** is just recent so i just actually take a watch.
![gulp-grunt-comparaison](https://cloud.githubusercontent.com/assets/133777/11373331/dcaae5d8-92b8-11e5-82ae-0dcc973c7241.png)
we had the same behavior with projects like **sass**, **less** or **stylus**

Also note that if you take animations in the source directory and you make a concatenation manually, with a **nodejs** script (in the `grunt.js` file just comment the autoprefixer instruction), with **gulp** by using `.concat` function or with **bash** script:
```bash
#!/bin/bash

cat source/_base.css > non_prefixed_animate.css
for src in `ls source/*/*.css` 
do
   cat $src >> non_prefixed_animate.css
done
```
you will have a version without vendor prefixes! :+1:

**Comment by tnga** [comment]
@zhudashu 
Except if i haven't understood very well, you have to open another issue with your preoccupation cause it's a different case with this one.

Maybe issue #488 can referred to yours.

**Comment by JohnnyWalkerDesign** [comment]
I've already built my own version without vendor prefixes using Gulp. I've added a pull request now, too.

**Comment by tnga** [comment]
:+1:

**Comment by coliff** [comment]
Thanks for the PR @JohnnyWalkerDesign . Here's the direct link of minified version for anyone who's interested in grabbing it. https://raw.githubusercontent.com/JohnnyWalkerDesign/animate.css/4cf676154666c4eb442c98bdae6777b361dfe1ca/animate-noprefixes.min.css
The file size is a lot smaller, and there isn't much need for the vendor prefixes anyway since latest versions of all browsers support unprefixed versions.

**Comment by daneden** [comment]
Closing this as per brief feedback on #495. TL;DR: the Gruntfile takes care of prefixes, and prefixed file is useful for people who want to grab it and go.
