### ISSUE TITLE
New animation proposal: Squiggle

### ISSUE THREAD

**Issue by erilyth** [daneden/animate.css#484]
Wanted something a little more bouncy and with some shake in it. A simple animation which combines a rubber-band and bounce animation.

Codepen: http://codepen.io/erilyth/pen/bVmqvR

Pull request: https://github.com/daneden/animate.css/pull/483

**Comment by nelsonkuang** [comment]
:+1:

**Comment by lbenie** [comment]
:+1:

**Comment by procodeing** [comment]
I dont know why this issue is open, the  corresponding pull request, #483, was closed.

**Comment by eltonmesquita** [comment]
I'll let this open for now in case @erilyth has got to improve the animation as cited by Daniel Eden in #483 . Might close if it's stale.

**Comment by eltonmesquita** [comment]
Ok, I'll close this as it's stale. If @erilyth improve something on #483 I might reopen it.
