### ISSUE TITLE
Page becomes super large when using fadeInRight in iOS+Safari

### ISSUE THREAD

**Issue by nimshkedy** [daneden/animate.css#485]
There is a workaround by adding body { overflow-x:hidden;}
But this bug could potentially cause a lot of problems...

http://stackoverflow.com/questions/29321344/animate-css-issue-the-page-becomes-super-large

A potential fix could be to add a warning somewhere in the docs?

**Comment by dmoothen** [comment]
Thanks for the tip !
I was having the same issue.

**Comment by mmjaeger** [comment]
Actually I experience the opposite - the page collapses to maybe about one-third of the regular width - is there a fix to this?

**Comment by VSVS** [comment]
@mmjaeger same here. Discover any fix?

**Comment by VSVS** [comment]
{ overflow:hidden;} worked for me.

**Comment by RainLaurent** [comment]
got the problem too, but i was using slideInRight,  they both used 
`
 -webkit-transform: translate3d(100%, 0, 0);
`
i think it's safari's bug with translate3d calculating parent width
use
`
-webkit-transform: translateX(100%);
`
will solve this
