### ISSUE TITLE
How do I do bounceIn then do a infinate loop of Shake?

### ISSUE THREAD

**Issue by jawfy** [daneden/animate.css#486]
Hello, I'm in the development of my website and I was wondering how I would combine a bounceIn effect at the start of my animation then it would continue on to do a infinite loop of shake.

**Comment by zhudashu** [comment]
you can add a word for example infinite

**Comment by jawfy** [comment]
Yes I know that. The point I'm getting at is how would I code a starting animation such as fadeIn, once the fadeIn has stopped an infinite shake will start.

**Comment by tnga** [comment]
Fortunately, there is a way indicated in the readme! Using jQuery you can do something like:

>You can also detect when an animation ends:

    $('#yourElement').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function (){
     $('#yourElement').removeClass('animated fadeIn');
     $('#yourElement').addClass('animated infinite shake');
    } );

**Comment by jawfy** [comment]
Well... That explains it. Thank you for the help, got it working.

**Comment by tnga** [comment]
Your are welcome. If you wish you can also give a try to this javaScript side development that support [animate.css](https://github.com/daneden/animate.css) animations. Here is an example of usage. 

     //Select the elements to animate and enjoy!
     var elt = document.querySelector("#notification") ;
     iJS.animate(elt, "shake") ;
     //it return an AnimationPlayer object
     //animation iteration and duration can also be indicated.
     var vivifyElt = iJS.animate(elt, "bounce", 3, 500) ;
     vivifyElt.onfinish = function(e) {
         //doSomething ...;
     }
     // less than 1500ms later...changed mind!
     vivifyElt.cancel();

Take a look [here](https://github.com/tnga/lib.ijs)

**Comment by jawfy** [comment]
Couldn't of asked for a more helpful guy! Thank you, this has helped a lot!
