### ISSUE TITLE
Animate with JavaScript

### ISSUE THREAD

**Issue by bocharsky-bw** [daneden/animate.css#492]
Awesome CSS animation!

But is there any more cross-browser library exist with such animation but using JavaScript?

**Comment by kafeltz** [comment]
do you mean animate.css wrapped on javascript? Or pure javascript?

**Comment by bocharsky-bw** [comment]
I meant pure JavaScript for browsers which not support CSS3.

**Comment by tnga** [comment]
Hi! If you wish you can give a try to this javaScript side development that support [animate.css](https://github.com/daneden/animate.css) animations. Here is an example of usage. 
```js
 //Select the elements to animate and enjoy!
 var elt = document.querySelector("#notification") ;
 iJS.animate(elt, "shake") ;
 //it return an AnimationPlayer object
 //animation iteration and duration can also be indicated.
 var vivifyElt = iJS.animate(elt, "bounce", 3, 500) ;
 vivifyElt.onfinish = function(e) {
     //doSomething ...;
 }
 // less than 1500ms later...changed mind!
 vivifyElt.cancel();
```
Take a look [here](https://github.com/tnga/lib.ijs)
