### ISSUE TITLE
Sequential use of multiple effects/classes

### ISSUE THREAD

**Issue by DaleZki** [daneden/animate.css#493]
Great tool, many thanks!
~ ~ ~
How to apply sequential, multiple effects/classes: i.e  “zoomIn” THEN “fadeout” ?
~ ~
Have:
4 distinct elements… brief sentences

Objective:
have each element, “zoomIn” then “fadeOut” THEN
proceed to the next element with the same effect sequences

Any references/ tips would be greatly appreciated.

Dale

**Comment by tnga** [comment]
I think that is a same question that was closed with this issue #486

**Comment by DaleZki** [comment]
Tnga...... I'll give this a try.... I appreciate your help / guidance ~D

**Comment by DaleZki** [comment]
This looks like a great fit..... the next step is to apply this same class-sequence (zoomIn then fadeOut) to a list of elements.  I have list of text (phases) I wish to apply this to.  I will attempt to continue this script by inserting new Classes assigned to my other texts-phases...
If you have any other suggestions, I would welcome your input...
Many thanks ~D

**Comment by tnga** [comment]
I'm not sure that i have understood well what you are trying to do, but i think that control structure in this case can be usefull. Something like:
```
for text in myTextList do
    zoomIn then fadeOut the text
done
```
this is an algorithm sample cause not know how you represent your list of test and in which case you apply your "class-sequence".  Is it depends of some event lin `onclick`, etc?

**Comment by DaleZki** [comment]
thanks tnga
I have a list of phrases I will be using. Each will zoom-In then fade-Out, one after the other.
Here is a online, flash version I am trying to replicate;
my edit... my name:  http://dale.you.are.mighty.aninote.com/
Aninote, main site reference: http://www.aninote.com/site.mpl?p=cont&cont=yam
~ ~ ~ .
Thanks for this and any further ideas.....

D-
