### ISSUE TITLE
Bower - Use dist/ for final product

### ISSUE THREAD

**Issue by jnovack** [daneden/animate.css#501]
Bower lightly hints at using `dist/` for the final package distributables. Many other popular packages do this as well.

The advantage of doing this is to assist in streamlining the build process.

Developers can just easily copy (or link) out the `bower_components/<package_name>/dist/` directory (e.g. within express, as `app.use('animate', express.static('bower_components/animate-css/dist/'));`) rather than cherry-picking each distributable within packages.

**Comment by eltonmesquita** [comment]
@jnovack , I think the best thing right now is to focus on the 4.x release (the sass version), that obviously will fix this.
Do you think this is a critical issue that should be fixed soon? With that we would release a minor version (3.6.0), risking breaking some people project. Or do you think it would be better to wait the non-ETA release of the 4.x branch?

**Comment by eltonmesquita** [comment]
I'm losing this as we'll probably kill bower support as discussed on #758.
