### ISSUE TITLE
Pulse causing placement and border-radius issues

### ISSUE THREAD

**Issue by teddythetwig** [daneden/animate.css#503]
When we animate elements with the pulse animation, it seems to be setting the elements' border-radius to a random %, as well as messing up the placement of the div. It can be observed on the demo site of this project. This bug started occuring when upgrading to Chrome 47. Screenshot attached.
![pulseedited](https://cloud.githubusercontent.com/assets/580041/11628065/768b3636-9cef-11e5-95f4-e39026476bad.png)
![pulsepeedited](https://cloud.githubusercontent.com/assets/580041/11628066/768e0d5c-9cef-11e5-9a9b-d9ee2032227c.png)

**Comment by teddythetwig** [comment]
Here is an screencap with dev tools opened as well. What more information should I provide? 
![pulsedevtoolsedited](https://cloud.githubusercontent.com/assets/580041/11628415/d573c2ba-9cf1-11e5-8431-afe5036315e8.png)

**Comment by Daraghmeh** [comment]
I am also facing this displacement and border-radius issue for the animation of `Pulse`

**Comment by eltonmesquita** [comment]
Closing this as it's stale and is a browser bug for sure.
