### ISSUE TITLE
Source directory no longer included using bower

### ISSUE THREAD

**Issue by oste** [daneden/animate.css#509]
It looks like the source directory was removed with the latest 3.5 release with this line: https://github.com/daneden/animate.css/blob/master/bower.json#L6

Was hoping that this directory could still be included. If not I think there should be a development bower build.

My use case is to include only the files I use/need. 

Thanks.

**Comment by lukiffer** [comment]
I'm still specifically targeting 3.2.6 because of this. It's super nice to be able to use gulp/grunt or specific `@include`s to keep the output lean. Can we get any movement on the #550 pull request?
