### ISSUE TITLE
About using true in animate-config.json file.

### ISSUE THREAD

**Issue by eshacker** [daneden/animate.css#512]
Hello there, 

I was going through code and found something perplexing in animate-config.json. There are so many keys with value equal to true. I forked and test out the code. I have a question. 

What's the rational behind `{"somthing": true}` and 

Can we update code:

```JavaScript
{
  "attention_seekers": {
    "bounce": true,
    "flash": true,
    "pulse": true,
    "rubberBand": true,
    "shake": true,
    "headShake": true,
    "swing": true,
    "tada": true,
    "wobble": true,
    "jello": true
  },
...
}
```

to:

```JavaScript

{ 
"attention_seekers" : [ 
      "bounce",
      "flash",
      "pulse",
      "rubberBand",
      "shake",
      "headShake",
      "swing",
      "tada",
      "wobble",
      "jello"
    ],
...
}
```

as there are no false values in the first example?

Check out https://github.com/eshacker/animate.css/tree/better-custom-builds for reference. 

It builds.  && Output is identical (diff). && Code looks cleaner.

My guess is that when you do not want to build a specific `animation` you can put false against it. But we can just remove the value if we do not want it in the build.  Am I missing something here? 

I am asking this question just to learn the thought and decision process behind such way of code, nothing more.

Edit: Added more info.

**Comment by daneden** [comment]
That makes perfect sense. Feel free to open a pull request with these changes!

**Comment by eshacker** [comment]
It's fine. Go ahead. My code there is stale.
