### ISSUE TITLE
Bootstrap button dropdowns overlapping

### ISSUE THREAD

**Issue by sovattha** [daneden/animate.css#516]
Hi!

This is a weird effect I have with Animate.css + Bootstrap.

![Capture](http://s28.postimg.org/o5cykk5pl/capture.jpg?noCache=1451401886)

Here is [the fiddle](https://fiddle.jshell.net/o8Lhah2k/)

Disabling the animations is the workaround I found.

Cheers!
Sovattha

**Comment by JoaoManoel** [comment]
Hi, try removing this lines:
```
-webkit-animation-fill-mode:both;
animation-fill-mode:both;
```

**Comment by sovattha** [comment]
Thank you!

Did you mean, [this](https://fiddle.jshell.net/o8Lhah2k/1/)?
