### ISSUE TITLE
animations not working in iOS 9.2 safari

### ISSUE THREAD

**Issue by peterworth** [daneden/animate.css#519]
https://liger.vm.bytemark.co.uk/animatetest/

fine in iOS 8, but on iOS 9.2 they just jump straight to the last keyframe

they seem to work in some situations, but i can't figure out the logic - for example sometimes they work if triggered by a jquery click event but not if an element already has the animated class when the page loads

(stack post here: http://stackoverflow.com/questions/34655201/animate-css-on-ios-safari)

**Comment by woneob** [comment]
Try to reduce the number of `translate3d` value in the animate.css.

```css
/* Change from 3000px to 800px */
  from {
    opacity: 0;
    -webkit-transform: translate3d(0, 800px, 0);
    transform: translate3d(0, 800px, 0);
  }
```

I think maybe safari on iOS9 ignores off-screen elements for performance. 
I'm not sure how to solve it clearly without JavaScript. Because the maximum value is determined by the window size.

**Comment by klopfdreh** [comment]
See https://github.com/daneden/animate.css/pull/541

**Comment by tgxpuisb** [comment]
hi~,I meet this question too
I find a solution from [stackoverflow](http://stackoverflow.com/questions/34655201/animate-css-on-ios-safari)

yeah~
by using `transform-origin: 50% 50%`, I resolve this question, you can update the code like this:

```
@-webkit-keyframes bounceInLeft {
    from, 60%, 75%, 90%, to {
        -webkit-transform-origin: 50% 50%; /*update here*/
        transform-origin: 50% 50%;/*update here*/
        -webkit-animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);
        animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);
    }

    0% {
        opacity: 0;
        -webkit-transform: translate3d(-3000px, 0, 0);
        transform: translate3d(-3000px, 0, 0);
    }

    60% {
        opacity: 1;
        -webkit-transform: translate3d(25px, 0, 0);
        transform: translate3d(25px, 0, 0);
    }

    75% {
        -webkit-transform: translate3d(-10px, 0, 0);
        transform: translate3d(-10px, 0, 0);
    }

    90% {
        -webkit-transform: translate3d(5px, 0, 0);
        transform: translate3d(5px, 0, 0);
    }

    to {
        -webkit-transform: none;
        transform: none;
    }
}

@keyframes bounceInLeft {
    from, 60%, 75%, 90%, to {
        -webkit-transform-origin: 50% 50%;/*update here*/
        transform-origin: 50% 50%;/*update here*/
        -webkit-animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);
        animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);
    }

    0% {
        opacity: 0;
        -webkit-transform: translate3d(-3000px, 0, 0);
        transform: translate3d(-3000px, 0, 0);
    }

    60% {
        opacity: 1;
        -webkit-transform: translate3d(25px, 0, 0);
        transform: translate3d(25px, 0, 0);
    }

    75% {
        -webkit-transform: translate3d(-10px, 0, 0);
        transform: translate3d(-10px, 0, 0);
    }

    90% {
        -webkit-transform: translate3d(5px, 0, 0);
        transform: translate3d(5px, 0, 0);
    }

    to {
        -webkit-transform: none;
        transform: none;
    }
}

.bounceInLeft {
    opacity: 0;
    -webkit-transform-origin: 50% 50%;/*update here*/
    transform-origin: 50% 50%;/*update here*/
    -webkit-animation-name: bounceInLeft;
    animation-name: bounceInLeft;
}
```

here is an example from animate.css that I add some `transform-origin: 50% 50%` code
it works on iOS9.0+ and my iPhone's webview
I hope it can help you

**Comment by semmel** [comment]
Still on iOS 10.3 `bounceInUp` is broken and jumps straight to the final key frame.

... **Unless** 
- the initial animation position is within the page's dimensions (as @woneob suggested on iPhone 5s simulator `3000px` is replaced by `400px`) or,
- the animation starts without delay as the page loads (i.e. is not programmatically added or delayed with `animation-delay`)

Since *animate.css* does not set `animation-delay` the [initial example](https://liger.vm.bytemark.co.uk/animatetest/) from @peterworth should work as promised. However his *animate.css* sets the property in this extra line: 
```css
.animated {
  -webkit-animation-delay: 1s;
}
```
so that his example hits the Safari bug. Remove that line or replace *animate.css* with the original source, and the example works.

In another case I was able to trick iOS Safari to animate an initially hidden element with `transform: translate3d (100%, 0, 0) -> translate3d (0, 0, 0);` by putting a 10 msec delay between setting `display: block` and `classList.add("my-translate-animation")`.
Somehow you'll have to persuade Safari that the to be animated element is visible in the page's view.

**Comment by oleggromov** [comment]
> the initial animation position is within the page's dimensions (as @woneob suggested on iPhone 5s simulator 3000px is replaced by 400px) or,

@semmel Hello, thank you for you comment! It is very helpful. I found this thread accidentally and I don't actually use animate.css library but I'm facing the exact same bug with animation/transition as you described. I have an element located off-screen and on some user action I want it to slide into view. But as it initially sits outside the viewport (`left: 100%`), Safari doesn't animate it. When it slides back, however, everything works as expected. Thanks to you comment, I found that changing the style to `left: 99.99%` or whatsoever helps but it seems to be a dirty hack that I don't want to use. Perhaps you're aware of any neater way to make Safari on iOS render element as I want to. I will highly appreciate any response!

**Comment by Dafrok** [comment]
I guess add `zoom: 1;` in the last frame could save your days.

**Comment by eltonmesquita** [comment]
I'll keep the conversations on #519. Closing it so we can keep everything in the same place.

**Comment by guylando** [comment]
if an element was changed to display:none, then on next animation of that element, ios9 will skip frames to last frame of keyframes? is there a css-only workaround for this which allows to keep the display:none?

**Comment by Nomeh-Uchenna-Gabriel** [comment]
You can use visibility: hidden; instead of display: none;

**Comment by guylando** [comment]
@Nomeh-Uchenna-Gabriel are you suggesting a solution which worked for you? if ios optimizes hidden elements than it might also optimize it for visibility: hidden. Also the element will take space when using visibility: hidden so its a problematic solution.

**Comment by mwiley** [comment]
I changed bounceInRight to look like this, and it seems to have fixed the problem:

```
@keyframes bounceInRight {
...
  from {
    opacity: 0;
    transform: translate3d(100%, 0, 0); // changed from  translate3d(3000px, 0, 0);
  }
...
}
```
