### ISSUE TITLE
animation showing early

### ISSUE THREAD

**Issue by ayazalam** [daneden/animate.css#522]
i have added bounceIn animation to an image in the end of the page but it animate just when the page is loaded. not when the user scroll and see it.

btw nice animations thank you

**Comment by helloeckstein** [comment]
As far as I know, you'll need another plugin like wow.js (or similar viewport plugin) to achieve that.

**Comment by daneden** [comment]
Since Animate.css is a CSS-only library, you’ll need to look into JavaScript in order to achieve your desired result.
