### ISSUE TITLE
License manifest missing

### ISSUE THREAD

**Issue by ilmente** [daneden/animate.css#524]
Hi @daneden,
my congratulations for the really nice work.

Can you please add a license manifest into your repo? While it's true that the css (that contains the link to license) is the object of the MIT terms, a manifest containing those terms is not available in your package.

I'm working for a company, and we are scanning our FOSS in order to make clear view regarding legal issues. We're selling a commercial product that uses your module. From our lawyer prospective, a potential customer could require to see the manifest inside the module: even if linked, a proper MIT license require a copyright holder at the beginning of the manifest, but it is missing. 
Something is in your css indeed, but it's formally wrong because there is no manifest to check.

Can you add it?
Thanks a lot.
Best.
Alessandro

link: https://github.com/daneden/animate.css/issues/445

**Comment by daneden** [comment]
Thanks for your PR, @ilmente!

**Comment by abelspry** [comment]
Hi @daneden,
sorry for bothering you again, but can you update the package on npm too? 
If I download the module from npm, there is no license there.

Thanks.
