### ISSUE TITLE
How to make it shows shadow and save z-index?

### ISSUE THREAD

**Issue by jack-fdrv** [daneden/animate.css#527]
I write my own angular directive for animate.css which works great, and I've noticed that if my animated elements has z-index or shadow it doenst show during animation and after it, so i've binded event which remove animated class after animation end it helps in moz, safari and chrome but not in ie. I try to overwrite rules to disable 3d engine but it not help. Any solution how to not lost shadow and z-index in animation?

**Comment by daneden** [comment]
Do you have an isolated demonstration of the issue you could show us?

**Comment by jack-fdrv** [comment]
I've fixed it again with binded remove class "animated", it happens with css 3D animation. Elements lose z-index.

**Comment by almgwary** [comment]
need help

**Comment by saboorazizi** [comment]
I have find a 3D animation in this website home page https://www.style-instruct.com/. While hover mouse on the image it move up that corner of the image and the shadow grow up.

If you add this in your library or any help resource please.
Thanks

**Comment by eltonmesquita** [comment]
Closing this as it's inconclusive.
