### ISSUE TITLE
Animations not working correctly in IE10

### ISSUE THREAD

**Issue by pinto42** [daneden/animate.css#528]
Any idea on what is causing issues in IE?

**Comment by daneden** [comment]
You’ll have to elaborate—which animations are you having trouble with? Are you sure you’re using the compiled, prefixed CSS?

**Comment by nlound** [comment]
Confirmed for IE10 working ok.

**Comment by sirmelle** [comment]
I am using minified CSS and have problem with windows phone.
I am using IE on Win 8.1
Animations are not shown at all.

**Comment by procodeing** [comment]
@pinto42, could you give a example of what is the exact problem? are the animations not playing right? Are they going of the page? What exactly is "wrong"? And is it IE or edge?

@sirmelle That's a different issue, do you mind making a separate issue?

**Comment by sirmelle** [comment]
OK, I will make a separate issue for this.

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
