### ISSUE TITLE
add main in package.json

### ISSUE THREAD

**Issue by thisconnect** [daneden/animate.css#529]
hi, I love animate.css :)

To use it with postcss + postcss-import it currently needs to be imported like this:
```css
@import "animate.css/animate.css";
```

If a `"main": "animate.css"` would be added then we could just import it with 
`@import "animate.css";`. That is like others do it, see normalize.css:
https://github.com/necolas/normalize.css/blob/master/package.json#L15

**Comment by daneden** [comment]
There is already a `main` property in package.json.

**Comment by thisconnect** [comment]
thanks!
