### ISSUE TITLE
"peek in" effect (close to SlideIn/Out but not quite)

### ISSUE THREAD

**Issue by pliablepixels** [daneden/animate.css#532]
Hello, thank you for this amazing library.
I am using it extensively for my app.

Is it possible to get a "peek in/out" effect ? This is similar to SlideInOut/In effects, but the element does not actually move out of its defined border ? Illustratively I mean this is the difference. If this can already be achieved I'd much appreciate a tip on how

```

                     slideOutRight
   +-------------+     +-------------+
   |             |     |             |
   |             |     |             |
   |   +---------+     |         +---+----+
   |   |  anim   |     |         |  anim  |
   |   +---------+     |         +---+----+
   |             |     |             |
   +-------------+     +-------------+

                      peekOutRight
   +-------------+     +--------------+
   |             |     |              |
   |             |     |              |
   |   +---------+     |         +----+
   |   |  anim   |     |         |  an|
   |   +---------+     |         +----+
   |             |     |              |
   +-------------+     +--------------+

```

**Comment by pliablepixels** [comment]
closed http://stackoverflow.com/questions/35254556/creating-a-peek-in-effect-with-animate-css

**Comment by thowmas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thnghm@gmail.com
    Domain typeshape.com has exceeded the max emails per hour (1/1 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:43799 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by whm01.mammoth.net.au with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aSQNJ-004KJ4-VB
	for tom@typeshape.com; Mon, 08 Feb 2016 01:31:49 +1100
Date: Sun, 07 Feb 2016 06:30:58 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1454855458;
	bh=Zax1AJsbQA5FvlrP0PdoO7ardnzSIs8acptgfMQvexU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=V/3+S5X5f7SfQtXposwm9y9jzw3ZyS8BeaFTmjsfy36zydMaJZDWx3kWfOy7L7g3P
	 cHpybpU5GPapfjaRub+Lwy8Hybqf6TFyDMcz4OwvFr909m9X4LULYMPIOCVnrHA05A
	 +H8gh7MV5qIeCaKMdjiw/f4tZ+KC8mCnT2YArunk=
