### ISSUE TITLE
CSS4 Support

### ISSUE THREAD

**Issue by marcobiedermann** [daneden/animate.css#535]
I would suggest using [CSS4 variables[(https://www.w3.org/TR/css-variables/) instead of switching to Scss #277.
CSS variables are [supported](http://caniuse.com/#feat=css-variables) by Chrome Canary natively which would allow you to use it now in the browser without any transpile process.

**Comment by tnga** [comment]
The reason for using css preprocessor language like **sass** is not only for variable feature. There are others reasons for that (functions, mixins, imbriquetion,..) without worry about browser support. After all it's css (when using scss or less). CSS4 have to be experiment and get large support. and for my point of view, it variable's declaration is pretty unfamiliar :disappointed: . If if I'm wrong, that feature isn't officially approved.

**Comment by marcobiedermann** [comment]
@tnga You are absolutely right. Sass is way more than just variables. But I think this project does not need any.
CSS4 variables do look at first but you will get into it very quickly. Current state is "W3C Candidate Recommendation" but Chrome Canary, Firefox and iOS Safari have implemented them.

**Comment by adamspruijt** [comment]
CSS variables don't solve the problem of loading a 50kb animation library to use 3 effects. Yes you can copy and paste, but that is the entire point of mixins, to not copy and paste. CSS4 solves the issues of convenience and does nothing for performance.
