### ISSUE TITLE
Animate.css not working on the server side in Safari

### ISSUE THREAD

**Issue by santybarandiaran** [daneden/animate.css#536]
Hi, I am building a website, and when I test it locally, all works fine, but when I upload everything to my hosting (000webhost) the animations doesn´t work in Safari. Does anyone know what could be?
Thanks in advance.

**Comment by santybarandiaran** [comment]
I found out what was happening. As I am using a free web hosting, it has adds, and that add is preventing the animation to work. I download an add blocker and now it´s working.
Does anyone know if these can be fixed programmatically without downloading an external application?
Thanks.

**Comment by eltonmesquita** [comment]
This is not related to Animate.css, so we can't help much.
But if you're needing a free host you better use something like [openshift](http://openshift.com) as it won't bring any annoying problem.
