### ISSUE TITLE
BounceIn: scrollbar visible for a moment

### ISSUE THREAD

**Issue by richardsengers** [daneden/animate.css#543]
I'm not sure if this is something we have to fix programmatically or if it can be fixed within the core of animate.css

The problem is, when the html/body have an overlfow of auto (useful for large websites ;-)), the bounceIn animation is showing a scroll bar until the animation is finished. 
https://daneden.github.io/animate.css/ is showing the scrollbar as well

![animatecss](https://cloud.githubusercontent.com/assets/810038/13348715/6ee3da4e-dc75-11e5-9cf5-cd4ae2ee3a3e.png)

Is there a way to fix this within the core of animate.css?
Or do we have to fix it with js and/or css by ourselves?

**Comment by eltonmesquita** [comment]
Nope, this should not be in the core as it'll probably break lots of pages out there. Overflow "issues" should always be handled by the developer as it's something that no library can guess if the body should have or not overflow hidden.

And no, you shouldn't do it programmatically, just a simple ´overflow: hidden´ in the body or container should do it.

If your your question is answered, could you please close the issue?

**Comment by richardsengers** [comment]
Thanks for the quick reply.
I'll close this issue. An overflow: hidden on a body element is most of the time not prefereble on dynamic websites, but a container of the animated element with overflow:hidden also fixes the problem!!!

Thanks 4 the advice!
