### ISSUE TITLE
Cannot combine 2 animation classes

### ISSUE THREAD

**Issue by leikxile** [daneden/animate.css#546]
Tried adding 2 css animation classes but only one works, the last class.

**Comment by eltonmesquita** [comment]
That's how CSS works, you're overriding properties and only the last of them gets used.
If you need two animations at the same time you'll have to put the element inside a container (like a `div`) and add one class in the container (the parent `div`) and the other one in the element itself.

If your question is answered, could you please close the issue?

**Comment by leikxile** [comment]
Alright thanks for the solution!
