### ISSUE TITLE
animate not working at Windows Phone

### ISSUE THREAD

**Issue by sirmelle** [daneden/animate.css#547]
Hello,
I made a website which use animate.css to create some animations. 
On all platforms working well, but only on windows phone with Windows 8.1 installed not working at all.
Divs with animate.css classes not showing up. 
I tried with various animations but nothing helps.
I am using 3.5.1 version.

**Comment by KickinAss** [comment]
Same problem

**Comment by eltonmesquita** [comment]
Does this problem happens on the [demo website](https://daneden.github.io/animate.css/)?

**Comment by KickinAss** [comment]
No, actually the demo works fine.

My problem was (I guess, since I cant' access a debug mode in WP) the opacity set to 0 for the fade not property set to 1. I just fix the problem with modernizer and this fix

```
.cssanimations.requestanimationframe.webanimations .hidden-for-effect {
     opacity:0;
 }
```

(the only cssanimations class didn't work)

**Comment by eltonmesquita** [comment]
Closing this as it seems to be solved.
