### ISSUE TITLE
Animation preserves height and thus next siblings are not moving with the animation

### ISSUE THREAD

**Issue by richardsengers** [daneden/animate.css#551]
I can't figure out how to make this work.
When an animation takes place, the element keeps its preserved height, so next sibling elements are not moving with the animation.
I've created a codepen example
http://codepen.io/richardsengers/pen/EKZmxN

As you can see, the element with the text "hello" stays on its place.

What should I do to make the animations behave like from: {height: 100%} to: {height: 0}

Any help would be appreciated.

Thnx

**Comment by sarbbottam** [comment]
> What should I do to make the animations behave like from: {height: 100%} to: {height: 0}

To the best of my knowledge you can not, `height` can not be animated or transitioned, but `max-height` can be.

> As you can see, the element with the text "hello" stays on its place

There is a possible work around, please see https://jsfiddle.net/oae0rbph/. [On`animationend` event](https://github.com/daneden/animate.css#usage), you can set the `height` to `0`
