### ISSUE TITLE
 Wrong positioning when translateX is set to animate element.

### ISSUE THREAD

**Issue by brokleen** [daneden/animate.css#552]
Hi, 
When i use an animation like bounceIn or tada on an element with a translateX, this element is slightly offset.

Check that : 
http://codepen.io/brokleen/pen/GZWWpj

**Comment by ttrreevvoorr** [comment]
Hey pal
I think this is a problem with your code. I would suggest investigating `transform: translateY(-50%);`. 

Seems to work fine with `transform: translateY(0px);`

Good luck - hopefully you have already figured this out by now.
-Trevor

**Comment by brokleen** [comment]
Hey Trevor, 
Can you reload my code, i did an update : http://codepen.io/brokleen/pen/GZWWpj

If i remove translateY(-50%) the box is no longer centered. 
Check commentary in my css.

**Comment by ttrreevvoorr** [comment]
Hey again
May I suggest removing `transform: translateY(-50%);` from your `.box-center` class and `margin-top: -25px;` from your `.box-center-2` class? I was able to confirm this in Chrome.
Good luck.

**Comment by brokleen** [comment]
I don't understand what did you don't understand.

Box-center and box-center-2 are centered. 

Box element isn't centered.

**Comment by sarbbottam** [comment]
Sorry, I am late to the party.

>When i use an animation like bounceIn or tada on an element with a translateX, this element is slightly offset.

In the the CodePen link there is no `translateX` style used. Could you be precise with what do you mean by slightly offset?

**Comment by brokleen** [comment]
Hi @sarbbottam,
i did an update : http://codepen.io/brokleen/pen/GZWWpj

As you can see, the elements box-center ( blue border ) is vertically centered. If i use animate class on the element box-animate ( red border ), with the same parameters than box-center, this element is not correctly centered.

**Comment by eltonmesquita** [comment]
Animate.css uses transforms to do its magic. Any element that uses transform will get it overwritten. What you can do is to put the element inside a container (like a div), position the container with transform and animate the element or the opposite.

**Comment by sarbbottam** [comment]
Please update the thread with your findings as suggested by @eltonmesquita.

And close the issue if the issue you are facing is resolved. Thanks!

**Comment by fahmilatib** [comment]
@eltonmesquita wow never thought about that approach, cool.
