### ISSUE TITLE
animate.css is loading double time in firefox and chrome

### ISSUE THREAD

**Issue by trsivasankar** [daneden/animate.css#554]
Hi, Anyone please help me on this in my page i used fadeInUp css from animate.css file. when i open in firefox it is loading double time.

This is css i used.

```
@-webkit-keyframes fadeInUp {
  from {
    opacity: 0;
    -webkit-transform: translate3d(0, 100%, 0);
     transform: translate3d(0, 100%, 0);
  }

  to {
    opacity: 1;
    -webkit-transform: none;
     transform: none;
  }
}


```
@-moz-keyframes fadeInUp {
  from {
    opacity: 0;

    -moz-transform: translate3d(0, 100%, 0);
     transform: translate3d(0, 100%, 0);
  }

  to {
    opacity: 1;
    -moz-transform: none;
    transform: none;
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    -webkit-transform: translate3d(0, 100%, 0);
    -moz-transform: translate3d(0, 100%, 0);
    -ms-transform: translate3d(0, 100%, 0);
    -o-transform: translate3d(0, 100%, 0);
    transform: translate3d(0, 100%, 0);
  }

  to {
    opacity: 1;
    -webkit-transform: none;
    -moz-transform: none;
     -ms-transform: none;
    -o-transform: none;
    transform: none;
  }
}

.fadeInUp {
  -webkit-animation-name: fadeInUp;
  -moz-animation-name: fadeInUp;
  -ms-animation-name: fadeInUp;
  -o-animation-name: fadeInUp;
  animation-name: fadeInUp;
}
```

some times i am getting same error in chrome also

**Comment by sarbbottam** [comment]
> loading double time

What do you mean by 'loading double time'?
