### ISSUE TITLE
Why animation copied from .site__title in Animate.css homepage is not work?

### ISSUE THREAD

**Issue by chenweiyj** [daneden/animate.css#555]
I want to show the gradient animation like `.site__title` in Animate.css homepage. I copied following code but it does not work on my website.

```
color: #f35626;
background-image: -webkit-linear-gradient(92deg,#f35626,#feab3a);
-webkit-background-clip: text;
-webkit-text-fill-color: transparent;
-webkit-animation: hue 3s infinite linear;
```

**Comment by sarbbottam** [comment]
Please create either a [CodePen](http://codepen.io/), [JSBin](http://jsbin.com/), [JSFiddle](https://jsfiddle.net/) as an example of the issue you are facing.
