### ISSUE TITLE
remove @-webkit-keyframes

### ISSUE THREAD

**Issue by user67x** [daneden/animate.css#557]
Hello,

Could you remove old  value with -webkit, when I try to validate my css I have this warnong : "Désolé mais la règle-arobase @-webkit-keyframes n'est pas implementée"

Thanks

**Comment by sarbbottam** [comment]
Why would you validate a generated third party asset? `@-webkit-keyframes` are generated by [autoprefixer](https://github.com/postcss/autoprefixer) as `-webkit` prefix is required for [iOS Safari 8.4](http://caniuse.com/#search=keyframes) and [last two version of standard browsers are supported by animate.css](https://github.com/daneden/animate.css/blob/master/gulpfile.js#L26-L29).
