### ISSUE TITLE
Can we control the "size" of animations?

### ISSUE THREAD

**Issue by githorse** [daneden/animate.css#559]
I can change the duration of animations with `animation-duration`. Is there any way to change the distance translated by the element across the page on, say, a `fadeInLeft` or `slideInLeft`? In some cases I would like to have a subtler effect where the element moves just slightly on the page. I'm probably overlooking an easy way to do this.

**Comment by bennetthardwick** [comment]
Hi!

The transform that is used in fadeInLeft is `transform: translate3d(-100%, 0, 0);`. Therefore, changing the width of the element you're animating will change the distance that it travels on fading in. You can have a look at this fiddle if you like:
https://jsfiddle.net/fvqus3am/
I've shown the border boxes of all the elements so you can see what's going on. 

Alternatively, you can modify the distance travelled in your CSS by using:
 `@keyframes fadeInLeft{ from{ transform: translate3d(-40px, 0, 0); }}`
Please note that this will fadeInLeft from -40px of the final position, but it will change the value for ALL .fadeInLeft elements, so be careful. 

I hope this helps you out!

**Comment by sarbbottam** [comment]
`fadeInLeft` or `slideInLeft` or any other effect are pre-determined and opinionated steps, there is no way to modify other than override.
