### ISSUE TITLE
Animation not working all the time with Jekyll

### ISSUE THREAD

**Issue by markorapaic** [daneden/animate.css#560]
Hello,

I'm trying to achieve a simple on hover animation using the coffeescript below, my website is running on the latest version of Jekyll.

```
$(document).ready ->
  $('.site-title img').addClass 'animated jello'
  $('.page-link').hover ->
    $(this).toggleClass 'animated jello'
```
The first portion works - as soon as the page loads, the `animated jello` classes get added to `.site-title img` and it animates. However the second portion doesn't work. I can see that the classes are being added to `.page-link` on `hover` - however, no animation occurs.

What do you think might be causing this?

**Comment by eltonmesquita** [comment]
`display: inline-block` it. Animations will not work on inline elements. This is part of the CSS specs.

**Comment by markorapaic** [comment]
You nailed it first go - that was the issue. Thank you! :smile: :+1:
