### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by 10SexyApples** [daneden/animate.css#561]
Just attempted to install and hit this error ... 

```
└─[$]> bower install animate --save
bower animate#*             not-cached https://github.com/joshuapekera/animate.git#*
bower animate#*                resolve https://github.com/joshuapekera/animate.git#*
bower animate#*               checkout 1.0.1
bower animate#*             EMALFORMED Failed to read /var/folders/d7/s2kts_td0m9dcjwgqlmcm05c0000gn/T/macbook/bower/a2a424217f809672e8fe80ddeab36781-71780-a63xtn/bower.json

Additional error details:
Unexpected token }
```

**Comment by 10SexyApples** [comment]
Just discovered this issue is due to unusual naming convention ... need to use install using animate.css, not just animate~

**Comment by BenBuck123** [comment]
Unsubscribe

On Saturday, 9 April 2016, Angelia Baladon <notifications@github.com> wrote:

> Just discovered this issue is due to unusual naming convention ... need to
> use install using animate.css, not just animate~
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/daneden/animate.css/issues/561#issuecomment-207715802>
>


-- 
Sent from my iPhone
