### ISSUE TITLE
Question: copyright

### ISSUE THREAD

**Issue by Ledragon** [daneden/animate.css#564]
Hi,
First, thanks for the library, and the effort invested!
Second, I am preparing for deployment of my application, and thus citing all libraries I use. I realized your project does not have a license file (I saw you are under the MIT license) nor copyright; who shall I cite as author?

**Comment by eltonmesquita** [comment]
The author is Daniel Eden. The creator of animate.css.

**Comment by Ledragon** [comment]
Thx fo the info!
