### ISSUE TITLE
Safari Browser

### ISSUE THREAD

**Issue by vcmonterosso** [daneden/animate.css#565]
Animate.css Does not work in Safari 5.1

None of the fadeIns work. Does anyone have a solution?

**Comment by JoshuaDoshua** [comment]
This package uses gulp and autoprefixer.
Either autoprefixer thinks Safari does not need the `-webkit-` prefix, or Safari needs to be declared in autoprefixers browsers definition.

I usually explicitly declare the webkit prefix in my sass

**Comment by sarbbottam** [comment]
**It is not desired to**, [only last 2 browser version is supported](https://github.com/daneden/animate.css/blob/master/gulpfile.js#L26-L29)

```js
autoprefixer: {
    browsers: ['last 2 versions'],
    cascade: false
},
```
