### ISSUE TITLE
Webpack loader - if you want to include a link.

### ISSUE THREAD

**Issue by andreijs** [daneden/animate.css#567]
Hey mate,

Greate work on this I have created a webpack loader for this so you can selectively include your animations when you use animate.css. 

https://github.com/andreimc/animate-css-webpack

Maybe you could include it in the readme ?

**Comment by MarkHerhold** [comment]
Awesome! I'll have to give this a try!

**Comment by eltonmesquita** [comment]
@andreijs could you please send a PR adding it to the read me?
