### ISSUE TITLE
Animation on element removal

### ISSUE THREAD

**Issue by smohamali** [daneden/animate.css#568]
Is it possible to trigger an animation on document element removal?
So far I have been animating document elements which are being added to the page through angularjs ng-if for example.

**Comment by eltonmesquita** [comment]
You can animate and then remove it. You can't manipulate an element that is not in the DOM. If I'm not wrong Angular has a method (callback, or whatever) that can execute a function before the removal of the element.

Ps.: If this solves your problem, please close this issue.

**Comment by smohamali** [comment]
Thanks Elton. I see what you mean, I need to use ngAnimate which makes certain directives "animation aware". For example:

`<div ng-repeat="item in items" ng-animate="{enter: 'animate-enter', leave: 'animate-leave'}">`

I would then replace animate-enter and animate-leave with the classes I want from this library.
