### ISSUE TITLE
click and mouse events are not working with animate.css, only ready is working.... how to enable all events of animate.css with jquerry

### ISSUE THREAD

**Issue by sriranjanm** [daneden/animate.css#569]

**Comment by eltonmesquita** [comment]
It's hard to help you this way. Could you create a pen, share it here and describe the problem the best you can?

**Comment by sriranjanm** [comment]
animate.css is working for only onload(ready) event. it is not working for
other events like mouseover,mouseout,click and etc..

i tried like this

jquerry:

$("#btnlogin").ready(function () {
            $('#div').addClass('animated bounceInLeft');

        });
above code is working..

but below code is not working

$("#btnlogin").on('click',function () {
            $('#div').addClass('animated bounceInLeft');

        });
help me where  i have gone wrong??

**Comment by sriranjanm** [comment]
This is My Whole Program


<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs"
Inherits="_Default" %>

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head2" runat="server">
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/motion-ui.css" />
    <link rel="stylesheet" href="css/style.css" />
    <link href="script/motion-ui-starter/css/animate.css" rel="stylesheet"
/>


    <link href="script/motion-ui-starter/css/motion-ui.css"
rel="stylesheet" />

    <link href="script/motion-ui-starter/css/foundation.css"
rel="stylesheet" />
    <link href="script/motion-ui-starter/css/style.css" rel="stylesheet" />
    <script src="script/motion-ui-starter/js/vendor/modernizr.js"></script>

    <style>
        .animated {
            animation-duration: 2s;
            animation-delay: 0s;
            animation-iteration-count: 1;
        }

        .flash {
            animation-delay: 3s;
        }

        .auto-style1 {
            width: 100%;
            border: 2px solid #000066;
            background-color: #cccccc;
        }

        .auto-style4 {
            width: 513px;
            height: 44px;
        }

        .auto-style7 {
            height: 52px;
            text-align: center;
            color: #FFFFFF;
        }

        .auto-style9 {
            height: 44px;
            width: 1403px;
        }

        .auto-style10 {
            height: 53px;
        }
    </style>
    <script src="script/motion-ui-starter/js/script.js"></script>
    <script src="script/motion-ui-starter/js/foundation.min.js"></script>
    <script src="script/motion-ui-starter/js/vendor/jquery.js"></script>
    <script src="script/motion-ui-starter/js/vendor/motion-ui.js"></script>

    <script src="script/motion-ui-starter/css/Java.min.js"></script>
    <script>
        $('#div').ready(function () {
            $('#div').addClass('animated bounceInLeft');

        });

        $('#TextBox1').on('click', function () {
            $('#TextBox1').addClass('animated shake');

        });
    </script>
</head>
<body>

    <form id="form1" runat="server">
        <div style="position: absolute; top: 63px; left: 2px; width: 280px;
height: 203px; bottom: 513px;" id="div">
            <table class="auto-style1">
                <tr>
                    <td class="auto-style7" colspan="2"><strong>Login
Here</strong></td>
                </tr>
                <tr>
                    <td class="auto-style4">User ID</td>
                    <td class="auto-style9">
                        <asp:TextBox ID="TextBox1" runat="server"
Height="43px" Style="margin-left: 15px" Width="194px" CssClass="animated
flash"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style4">Password</td>
                    <td class="auto-style9">
                        <asp:TextBox ID="TextBox2" runat="server"
Height="44px" Style="margin-left: 14px" Width="196px" CssClass="animated
flash"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style10" colspan="2">
                        <asp:Button ID="Button2" runat="server"
Height="36px" Text="LOGIN" Width="94px" />
                        &nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>

**Comment by eltonmesquita** [comment]
Please, [create a pen](http://codepen.io/) and isolate the problem. It's kinda hard to help with code pasted in a comment...
