### ISSUE TITLE
Padding or margin error

### ISSUE THREAD

**Issue by gmelen** [daneden/animate.css#575]
It appears as if the box-sizing were wrong on the "animate-it" button

<img width="644" alt="screen shot 2016-05-03 at 6 27 32 pm" src="https://cloud.githubusercontent.com/assets/18314382/15001410/d8e5325a-115c-11e6-8b0d-b90e8aa6a703.png">

**Comment by daneden** [comment]
This looks like a browser bug and is unlikely to be fixable by myself.
