### ISSUE TITLE
Simultaneous animation graphic bug Chrome

### ISSUE THREAD

**Issue by stan69b** [daneden/animate.css#576]
When using animate CSS on 3 elements (maybe more) simultaneously, the third one animated is being animated over the visible default version of the element.

![bug](https://cloud.githubusercontent.com/assets/3304418/15097903/835071a0-152c-11e6-86c6-2bbae4043128.jpg)

**Comment by daneden** [comment]
This seems like a browser bug and should be reported to the browser vendor.
