### ISSUE TITLE
bounceInDown doesn't work on iPhone 6

### ISSUE THREAD

**Issue by A-2-D** [daneden/animate.css#581]
Just tried to use the bounceInDown animation & it doesn't work on my iPhone 6 even on the official website.

Also some other bounceIn animations are not working. They work on the smallest breakpoint in chrome but not on my iPhone 6.

**Comment by daneden** [comment]
This is probably due to a browser bug in Safari iOS and not a bug in Animate.css.

**Comment by A-2-D** [comment]
Ok, thanks for letting me know. Hopefully they fix this bug soon.

Thanks for provided us with your awesome work!
