### ISSUE TITLE
gulp autoperfix not work

### ISSUE THREAD

**Issue by vahidalvandi** [daneden/animate.css#582]
when i build gulp result szie animate.css = 23kb but in source animate.css = ~65kb why?????

then after use result gulp in fadeinright show scroll Horizontal and hide scroll

and dont add -webkit in result

**Comment by eltonmesquita** [comment]
Please follow all the [instructions](https://github.com/daneden/animate.css#custom-builds) for custom builds.
Closing this, but feel free to reopen the issue if needed.
