### ISSUE TITLE
Animation not working on explorer edge

### ISSUE THREAD

**Issue by juggernautt** [daneden/animate.css#583]
Hello,
I've used your library to create an animation - opening flower using classes rotateInDownLeft, rotateInDownRight and fadeIn. It works fine in chrome, opera and mozilla, but not in explorer edge. When I open a browser I just see my images (flower petals) arrive form different part of a screen like in powerpoint presentation. So it looks like animation classes doesn't work properly there.. or maybe I missed something... Anyway, I would appreciate any help or advice. 
Thank you 

Upd: I just made some tests and it looks like  classes rotateInDownLeft and rotateInDownRight behave differently  in explorer edge. i.e. instead of rotation to left or right its like come flying from the side of a screen. Still be happy to hear your suggestions how to solve this issue.

**Comment by tnga** [comment]
Hi, in this case, provide a codepen example or alternative can be useful. How about the behavior with usage of javascript web-animation API? (for example you can take a look: https://github.com/tnga/lib.ijs). These can determine if issue depend of how edge implement css's animation features or if it depend of your code.
