### ISSUE TITLE
Any examples on how to use to animate elements from/to display: none?

### ISSUE THREAD

**Issue by cyphix333** [daneden/animate.css#584]
I am testing this out but it doesn't seem to work too well; I'm trying to use it to animate to a `display: none;` state and vice-versa, but it seems to animate from the top of the screen rather than from where it's supposed to.

**Comment by elbsurfer** [comment]
My assumption is, that display: none / display:block does not work with CSS transitions.

**Comment by cyphix333** [comment]
Well not really, but you can get it to work with keyframes.
