### ISSUE TITLE
Great job! but I have troubles using it with mdl light

### ISSUE THREAD

**Issue by MarcosGalaviz** [daneden/animate.css#585]
Hi, this work is excelent, but  I am triying to use this animations witn mdl light : 

`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
 <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
 <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>`

But in that case the divs wich I want to animate has the display : hidden , I think is an isuue with the js of mdl light, but I cant find the problem :(

**Comment by daneden** [comment]
You should provide isolated demos of bugs you encounter with your issue, and issues here should pertain specifically to Animate.css, not to interference with other libraries.
