### ISSUE TITLE
animate-config.json structure

### ISSUE THREAD

**Issue by moose56** [daneden/animate.css#591]
Hi,

In the readme it mentions you can customise the build by setting the different options to true of false in the animate-config.json file.

In the actual animate-config.json file the options are stored in arrays not object literals so you need to remove the items from the array that you don't want in the final build.

Is this just a case that the readme needs updating?

David.

**Comment by coclav** [comment]
HI, 
;
I looked at the source of the build gulp file and it can't work as documented. i.e. there is nothing testing the true/false claim in the build script.

anyway : the best way I found is to just remove the line(s) of what you don't need. You can remove full categories. Leave only what you need. 

For example my remaining file is 

`
{
  "bouncing_entrances": [
    "bounceInRight"
  ]
}
`

**Comment by andreamaiolo** [comment]
Hi,
I've created a simple script that runs after installing all the node_modules and allows you to edit the `animate-config.json` automatically.

1. Install all the dependencies - `$ npm install`
2. Select using the console the animations you need
3. Run `gulp` to compile your custom library

See pr #558

**Comment by eltonmesquita** [comment]
#695 will fix this.
@andreamaiolo please see https://github.com/daneden/animate.css/pull/558#issuecomment-314216060
