### ISSUE TITLE
Using jQuery addClass not working with uppercase characters

### ISSUE THREAD

**Issue by cptstarling** [daneden/animate.css#592]
I'm using the following code:

```
$('.block-facetapi').hover(
    function(){ $(this).addClass('expanded animated fadeInDown') },
    function(){ $(this).removeClass('expanded animated fadeInDown') }
);
```

The result is that none of the classes is added _(Chrome v50.0.2661.102 [64-bit], Mac)_. However, when I change `fadeInDown` to `fadeindown` (all lowercase) they all get added as they should. But currently the class _should_ be written with uppercase characters, or the animation won't work.

Wouldn't it be better to abandon the uppercase characters in class names altogether, to guarantee compatibility? The use of uppercase characters for code is generally discouraged anyway, and since about 90% of the _animate.css_ selectors consist of class names with one or more uppercase characters, it's a huge drawback to use it.

**Comment by eltonmesquita** [comment]
I think you should check your code, as classes are case insensitive. Maybe a pen with the issue could help?
