### ISSUE TITLE
New class for speed of animation

### ISSUE THREAD

**Issue by sonphnt** [daneden/animate.css#595]
Hi,

I think it would be a great idea if we can include some classes with speed of animation like: slow, normal, fast, superfast.

And we can use like this "animated fadeIn fast"

Thanks

**Comment by cobbyamoah** [comment]
Great suggestion. It will simplify things.

**Comment by fatbattk** [comment]
So just a shortcut for `-vendor-animation-duration: 3s;` ?

Instead, what is missing is an option for a **pause delay _between_ infinite** animations.

**Comment by samwisegrangee** [comment]
I double fatbattk's suggestion for a delay between animations.

**Comment by eltonmesquita** [comment]
As @fatbattk cited, that would be just a small shortcut for a single property. I doesn't seem to be worth the effort.

About the delay between animations, that is simply not possible with CSS, so it's a no go.
Closing this.
