### ISSUE TITLE
Animate.css and typeahead z-index problems.

### ISSUE THREAD

**Issue by phlegx** [daneden/animate.css#596]
Hi! I use typeahead.js and animate.css to animate the input field of typeahead.

``` html
<div class="animated bounceIn">
    <form id="typeahead-form"...>
        ...
    </form>
</div>
```

**Problem:** the dropdown of the typeahead is shown like transparent. If I remove the animation all works fine. So, the animation seams to change some CSS to the typeahead form. Any idea?

**Comment by tonimichel** [comment]
I experience the same issue with ordinary bootstrap dropdowns, after an animation has finished.
It seems as if the -webkit-transform: translateY(0) property on the parent element causes a very weired z-index-like effect for children with position absolute.

<img width="389" alt="screen shot 2016-11-25 at 10 46 26" src="https://cloud.githubusercontent.com/assets/479271/20620949/969e0ea2-b2fc-11e6-9f73-2ed630c9f12d.png">

**Comment by elasticsteve** [comment]
Any solution for this? This is driving me nuts for hours!

**Comment by lbrealeza** [comment]
Here is the solution!

Change:
.animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-fill-mode:both;animation-fill-mode:both}

To:
.animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-fill-mode:none!important;animation-fill-mode:none!important}

**Comment by Bizarrus** [comment]
Thanks for the solution!

But, the `z-index` won't work if the animation is currently running.

**Comment by eltonmesquita** [comment]
As animate.css uses 3d Transforms for performance reasons, the z-index might not be respected in some cases. Please read this article to understand a little bit and fix your issues:
[http://katydecorah.com/code/z-index-and-transform/](http://katydecorah.com/code/z-index-and-transform/)

I'll close this as it's not a real issue, but a side effect. Might be worth to add some notes in the readme to warn about this particular behavior. Linking #681 to take note on this.
