### ISSUE TITLE
Transformation not working when using :hover ?

### ISSUE THREAD

**Issue by lokiiiii** [daneden/animate.css#603]
Hello there,

I got an issue when using ":hover" css transformation animations :
the animations that don't transform the text work (for example "flash" is working) but not the ones using transformations like "pulse".

I've made a jsfiddle to explain this:
https://jsfiddle.net/7ngtwfrL/3/

Do you have any idea ?
Thanks a lot !

**Comment by sivendra** [comment]
Hey You See There Add This IntoYour Editor


<head>
<style>
a{
text-decoration:none
}
h1
{
position:re	lative;text-align:center
}
h1:hover {
  animation: pulse 2s infinite;
  -moz-animation: pulse 2s infinite;
  -webkit-animation: pulse 2s infinite;position:relative;
  cursor:pointer
}

</style>
  <link rel="stylesheet" href="http://s.mlcdn.co/animate.css">
</head>
<body>

<div class="column2">
<h1><a href="#">Welcome To pulse</a></h1>
</div>
</body>

**Comment by lokiiiii** [comment]
OK I understand my mistake, thank you :)

**Comment by sivendra** [comment]
welcome again
