### ISSUE TITLE
Detecting when animations end isn't reliable

### ISSUE THREAD

**Issue by Quas94** [daneden/animate.css#604]
I'm using it as directed from the Github description:

```
			$('#loginModalDialog').
				one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',
				function() {
					console.log('ANIMATION ENDED');
					$timeout(function() {
						$scope.login.failed = false;
					}, 100);
				});
```

However after multiple tries (around 3 or 4) the animation ending simply doesn't get detected (no console log, and the variable isn't updated).

Anyone have any suggestions? thanks

**Comment by gazpachu** [comment]
I have experienced also issues with this. It tends to work well if there's one animation at a time, but if you start mixing a few of them, then it becomes unreliable.

**Comment by eltonmesquita** [comment]
Have you tried this method: [https://davidwalsh.name/css-animation-callback](https://davidwalsh.name/css-animation-callback)?

I'm lacking the time to test the method described in the readme and send a PR to fix it. I might do it in the future if no one do this before.

**Comment by jamesmichaelhickey** [comment]
I was having a similar issue with a certain callback being triggered again in a weird way. The fix from David Walsh's blog was perfect! Here's the result:

```
function whichAnimationEvent(){
    var t;
    var el = document.createElement('fakeelement');
    var animations = {
      'animation':'animationend',
      'OAnimation':'oAnimationEnd',
      'MozAnimation':'Animationend',
      'WebkitAnimation':'webkitAnimationEnd'
    };

    for(t in animations){
        if( el.style[t] !== undefined ){
            return animations[t];
        }
    }
}
```

And, just call the Jquery extension like:

```
var animationEnd = whichAnimationEvent();
$(this).addClass('animated ' + animationName).one(animationEnd, function () {
    doStuff(); 
});
```
