### ISSUE TITLE
animate.css on slideshow text

### ISSUE THREAD

**Issue by imdorothy** [daneden/animate.css#607]
i would like to have a slideshow with animated text. But only 1st slide of my slideshow is working well. the rest of the slides is not having animation..

May I know how can I modify the code to have my 2nd slide's text and so on have the animation?

Thank you so much

**Comment by realslimshanky** [comment]
Simply add animation to the text only when they are displayed to the screen. This can be done easily using javascript.

**Comment by daneden** [comment]
@imdorothy CSS animations are applied as soon as the element/node is rendered on the page, so it's likely that the animations *are* happening on the other slides, but all happening at once. You could try only adding animation classes when the element actually appears on the screen (i.e. when the user moves to the next slide) using JavaScript.
