### ISSUE TITLE
Add a timer between loops when using infinite class ?

### ISSUE THREAD

**Issue by lokiiiii** [daneden/animate.css#609]
Hello,
Is there a way to specify a timer between two occurrences while using the infinite class ? 
Because right now, the loop just repeat as soon as it ends and it's pretty aggressive :)
Thanks a lot.

**Comment by eltonmesquita** [comment]
Sorry, but it's not possible with only CSS as far as I can remember.  You'll have to use Javascript for this behaviour.

**Comment by MosheLevi** [comment]
I think you can set up delay between animations or just prolong the animation duration and set few to be on the same state. i'm no expert but it may be a solution.

**Comment by skeet** [comment]
I ended up using the following:

```
  window.setInterval(bounceArrow, 5000);

  function bounceArrow() {
    $('#arrow').removeClass('animated bounce').delay(1000).queue(function(next) {
      $(this).addClass('animated bounce');
      next();
    });
  }
```

**Comment by bookoobusiness** [comment]
@skeet Perfect.
