### ISSUE TITLE
Animate.css not working in chrome 51.0 but works in firefox

### ISSUE THREAD

**Issue by ARKKYN** [daneden/animate.css#610]
i am using animate.css in angular SPA it is not working in chrome 51.0 but works in firefox

**Comment by eltonmesquita** [comment]
There's no way to help with so little information. First of all, isolate the issue to make sure it's not a problem with your code. Then, if the problem continue, make a pen and share here.

**Comment by douglasjunior** [comment]
I dont know about pure Angular, but with Ionic I have to add animation using [`$timeout`](https://docs.angularjs.org/api/ng/service/$timeout).

```javascript
  $timeout(function() {
       var element = document.getElementById("myElement");
       element.classList.add('animated');
       element.classList.add('flash');
  });
```

With `$timeout` the function is executed after the view update.

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
