### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by jcaruso001** [daneden/animate.css#611]
You cdn is down

**Comment by andrewkirc** [comment]
Seconded. This one is working in the meantime.
https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css

**Comment by nueverest** [comment]
Could you update the Readme to send people here: [https://cdnjs.com/libraries/animate.css/](https://cdnjs.com/libraries/animate.css/)?

**Comment by daneden** [comment]
Fixed in #627.
