### ISSUE TITLE
Animate.css and wow.js compatibility

### ISSUE THREAD

**Issue by F-Tahir** [daneden/animate.css#614]
Hi.

I'm using animate.css and wow.js together, so I can set duration, delays etc. Are these 2 plugins compatible with IE9? If not, are there alternative stylesheets one can load, or some modifications I can make to disable animations on the older browsers?

Thanks.

**Comment by Vernando05** [comment]
animate.css uses CSS3 animation properties which is not supported for older browser like IE9 http://caniuse.com/#feat=css-animation. 

You can use feature detection library such as Modernizr.js to set fallback for your animation.
