### ISSUE TITLE
Not working with ionic 2

### ISSUE THREAD

**Issue by SanjayYadav90** [daneden/animate.css#616]
hi Team,
I follow the steps as here-
https://github.com/daneden/animate.css,
but it wont seems working well here with ionic 2.
This is ionic information of my machine-

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v6.2.2
Xcode version: Xcode 7.2 Build version 7C68 

Let me know if it work with ionic-2 and how in case if it works.

**Comment by shahzeb1** [comment]
You might find the following comment helpful:

https://github.com/daneden/animate.css/issues/610#issuecomment-233965575

**Comment by joshi-mehul** [comment]
Hi Sanjay, your issue seems good, but the thing is animate css is a CSS lib. so any way just check your code is it's adding class properly or not, or just check whether your code gets executed. if any css is working then animate should work. :-)
