### ISSUE TITLE
Add namespacing

### ISSUE THREAD

**Issue by erikaperugachi** [daneden/animate.css#618]
Is possible add a prefix in your css class?, because sometimes your class crash when add this in others websites. Sometimes is difficult change the css in advanced project or when I make a little plugin or widget that other users added I can't manipulate this problem in other site that I don't have access.

**Comment by morajabi** [comment]
You can prefix them yourself, but I think its a good idea to make a custom variable in SASS files to specify prefix for lib and then compile.

**Comment by Rafi993** [comment]
just use @extend to extend the animation classes and then use them in your code in scss

.anim-lightspeedin{
@extend .lightspeedin;
}

**Comment by eltonmesquita** [comment]
Although this can be worked around as @Rafi993 mentioned, I think this deserves some attention and should be included in the next big launch (4.x branch). Keeping this issue for further discussion.

**Comment by daneden** [comment]
I'd like to proceed without relying on Sass and with a specific namespace for animate.css (as opposed to custom namespaces). Are there any major objections to this?

As a proposal, would `anim` be the right call?

```
.anim-animated {
…
}

.anim-bounce {
...
}
```

**Comment by janydrozd** [comment]
Hi @daneden , is it still open? I could work on this.

**Comment by WarenGonzaga** [comment]
@janydrozd yes but it is assigned to me and this will be available on v4.0 and we still discussing it.. so this one would be held for now. Until we finalize it. :) You can suggest features to us. Just create a new issue. Thanks!

**Comment by jakubmuda** [comment]
Why don't you use data attributes?

`.animated` would become `[data-animate]`

`animated pulse` would become `[data-animate="pulse"]`.

It would be independent of classes and no prefix is needed.

**Comment by WarenGonzaga** [comment]
@jakubmuda this is already added on v4 beta ;) anyway thank you for your help.

**Comment by eltonmesquita** [comment]
It's available on the dev branch now!
