### ISSUE TITLE
Dead CDN links in README.md

### ISSUE THREAD

**Issue by lukejacksonn** [daneden/animate.css#620]
It seems that smallcdn ceases to exist or is down so the following links no longer work..

http://smallcdn.rocks/
http://s.mlcdn.co/animate.css

**Comment by ammichael** [comment]
Meanwhile: https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css

**Comment by daneden** [comment]
Solved in #627
