### ISSUE TITLE
Possible to make appear a div plus animated ?

### ISSUE THREAD

**Issue by jacargentina** [daneden/animate.css#621]
I have a layout where i have a navbar on top, then a "rooms" navbar below it, and then the "workspace" below it. the workspace is invisible while you dont choose any room. when clicking a room to enter, the workspace is displayed.

Currently, i have the workspace DIV with `display: none` but when trying to integrate animate.css to "zoon in down" the connected room on entering it, i've found that the DIV must be `display: block` for it to work.

My problem is that then the workspace is already there without any contents (the chat room empty... etc)

Which would be "the way" to achieve the effect i desire? Or is it not possible ?

**Comment by sinamotamedi** [comment]
You can try using jQuery to change the display from none to block and also add animated class. You can see something similar done [here](http://www.directplumbingpdx.com/) although this loads the element and adds the animated class when a user scrolls down and has the element insight whereas you'd want to do it after they choose a room first.
