### ISSUE TITLE
Animate.css is not working in any browser.

### ISSUE THREAD

**Issue by Devrathi** [daneden/animate.css#623]
I used animate.css in Dreamweaver and its not working in any of the browser.
Please Help.
My code is:

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Animate</title>
<link rel="stylesheet" href="animate.min.css">
</head>

<body>
<h1 class="animated shake">Animation</h1>
</body>

**Comment by shahzeb1** [comment]
Hello,

Your code seems to be improperly pasted.

**Comment by Devrathi** [comment]
**My Code is**:

`<head>`
`<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />`
`<title>Animate</title>`

`<link rel="stylesheet" `href="animate.min.css">
`</head>`

`<body>`
`<h1 class="animated shake">`Animation`</h1>`
`</body>`

**Comment by eltonmesquita** [comment]
This can be anything. Could you please create a pen on Codepen and share it with your code?

**Comment by Diego-Soares** [comment]
@shahzeb1 Try put class "visible" in element.

**Comment by Devrathi** [comment]
@eltonmesquita This is my link to pen on Codepen: https://codepen.io/devrathi/pen/oLmXmz

**Comment by Diego-Soares** [comment]
Look in my example:
https://codepen.io/diego92ms/pen/zBZvrk
You need call the library Animate, correct way.

**Comment by Devrathi** [comment]
@shahzeb1 I saw your code and I don't think there is any difference in the code but your code is working fine but not mine. Can you please explain where I am doing wrong? Thanks.

The animate.css **CDN** is not working.

**Comment by eltonmesquita** [comment]
@Devrathi, you're not adding the animate.css to the page. If you go to the Settings of the pen and click in CSS, you'll see the @Diego-Soares added the link to animate.css.

**Comment by klingtnet** [comment]
There is no animation In chromium 52 and Firefox 48, previous version worked fine. I haven't changed any styling in the mean time.
I'm using animate.css `3.5.0` for my [website](https://klingt.net) (the logo at the top is animated via `flipIn`).

**Comment by klingtnet** [comment]
**UPDATE** Animation works, my webserver's minify directive was the problem.

**Comment by Devrathi** [comment]
Thank you @eltonmesquita it worked, but can you tell if I want to use the animate.css in my website then should I have to download animate.css or I can just use the CDN.

**Comment by anthonydelgado** [comment]
You should only rely on the CDN for testing. If you are going to use it for a live website download the package to your project.

**Comment by nawrasma** [comment]
klk

**Comment by ilechukwuoliverk** [comment]
animate.css files not downloading in my browser instead shows me raw.githubusercontent.com
am using google chrome

**Comment by eltonmesquita** [comment]
Please, follow the instructions on the readme and avoid linking files directly from GitHub.
