### ISSUE TITLE
fadeIn doesn't work after fading item out with fadeOut

### ISSUE THREAD

**Issue by Geoffie** [daneden/animate.css#624]
I have tried animate.css and i realized when fading "out" a div then fading it "In" again it doesn't appear. what happens when you fadeOut an item, is the entire item deleted from the dom ? why can't it be faded back "In" .

**Comment by n-jay** [comment]
Hi, isn't there a solution to this? 
It's 2020 and I'm still encountering this problem.

**Comment by Retours** [comment]
Hi n-jay,

Encountered the same issue, and thought about you when I "solved" it the hacky way.
Seems like you need two things for it to work:
- the fadeout animation needs to be finished (has to do with classes I think)
- you need to manually set the element visibility to visible BEFORE doing the animation (I know, makes no sense)

Hope that clears things out for you, I did it in a messy way so won't paste any code here, best way to do this would be to use callbacks I guess.
