### ISSUE TITLE
Trigger Animation When In View / Scroll

### ISSUE THREAD

**Issue by spw52889** [daneden/animate.css#628]
I was wondering what do I need to do make the animations only trigger when its in view? And possibly repeat only on down scroll? 

Thank you!

**Comment by eltonmesquita** [comment]
You've got to use something like this: https://github.com/camwiegert/in-view
or this: https://gist.github.com/eltonmesquita/bd803a21f27b12a58df1

If your question is solved, please close this issue.
Thx!
