### ISSUE TITLE
Regression on bounce animate.min.css introduced in 3.5.1

### ISSUE THREAD

**Issue by jrobichaud** [daneden/animate.css#629]
The bounce animation of "animate.min.css" does not work properly in Safari since 3.5.1.

The issue does not happen with "animate.css", only with "animate.min.css".
1. Open Safari on Mac and on chrome
2. Open https://jsbin.com/teraye/3/edit?html,js,output
3. Press on the bounce button and notice there is a delay and the animation's translation
4. Change the animate css library url in the html from 3.5.2 to 3.5.0
5. Press on the button again and notice there is no delay and the translation is higher (Safari and Chrome now both looks the same)

**Comment by eltonmesquita** [comment]
Sorry, but there was [no alteration of the code](https://github.com/daneden/animate.css/commits/master/source/attention_seekers/bounce.css) for the bounce animation between those versions. Closing this issue.

**Comment by jrobichaud** [comment]
I think you missed the point. The version of the source code is fine like you said but the minimized version is incorrect.

**Comment by eltonmesquita** [comment]
Sorry, my mistake. I'll investigate this, as the compiled version really has differences.

**Comment by eltonmesquita** [comment]
It got fixed in the last commits and the fix will be live on the next version.
