### ISSUE TITLE
IE Animations Disappear

### ISSUE THREAD

**Issue by wihodges** [daneden/animate.css#632]
Issue with IE animations not working in any version. 'fadeInRight' just rotates and fades out. 

Finally figured out it was caused by gulp cssnano minification, "animation-name:" gets rewritten into shorter letter pattern. animation-name: fadeInRight becomes animation-name: z
Seems to work in all other browsers except IE. 

This is not a bug with animate.css directly but thought I'd share because I have only experienced this minification issue with these sets of animations.

**Comment by Sparragus** [comment]
Yep. Same thing over here. Be careful with cssnano + animate.css. Not an issue of this library but thank god someone had reported it so I don't go crazy looking for the bug. Thanks @wihodges

**Comment by shooby** [comment]
so, how did you work around this issue?

**Comment by Sparragus** [comment]
I removed the animation.
