### ISSUE TITLE
where is the water animation?

### ISSUE THREAD

**Issue by deeperx** [daneden/animate.css#634]

**Comment by eltonmesquita** [comment]
?????
Better make it clear, mate.
This makes no sense.

**Comment by deeperx** [comment]
In the README.md documentation it says:

> Just-add-water CSS animation
> 
> animate.css is a bunch of cool, fun, and cross-browser animations for you to use in your projects. Great for emphasis, home pages, sliders, and general just-add-water-awesomeness.

So, I wonder, where is the water effect? There is no documentation about it. I've also searched on the code in github, and couldn't find anything about water-effect but the documentation.

**Comment by chantellmocha** [comment]
You may be taking it too literally.. Just-add-water is being used as a literary device.

Though a water animation would be rather nice to see.

**Comment by deeperx** [comment]
Ohh, OK then :) I didn't know that, sorries.

**Comment by eltonmesquita** [comment]
@deeperx, could you please close this issue as it's solved?
