### ISSUE TITLE
animation is finished before the page scroll to the Item

### ISSUE THREAD

**Issue by mazdak78** [daneden/animate.css#635]
I added animated classes to some items at the bottom of the page.  The problem is the animation is done before the user scroll down to that Item or Div, Should I add anything so animation happen when the user scroll to it?

Thanks
Mazdak

**Comment by Vernando05** [comment]
yes, you need to set a trigger when user scroll down to certain pixel

**Comment by mazdak78** [comment]
Thanks.. i can not find any sample code for that, can you point me to one pleade?

**Comment by Vernando05** [comment]
By using this lib (JQuery one) http://imakewebthings.com/waypoints/ you can set 'offset' option to set the trigger point, http://imakewebthings.com/waypoints/api/offset-option/
 
here's the pen http://codepen.io/Vernando05/pen/pEbvGo
