### ISSUE TITLE
Exit animation problem in Aurelia project

### ISSUE THREAD

**Issue by danielheddelin** [daneden/animate.css#636]
I have a div with a show.bind condition. In the GUI there is a checkBoxList that on check of either one/multiple, a div should appear. I would like the entrance and exit of the div to slideInUp and then slideOutDown as the binding condition changes, such as:

`<div class="animated ${myListOfObjects.length ? 'slideInUp' : 'slideOutDown'}" show.bind="myListOfObjects.length">`

For some reason, this works for the slideInUp animation, but when I expect the slideOutDown to occur - the element instead disappears. (The same happens when using if.bind)

The first work-around I tried was to remove the if/show binding and instead manipulating the div's properties in the DOM on load, such as setting its height to 0 on load. This instead caused the animation to trigger immediately on page load even though I had told it to be invisible.

As of now, I ended up re-adding the show.bind to get the right visibility/invisibility, but I have had to introduce a 'third state' to mimic the "notLoadedQuiteYet" scenario, like so:

`<div class="animated ${myListOfObjects.length ? 'slideInUp' : (boolThatIsTrueOnceUserClickedTheFirstCheckbox ? 'slideOutDown' : '')}" show.bind="boolThatIsTrueOnceUserClickedTheFirstCheckbox">`

In words: If we have 0 objects in the list AndAlso the user has not interacted with the checkboxList - append NO animation class to the div.

It would be awesome to somehow stop animations from triggering until everything is loaded fully.

**Comment by daneden** [comment]
This issue seems to be related to a library besides Animate.css, which I can’t help you with. The issues for this repository should pertain specifically to the Animate.css library.
