### ISSUE TITLE
How do I get the animation to start on scroll?

### ISSUE THREAD

**Issue by Akshu18** [daneden/animate.css#639]
Animation starts on load...even before the particular section with animation is being scrolled...please help.

**Comment by coliff** [comment]
Check out:
http://mynameismatthieu.com/WOW/
https://github.com/matthieua/WOW
It does exactly what you want (and is powered by animate.css)

**Comment by eltonmesquita** [comment]
@coliff, better use https://github.com/michalsnik/aos
Wow is abandoned and aos is the way to go now...

**Comment by kristian-welsh** [comment]
Shouldn't this be closed?

**Comment by felipewarrener** [comment]
This is not an issue, this is simply poor usage.
