### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by ZLHysong** [daneden/animate.css#641]
Chrome Console gives this error when reloading any page in my project that contains this file.

I says it is on line 1:  `@charset "UTF-8";`

**Comment by dotamir** [comment]
just in the Chrome console ?

**Comment by ZLHysong** [comment]
So far as I know, yes. Nothing appears different on screen.

**Comment by eltonmesquita** [comment]
Not an issue, just some specific and isolated Chrome's behavior.
Closing this.

**Comment by yanickrochon** [comment]
What do you mean "Not an issue"? How can this be resolved?

**Comment by eltonmesquita** [comment]
This isn't something related to the project itself. As far as I can remember, one single version of Chrome was throwing this error without a real reason but it didn't break anything. Also 99% of the cases this kind of error happens is not animate.css' fault as it's just CSS and that's usually related to Javascript code.

**Comment by unclespode** [comment]
I had this issue, ended up here via Google. It turned out I had tried to load the CSS file as a JavaScript file - i.e user error. Might help someone else.

**Comment by soccerKevin** [comment]
I can confirm that this error is caused by trying to load css as a script tag

**Comment by Lahirutech** [comment]
> I can confirm that this error is caused by trying to load css as a script tag

Solved it

**Comment by OC-Dev** [comment]
> I can confirm that this error is caused by trying to load css as a script tag

Sometimes it's the real simple things when you're just tired or not really in the mood - Can't believe I was trying to load in a CSS file under a Script tag...
