### ISSUE TITLE
Lightspeedin

### ISSUE THREAD

**Issue by cyberf4n** [daneden/animate.css#642]
Any idea how make the lightspeedin effect to slide from left? 
Thank you

**Comment by Rafi993** [comment]
If you are using scss you can use @extend and extend .lightspeedin and change direction
```

.rightlightspeedin{
  @extend .lightspeedin;
    animation-direction: reverse;
}
```

or else you could use plain css to override animation-direction property

**Comment by cyberf4n** [comment]
Thanks !!!
