### ISSUE TITLE
Can't slow down animation fade in?

### ISSUE THREAD

**Issue by robgnyc** [daneden/animate.css#645]
I'm trying to slow down the duration of a fadein animation using:

-webkit-animation-duration: 8s;
	-moz-animation-duration: 8s;
	-ms-transition-animation-duration: 8s;

However it doesn't seem to do anything. The animation delay works but not the duration.

**Comment by codebubb** [comment]
Hi, how are you applying the CSS rules? I've found that if you apply duration changes to a top level element e.g. div, img etc the animation duration isn't changed.  However if you use an id on the element you wish to affect (and then target this with your CSS selector) the duration is changed.  

Take a look at: (http://codepen.io/codebubb/pen/vXPdrR) if you try targeting the <img> element directly the duration doesn't change.

Hope that helps.

**Comment by robgnyc** [comment]
Thanks so much.

Using an id worked.
