### ISSUE TITLE
'Jello' animation incompatible with latest iOS Safari?

### ISSUE THREAD

**Issue by felipewarrener** [daneden/animate.css#646]
If I to the test site for the animations all of them except 'Jello' work. 

I can see why Jello would maybe have issues as it's very complex however needs to be fixed!

**Comment by procodeing** [comment]
What device are you using?

The reason I ask is that I tried it on the site with my SE, and it worked perfectly.

**Comment by eltonmesquita** [comment]
Safari 10 is having some issues with transform on some situation, but it's a browser bug that shouldn't be handled in the library itself.
Closing this issue.
