### ISSUE TITLE
Bad naming effects!!!

### ISSUE THREAD

**Issue by belozer** [daneden/animate.css#648]
(good) `FadeInUp` - fade-in from down to up
(good) `FadeInDown` - fade-in from up to down
(good) `FadeOutUp` - fade-out to up
(good) `FadeOutDown` - fade-out to down

But... :bomb: 
__(bad!) `FadeInRight` - fade-in from right to left__
__(bad!) `FadeInLeft` - fade-in from left to right__
(good) `FadeOutRight` - fade-out to right
(good) `FadeOutLeft` - fade-out to left

This naming breaks the understanding in the other animations.
`bounce`, `slide`.

**Comment by msheakoski** [comment]
Maybe FadeInFromBottom, FadeInFromTop, FadeInFromLeft, FadeInFromRight?

**Comment by belozyorcev** [comment]
FadeInRight -- fade-in from left to right
FadeInLeft  -- fade-in from right to left

**Comment by Zearin** [comment]
How about:

- FadeInRTL
- FadeInLTR

**Comment by DaSchTour** [comment]
FadeInRight is the opposite of FideOutRight. So I FadeInUp and FadeInDown are bad. In and Out should have the same direction to be reversible.

**Comment by belozer** [comment]
@DaSchTour With such logic, it is better to make it so

`FadeRightIn, FadeRightOut, FadeUpIn, FadeUpOut, FadeIn, FadeOut` etc...

**Comment by belozer** [comment]
@daneden What do you think?

**Comment by WarenGonzaga** [comment]
I think this is good for easy understanding...

**Comment by eltonmesquita** [comment]
Although I do agree with some points, I don't think it's a good idea to change this as it'll break people's projects.
Closing this.

**Comment by WarenGonzaga** [comment]
Hmmm @eltonmesquita you have point...

**Comment by hellodaniel** [comment]
This has driven me mental for years and I keep meaning to check the issues log. Every single time I get it wrong. You can see @belozer's point though: 
- `fadeInUp` fades in moving up
- `fadeInDown` fades in moving down
- `fadeInLeft` fades in moving **right** _(i.e.: backwards_)
- `fadeInRight` fades in moving **left** _(i.e.: backwards)_

I don't really want to drag up an old point, and agree with @eltonmesquita that it would break existing projects, but I'd love to know if there was any rationale behind this being backwards or any plans to change it in future major releases?

**Comment by jeanieherold** [comment]
a fadeIn from the left moves right
a fadeIn from the right moves left

so really it is not backwards depending on how wording interpreted.

**Comment by hellodaniel** [comment]
> a fadeIn from the left moves right a fadeIn from the right moves left so really it is not backwards depending on how wording interpreted.

I know what you mean, but it's counter to the up/down fades. `fadeInUp` moves up (as expected) so `fadeInLeft` should move left, not _from_ the left (thus actually moving right, as it does). Following that logic `fadeInUp` should fade in from up to down, so it's literally the definition of opposite.

**Comment by jeanieherold** [comment]
haha! you are right!!

is funny to think about!
