### ISSUE TITLE
Animation in Google Chrome Not Fluid

### ISSUE THREAD

**Issue by edarioq** [daneden/animate.css#650]
When loading the site in Google Chrome, the fadeIn animation I have on H1 tags in my HTML is laggy, jagged, not fluid.  When looking from Edge, Safari, Firefox, the animation is perfect.

Weird as I always thought Chrome is usually the browser without any issues. Has this happened to anyone else. If so how did you fix it? Or am I doing something wrong on my end.

**Comment by eltonmesquita** [comment]
This can be anything. It's hard to guess what's happening, but usually this is related to some script being executed at the same time of the animation.

**Comment by edarioq** [comment]
Ok so gonna try maybe changing loading order of some scripts. The site I'm building is http://www.life72bogota.com/staging/apartamentos/, just in case you have a min to spare (sorry). Regardless thanks so much for your input.

**Comment by eltonmesquita** [comment]
Try to add the class when the DOM is ready. It might help in your case.

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
