### ISSUE TITLE
iframe inside animated block - bug

### ISSUE THREAD

**Issue by Tusko** [daneden/animate.css#655]
Hi! 
When I'm using `iframe`with Vimeo/Youtube video inside animated block, the fullscreen doesn't work in Google Chrome.
please add the fix : 

    :-webkit-full-screen-ancestor:not(iframe) {
        transform: none !important;
        animation: none !important;
        opacity: 1 !important;
    }

**Comment by eltonmesquita** [comment]
Although this is something that appeared as an issue more than once, it's a browser's quirk. I don't think it would be a good idea to add this to the library itself as it may cause some other problems.
Might be a good idea write some more documentation and add these kinds of quirks.
I'm closing this, but feel free to reopen it in case you think there's a need for more discussion.
