### ISSUE TITLE
Laggy animations

### ISSUE THREAD

**Issue by siba2893** [daneden/animate.css#656]
Hi I just set up a div with an image to fadeInLeft but its to laggy to be used any idea?

`<div class="row services-section animated fadeInLeft">`

**Comment by eltonmesquita** [comment]
That depends entirely on what's happening in your page in the moment of the animation. If your DOM is huge (there are a lot of element in the page), or if there are a lot of animations going on at the same moment, the animations can get laggy. Javascript, DOM updates, repaints and reflows can cause it too.

Maybe a [pen](http://codepen.io) with your code might help us debug it and try to find the problem.

**Comment by eltonmesquita** [comment]
Close this as it's stale. Feel free to re-open it.
