### ISSUE TITLE
Animations removing other CSS transforms

### ISSUE THREAD

**Issue by br0wnie1991** [daneden/animate.css#657]
Hey, I have a div with one of the animations on (bounceInLeft) which works beautifully. However, I also have a transform: skew(-20deg); on that div which is removed when using the animation class.

Is there a way around this? Sorry if I'm not posting in the correct thing or what have you. I'm new!

Thanks!

**Comment by eltonmesquita** [comment]
Wrap it in another element and animate the wrap.

**Comment by eltonmesquita** [comment]
Closing this issue as it's stale.
