### ISSUE TITLE
Chaining animations ?

### ISSUE THREAD

**Issue by Legends** [daneden/animate.css#658]
Is it possible to chain animations elegantly, while the following works, you have to nest this multiple times:

```
var animationEnd = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
						
$("body").animateCss("flip");
$("body").on(animationEnd, function () {
	$(this).animateCss("bounce");
});
```

**Comment by eltonmesquita** [comment]
I don't think there's an easy to achieve this. If you're chaining a lot of animations, there's a big chance you'd be better with an animation library like green sock or or velocity.

**Comment by MarcoRey86** [comment]
I use wowJS and play with the duration of the animation, 
You can check the WOW page https://wowjs.uk/
If someone uses something different please let me know

**Comment by imjosh** [comment]
@Legends @eltonmesquita see #678

**Comment by rohitm** [comment]
Use promises. Works for me
example -

```
const bounceInImage = (image) => new Promise((resolve, reject) => {
  image.addClass('animated zoomIn').one(animationEnd, () => {
      image.removeClass('animated zoomIn');
  });

  setTimeout(() => {
    resolve(true);
  }, 100);
});

const showImages = () => {
  $('.round-image').parent().toArray().map((image)=>{
    return(()=>{
      return (bounceInImage($(image)));
    });
  }).reduce((pacc, fn) => {
    return pacc = pacc.then(fn);
  }, Promise.resolve());
}
```

**Comment by shankariyerr** [comment]
I had to use animation-delay and chain 4 sets of animation.

**Comment by eltonmesquita** [comment]
As I think this is solved, with plenty of options, I'll close this. Let's keep the repo tidy.

**Comment by Skura23** [comment]
I find this is a good solution:
https://codepen.io/austencm/pen/WvbwQa

**Comment by aislanmaia** [comment]
@Skura23 do you have some example without JQuery?
