### ISSUE TITLE
Positioning issue with some effects

### ISSUE THREAD

**Issue by Legends** [daneden/animate.css#660]
I just played around with bootstraps popover and thought why not animate it.
So it works fine with many effects like bounce, but not with pulse and several others more.

I have to create an additional css class to  fix the positioning:
[jsBin](http://jsbin.com/loqusit/edit?html,js,output)

**Comment by WarenGonzaga** [comment]
Probably it is a bug... I guess they have conflict in CSS part.

**Comment by WarenGonzaga** [comment]
Be careful and using Animate.css with other libraries mostly in CSS. Like on GSAP I had a trouble in using both css and gsap at the same time and they had conflict in some aspect and pars of animation. You should  base your element on how the animation created for animate.css.

Waren | Animate.css Enthusiats

**Comment by eltonmesquita** [comment]
Animate.css uses mostly transforms and opacity to do its magic, if Bootstrap or any other style in the page is setting one of those things in the element, you're going to have some sort of problem. 

Closing the issue as this seems stale anyway.
