### ISSUE TITLE
Pause between iterations

### ISSUE THREAD

**Issue by eriktobben** [daneden/animate.css#662]
Hi!

How can I pause the animation for X seconds between iterations? Is it possible?

**Comment by procodeing** [comment]
It is possible using pure JS, see my [pen](http://codepen.io/procodeing/pen/bgdeMK)

**Comment by eltonmesquita** [comment]
As @procodeing cited, javascript is the solution here. I'll close the issue but any more question, just re-open it @eriktobben .
