### ISSUE TITLE
Flippers, choice of direction, upturn effect

### ISSUE THREAD

**Issue by dawadam** [daneden/animate.css#664]
Hello,
Concerning the transition "flippers", "flip".
It would be nice to be able to choose the direction.
Currently there is only one direction, for example for the Y axis:
Exit (out) is by turning to the right and enters (in) turning to the left.
It would be convenient to enter (in) by turning to the right and exit (out) by turning to the left.
It would then be possible to combine two transitions to make a upturn effect.
Thanks

**Comment by eltonmesquita** [comment]
You can do this easily using the `animation-direction: reverse` property, like [this](http://codepen.io/eltonmesquita/pen/xqdpPQ). Even though it's really simple, I'm considering adding this as an modifier class in a future release.
