### ISSUE TITLE
How to properly hide element to be slideInRight?

### ISSUE THREAD

**Issue by donsingh** [daneden/animate.css#666]
Say I have a sidebar called `popmenu` that sticks on the right hand side. 
I want it to be somewhere offscreen/hidden and then use jquery to append slideInRight.

So far this works for toggling it:
```
$(".burger").on("click", function(){
        if( $(".popmenu").hasClass("animated slideOutRight") ){

            $(".popmenu").removeClass("animated slideOutRight");
            $(".popmenu").addClass("animated slideInRight");

        }else{

            $(".popmenu").removeClass("animated slideInRight");
            $(".popmenu").addClass("animated slideOutRight");

        }
});
```

But this means the sidebar is displayed onload. **How do I have it initially hidden?**

Also... this doesnt seem to be working...
```
.popmenu{
        -webkit-animation-duration:0.3s;
}
```

**Comment by aSchaffe** [comment]
use css animate from to     
   @-webkit-keyframes slide {

          0% {
            opacity: 0;
            -webkit-transform: translateX(-100%);
            -moz-transform: translateX(-100%);
            -ms-transform: translateX(-100%);
            -o-transform: translateX(-100%);
            transform: translateX(-100%);
          }
          100% {
            opacity: 1;
            -webkit-transform: translateX(0%);
            -moz-transform: translateX(0%);
            -ms-transform: translateX(0%);
            -o-transform: translateX(0%);
            transform: translateX(0%);
          }
        }

**Comment by donsingh** [comment]
Not sure if I got it right. The above code only fixes the problem with the duration but its still there onload.
The element in question has this:
```
.popmenu{
  padding-top:30px;
  position:fixed;
  top:0;
  right:0;
  background-color:rgb(0,168,80);
  -webkit-animation-duration:0.3s;
}```

**Comment by johnhogan87** [comment]
I am doing something similar on a project so thought I would see if I can help. I believe I have got your pen to work as you want: https://codepen.io/johnhogan/pen/pRdQEy

Hope that helps,

John

**Comment by donsingh** [comment]
This is great. Thanks a lot @johnhogan87 !

**Comment by eltonmesquita** [comment]
Closing the issue as this seems to be solved.

**Comment by donsingh** [comment]
@eltonmesquita as this does solve the current problem, is this the team's preferred method in initializing an element to be hidden?

**Comment by eltonmesquita** [comment]
This is something that is due to the developer to decide. There's no better way as it depends a lot of the project. My opinion is, just hide it with CSS - like: `position: absolute; left: -100%` - then add the animate class , an additional class to position the element to the place you need - like `left: 0;` - on click and you're done. But it's up to you to find the way that best suits your project.
