### ISSUE TITLE
FadeInUp seems to disable the navbar-fixed-top.

### ISSUE THREAD

**Issue by nipungarg59** [daneden/animate.css#667]
whenever i use both of them my navbar scrolls away with the page and when i remove fadeInUp everything work's fine. I have used fadeInUp propert from animate.css in my MainApp.jsx. I want to use both of them, so is there any way to fix the problem. [Here](http://stackoverflow.com/questions/41970298/how-to-use-fadeinupfrom-animate-css-with-navbar-fixed-top) is the question I asked on stackoverflow.

**Comment by eltonmesquita** [comment]
Closing this as it's solved on stackoverflow already.
