### ISSUE TITLE
Eliminate render blocking?

### ISSUE THREAD

**Issue by vishy93** [daneden/animate.css#668]
Is there a way to stop this from render blocking ?

**Comment by eltonmesquita** [comment]
It's not something that is related to this library, but how you load your stylesheets. [Read this article](https://varvy.com/pagespeed/render-blocking-css.html), it might help.

If the issue is solved, please close it! ;D

**Comment by vishy93** [comment]
Are we allowed to concatenate the css file into one with others ?

**Comment by eltonmesquita** [comment]
Of course, animate.css is just plain old CSS, you can do anything you do with CSS.

**Comment by vishy93** [comment]
Just wanted to confirm I wasn't breaking the license terms

**Comment by eltonmesquita** [comment]
Just keep the header with license info in the file and you're good, as animate.css is MIT licensed.

**Comment by eltonmesquita** [comment]
Closing this as I think it's solved. Fell free to re-open it if you need.
