### ISSUE TITLE
Problem with fadeInLeft effect on mobile and RTL web pages

### ISSUE THREAD

**Issue by amraei** [daneden/animate.css#669]
There is a problem with RTL pages and mobile browsers. I recorded a witch which shows you the problem. You can see hotos which are fade in from right side are showing properly, but fadeInLeft effects are broken. 

I have tested it on Android 4.4.2 and Chrome browser. Also the same problem exists on responsive mode of Chrome on desktop PC (Ubuntu 16.04).

![feb 17 2017 1-08 am](https://cloud.githubusercontent.com/assets/3328211/23042534/45c125c0-f4ae-11e6-9050-1de5632c2024.gif)

**Comment by eltonmesquita** [comment]
I don't know if I understood your problem, but try to add `overflow: hidden` on the container for the items.

**Comment by amraei** [comment]
@eltonmesquita Can you see the GIF video? In cases which `fadeInLeft` effect has been assigned, whole body will be animated (3rd photo). 

Adding `overflow: hidden` to the container won't be a good idea because can cause unexpected behavior for other absolute elements like drop-downs.

**Comment by eltonmesquita** [comment]
But did you try `overflow: hidden`? Does it fix the issue?

**Comment by amraei** [comment]
@eltonmesquita Yes, `overflow: hidden` solves the problem. But on LTR webpages it's not required for `fadeInRight` effect..

**Comment by eltonmesquita** [comment]
@amraei , on LTR this doesn't happens because of the normal flow of the pages. The rule is, the elements that grow to the right (in this case the container) adds to the vertical space of the page, elements that grow to the left doesn't add to the vertical space. Same for top and bottom. There's no easy solution, as far as I know.
You can add the elements being animated in a wrapper and set the overflow and width (like `width: 100%`) in this wrapper and not the whole container.

**Comment by amraei** [comment]
Thanks! I did some research and seems their isn't really a simple way to solve it.

**Comment by mahramane** [comment]
Hi
I have the same issue too
Please help

**Comment by eltonmesquita** [comment]
> @amraei , on LTR this doesn't happens because of the normal flow of the pages. The rule is, the elements that grow to the right (in this case the container) adds to the vertical space of the page, elements that grow to the left doesn't add to the vertical space. Same for top and bottom. There's no easy solution, as far as I know.
> You can add the elements being animated in a wrapper and set the overflow and width (like `width: 100%`) in this wrapper and not the whole container.

Have you read this solution? There aren't many options for this as it's the way webpages work.
