### ISSUE TITLE
_base.css gets ignored in gulp compile task due to Sass type naming convention

### ISSUE THREAD

**Issue by jabranr** [daneden/animate.css#672]
@daneden 

In my Gulp workflow to compile various files together `_base.css` is getting ignored due to Sass type naming convention. If I remove underscore from front of it then it compiles fine. I can set rule in Gulp however but then I have to set certain rules for Sass imports that also start with an underscore.

Does this make sense to you? So I will push a fix for it by renaming the `_base.css` to `base.css`?

**Comment by eltonmesquita** [comment]
I think you do have an edge case here. I think it's better to focus our efforts on the sass version, that will probably fix your case. Mind if I close this?

**Comment by jabranr** [comment]
Any idea when sass is set to release? This was not related to the sass version of `animate.css` though. The problem appears to be in concatenation gulp task for css files of it. Here is the task for reference:

![image](https://cloud.githubusercontent.com/assets/2131246/23831509/dc784696-071a-11e7-9331-d005374455ab.png)

So here it simply ignores the `_base.css`. So for a workaround I now have a separate task that copies the `_base.css` to temporary directory and renames it to `base.css` before it is called in modified version of above gulp task. Hope this clears the issue.

**Comment by eltonmesquita** [comment]
At the moment my priority is to close all the stale/solved, etc issues. I'm getting close. There'll be at least one more minor release in the 3.x branch to fix some issues and add some small improvements.
After this release, I'll try to focus the efforts on the sass branch, including all the PR's that need proper review. I'm planning some stuff, there are some issues to be fixed and some approaches to be discussed and decided,, but still no ETA.

Sorry if it wasn't clear, but I wanted to say is that the sass version will fix your issue, but that it's not worth the effort to fix this particular issue in the 3.x branch.

**Comment by jabranr** [comment]
Thanks for the detailed reply! That makes perfect sense. I'll also try to add my input wherever possible to push for sass branch out. Cheers

**Comment by eltonmesquita** [comment]
Looking forward for your contributions.
