### ISSUE TITLE
How to add animate.css in ionic 2

### ISSUE THREAD

**Issue by madara134** [daneden/animate.css#674]
Hello ! i was install via npm: npm install animate.css --save
Then i include the stylesheet on my index.html
i want animation when change page and this is my code
`this.navCtrl.push(DetailPage, { id: id }, { animate: true, animation: 'fadeIn' })`

**Comment by nevilRootweb254** [comment]
ok i use a simple code in jquery;


function animate(){
    $(document).ready(function(){
            var end = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
            $('#subscribe').fadeIn();
            $('.flex').addClass('animated bounceIn','slow');
            $('.heder').addClass('animated zoomInLeft','slow');
            $('.flex').one(end,function(){
                $('.flex').removeClass('animated bounceIn');
            });
            $('.heder').one(end,function(){
                $('.heder').removeClass('animated zoomInLeft');
            });
        });
}
window.addEventListener('unload',animate,false);
thats the simple code i use .where i have added my own classes just use yours that you wanna animate.

**Comment by madara134** [comment]
thanks you

**Comment by nevilRootweb254** [comment]
year am also youtuber watch my videos play list on https://www.youtube.com/playlist?list=PLLR5k-d4xvLkNLerWUYof5AKgrVH_MOoX its about animate.css intergration to your web page .am making onother video right now then upload please subscribe to get notification

**Comment by nevilRootweb254** [comment]
welcome

**Comment by madara134** [comment]
@nevilRootweb254 🥇 Can you help me. i already use animte in ionic 2. It is very smooth on brower. but it not good in android... It is not smooth

**Comment by nevilRootweb254** [comment]
are you a web developer or ?

**Comment by madara134** [comment]
Mobile developer

**Comment by nevilRootweb254** [comment]
i am a web application developer i can share web related code.Would you mind me sharing that and get the idea from it?

**Comment by eltonmesquita** [comment]
Closing this as it's not related to Animate.css anymore.
