### ISSUE TITLE
Would be great to make mobile support more robust

### ISSUE THREAD

**Issue by davidvb** [daneden/animate.css#676]
On iOS many of the effects dont work at all, or not as expected, in both safari and chrome (chrome having more issues actually.) Would be wonderful to see a solution for that.

**Comment by eltonmesquita** [comment]
Is this happening in the [demo](http://daneden.github.io/animate.css) page?

**Comment by DanFeather** [comment]
FWIW: I tried more than half, including from each category. They all worked. (iPhone SE, current release iOS).  BUT, on revisiting the page, it was old-school ugly, with raised button and pull down. And no animations of course. I refreshed a time or two, and it changed appearance and animated again. Weird?

**Comment by eltonmesquita** [comment]
@DanFeather this is looking something like a cache issue. Does the device have enough storage? Anyway, Safari is constantly being a headache in my life. Too many weird bugs to deal with.

**Comment by DanFeather** [comment]
Not sure how to determine "enough storage" on iPhone. The settings indicate I've > 14 GB space available. I can't find anything about cache size in Settings > Safari (> Advanced). . . . 

Your comments about Safari make me wonder about using animate.css. The clients' websites I monitor have HUGE audience share with iPhones, so performance there is pretty darned important to me.

**Comment by eltonmesquita** [comment]
Nope, there is no performance issues with Safari. The problem is that in last 2 major updates (9 & 10) transforms are a bit bugged on it. In some conditions unexpected behavior can happen, but usually it doesn't.

I advise to test, if possible, in other iOS devices to make sure it's not an isolated issue with a single device.

**Comment by eltonmesquita** [comment]
Please, see #519.
Closing as it's stale.
