### ISSUE TITLE
IE11 weird issue for slideInRight and slideInLeft

### ISSUE THREAD

**Issue by windmaomao** [daneden/animate.css#677]
I debugged 1-2 hours just to realize this is strange, hopefully someone here some explanation . for basic translation from right to left, it simply doesn't work in IE11

```
  from {
    transform: translate3d(0, 0, 0);
    visibility: visible;
  }

  to {
    transform: translate3d(100%, 0, 0);
  }
```

however if i change it to, it works

```
  from {
    transform: translate3d(100%, 0, 0);
  }

  to {
    visibility: visible;
  }
```

I simply can not add the transform line to key-frame to, is this outrageous ?

**Comment by cybernet** [comment]
just an offtopic
nothing works IE, it's against all laws of developers :)

**Comment by windmaomao** [comment]
@cybernet I'm actually aware of that. Unfortunately, they run the other half of the earth.

**Comment by eltonmesquita** [comment]
I'll  have a look at this, but as far as I know, it worked ok on IE 11.

**Comment by eltonmesquita** [comment]
Yep, it does work ok on IE11 in my tests. Make sure that you're animating a block level, or inline-block element as IE usually behave strangely when you're animating inline elements.

**Comment by eltonmesquita** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by pnzimmer** [comment]
I have the same problem, SlideInLeft and SlideOutLeft doesn't work in IE11 - please help.
The Div Layer has a display: block attribute.

**Comment by chauhanshab** [comment]
Who's this ?

:-@Gaurav

**Comment by chauhanshab** [comment]
I'll have look at this, but i think it work ok on IE11

**Comment by pnzimmer** [comment]
Thank you, would be great. In every other browser it's working.

**Comment by KaizenBrian** [comment]
The problem is actually depending on which version of IE11 you got. 
We are experiencing problems with several animation in the older version of IE 11.  (See attached image)

![image](https://user-images.githubusercontent.com/20729064/35060872-dbd8ce28-fbbf-11e7-9239-70c440b11fb9.png)
