### ISSUE TITLE
Recent 3.5.2 release not updated in bower registry

### ISSUE THREAD

**Issue by AJStacy** [daneden/animate.css#680]
I am attempting to update animate.css in my forked repo. After deleting the files in my bower_components, running a bower cache clean, and confirming that my version number in my bower.json is correct, the package.json file for animate.css still reads `"version": "3.5.1"`.

The output of `bower install -S animate.css` is as follows: 

```
bower not-cached    https://github.com/daneden/animate.css.git#^3.5.2
bower resolve       https://github.com/daneden/animate.css.git#^3.5.2
bower not-cached    https://github.com/daneden/animate.css.git#3.5.2
bower resolve       https://github.com/daneden/animate.css.git#3.5.2
bower download      https://github.com/daneden/animate.css/archive/3.5.2.tar.gz
bower download      https://github.com/daneden/animate.css/archive/3.5.2.tar.gz
bower extract       animate.css#^3.5.2 archive.tar.gz
bower extract       animate.css#3.5.2 archive.tar.gz
bower resolved      https://github.com/daneden/animate.css.git#3.5.2
bower resolved      https://github.com/daneden/animate.css.git#3.5.2
bower install       animate.css#3.5.2

animate.css#3.5.2 bower_components/animate.css
```

Is this a bug or am I doing something wrong?

**Comment by eltonmesquita** [comment]
Yep, it wasn't updated on 3.5.2, just a small mistake. It is fixed on the master branch and will get a release soon.

**Comment by pdzugas** [comment]
I don't think this version mismatch has been resolved. Today I have installed your package in my Ember project via bower and I have observed exactly what @AJStacy has reported = bower downloads version 3.5.2 while _package.json_ and _animate.css_ contents alone still contain version information 3.5.1

**Comment by eltonmesquita** [comment]
Closing this as Bower is being killed. Please see #758 and keep all the discussion about bower support there.
