### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#681]
At the moment there are lots of PR adding important bits for the usage of Animate.css but our `readme.md` is bloated enough. I think it's time to think about a dedicated webpage with more details about Animate.css and its use.

Opening this issue for discussion about format, content and whatever about is related to the docs pages.

**Comment by equinusocio** [comment]
Why not github wiki?

**Comment by eltonmesquita** [comment]
Yep, Wiki can be a good way, but I was thinking about something more flexible and - why not -  beautiful. My initial ideia is to provide some live example and code and include a live search. Something like [Vue.js's guide](https://vuejs.org/v2/guide/), which is of great help and is great to use.

**Comment by fazykn** [comment]
Agreed!

**Comment by WarenGonzaga** [comment]
Agree!

**Comment by eltonmesquita** [comment]
I'm closing this, let's keep the conversation on #835.
