### ISSUE TITLE
Animate only one word in <h1>

### ISSUE THREAD

**Issue by vidsav** [daneden/animate.css#682]
Hello I need advice on how to use one of the animations on just on word in <"h1"> text. I tried with adding <"font class="some random animation"> to the specific word but it doesn't work, any of them. Any advice?

Please help :)

**Comment by fslDev** [comment]
http://codepen.io/anon/pen/XMEazQ

**Comment by imjosh** [comment]
http://codepen.io/anon/pen/XMEazQ

**Comment by vidsav** [comment]
Thanks a bunch :)

**Comment by DaSchTour** [comment]
Just as a side note. Using `<font>` within HTML5 breaks a lot of things and creates strange errors. So don't use font tag. Never!

**Comment by eltonmesquita** [comment]
As other side note, always animate an inline-block or block level element. Inline elements have issues animating. Just set the element as one of those and everything should be ok.

Closing this as it's solved.
