### ISSUE TITLE
When the element use 'zoomOut' class, it will go through a period of blank

### ISSUE THREAD

**Issue by ReedSun** [daneden/animate.css#683]
The class [zoomOut](https://github.com/daneden/animate.css/blob/master/source/zooming_exits/zoomOut.css) is 
```
@keyframes zoomOut {
  from {
    opacity: 1;
  }

  50% {
    opacity: 0;
    transform: scale3d(.3, .3, .3);
  }

  to {
    opacity: 0;
  }
}
```
If `animation-duration` is 1s, the element is blank during 0.5s~1s.  When I want to  detect when an animation ends, I have to experience blank time and then executive the callback function. I think this is not a good experience.

Thank you for writing such a good library! Have a nice day.

**Comment by nevilRootweb254** [comment]
you want the code or? I can write you a code that adds and remove the class so that animation can't experience blank time

**Comment by WarenGonzaga** [comment]
I think he needs a code...
