### ISSUE TITLE
Change class and apply new animation?

### ISSUE THREAD

**Issue by xlcrr** [daneden/animate.css#686]
I have a list being populated. Once it reaches a certain length, I want to change the animation class of the first item and remove the item from the array with a new animation

Using Laravel 5.4 and Vue2

```
<ul id="myList">
  <li v-for="item in myItems"> 
     // each item will slide in, works fine 
     <div class="box wow slideInRight">
        <p style="color: black;">@{{ item }}<p>
     </div>
  </li>
</ul>

watch: {
   'myItems'() {
       if(this.myItems.length > 2) {

         // get the first item
         var div = document.getElementsByTagName('ul')[0].children[0].children[0];

         // Change class name, works
         div.className = 'box wow fadeOutLeft';

         **// how to trigger the new class ?** 

         // remove first item from the array 
         this.myItems.pop[this.myItems[0]];

    }
}
```

**Comment by eltonmesquita** [comment]
I think that stackoverflow on the vue.js tag is a better place for your question. This is not an issue and is not directly related to animate.css. You'll get better and faster answer there.

I'll close this as it's unrelated to animate.css.
