### ISSUE TITLE
fadeInUp animation not working with chrome or mozilla

### ISSUE THREAD

**Issue by jeankhouri** [daneden/animate.css#690]
I have some fadeInUp animations on my site with the viewport checker so that the animations start as I scroll down. It works on Safari on mac, safari on iOS, chrome on iOS but not on android, chrome desktop or mozilla. I included the script as a CDN. 

I don't understand why this would happen since chrome supports -webkit-transform

**Comment by eltonmesquita** [comment]
Can you share a link, or post your code on codepen? It's really hard to help with no live code.

**Comment by jeankhouri** [comment]
http://edgeto.ca

**Comment by eltonmesquita** [comment]
This is not an issue with animate.css. Just try and add `animation-iteration-count: infinite;` to the elements and you'll see that the animations work. This is most likely a problem with viewport checker, which I can't help much as I've never used it. Recheck your code and see if everything is ok, and if not solved, try to get some help from the viewport checker comunity.

My honest suggestion is to use [AOS](https://github.com/michalsnik/aos) instead as it's small, fast, [well documented](https://css-tricks.com/aos-css-driven-scroll-animation-library/) and works perfectly fine with animate.css.

**Comment by jeankhouri** [comment]
Thank you for your help!! I will give it a try
