### ISSUE TITLE
is that possible do not override my own transform when i dynamically add an animate to my dom 

### ISSUE THREAD

**Issue by spademan** [daneden/animate.css#692]
is that possible do not override my own transform when i dynamically add an animate to my dom 
for example
my element has transform effect as below
```    
transform: translate(0px, 0px) rotate(0deg) rotateX(0deg) rotateY(0deg) scale(1);
```
when i add animate effect of animate.css

they will work together but not override

**Comment by eltonmesquita** [comment]
Nope, it's impossible because that's the way CSS works. A simple workaround is to add the element you're animating to a container (like a `div`) and add the animated classes to the container.
Like:
````HTML
<div class="animated fadeIn">
  <div class="my-transformed-element"></div>
</div>
````

**Comment by spademan** [comment]
thx, it work as u say

**Comment by eltonmesquita** [comment]
Closing this as it's solved.
