### ISSUE TITLE
animate infinite and Mouse Wheel Scroll

### ISSUE THREAD

**Issue by daveygroup** [daneden/animate.css#696]
I just found something funny in my Bootstrap 3 Admin Dashboard template.
In one of the side menu items I have a animate infinite icon (heartbeat), and when infinite is added, page scrolling with the mouse wheel stop to work.

So scrolling with by dragging the scrollbar still works, but mouse wheel scroll stopped working.
Remove the keyword infinite, and mouse wheel behavior back to how it should work.

`<i class="fa fa-heartbeat fa-fw animated infinite pulse"></i>`  (mouse wheel scrolling gone)
`<i class="fa fa-heartbeat fa-fw animated pulse"></i>`(mouse wheel scrolling normal)

**Comment by eltonmesquita** [comment]
This is probably this most weird bug of all. It's probably an extreme edge case (like a mouse driver that doesn't work correctly when there's GPU use on a browser window or something random like that). If there's no detail about this, I'll close this issue soon.

**Comment by eltonmesquita** [comment]
Closing this as had no response. In case you've got more details, please feel free to reopen the issue.
