### ISSUE TITLE
how to animate just like animate.css written on your homepage?

### ISSUE THREAD

**Issue by yash2code** [daneden/animate.css#711]

**Comment by eltonmesquita** [comment]
Can you please elaborate more? If you just need the animations, please read the readme on the repo.

**Comment by yash2code** [comment]
@eltonmesquita  at this url : https://daneden.github.io/animate.css/  I can see 'Animate.CSS' changing its color dynamically .

**Comment by eltonmesquita** [comment]
https://github.com/daneden/animate.css/blob/gh-pages/style.css#L214

May I close this issue?
