### ISSUE TITLE
Pulse Effect not showing the button but effect is working

### ISSUE THREAD

**Issue by corpuzorgen** [daneden/animate.css#715]
As seen here 
http://landing.socialgarden.com.au/animate-buttons/

In the middle of flash and rubber band effect is the pulse, you can see pulse effect  is working but the button is hidden. Hover and inspect on it. 

BTW, I used animateCss function created on the doc and use jquery to animate them.

**Comment by MaineCannabisKid** [comment]
Where is your code? Can you give an example please?

**Comment by eltonmesquita** [comment]
Closing this as there was no response from @corpuzorgen. Feel free to open it again in case you need help.
