### ISSUE TITLE
Animate.css not displaying demo of other effects

### ISSUE THREAD

**Issue by chaitalipatil** [daneden/animate.css#719]
When I select demo effect and click on animate button, it only shows the bounce effect.
url becomes https://daneden.github.io/animate.css/?

Is there any bug?

**Comment by eltonmesquita** [comment]
The page seems to be working fine. Tried with several browsers and can't reproduce it.
Can you give more details about the issue?

**Comment by chaitalipatil** [comment]
Steps to reproduce:
1. Go to https://daneden.github.io/animate.css
2. Select any animation , I selected 'swing'
3. Click on 'Animate it' button.
4. It displays animation for 'bounce'. 
5. Then I select 'wobble' effect. 
6. It again showing animation for 'bounce'.

For any selected animation it is displaying 'bounce' animation only.

**Comment by eltonmesquita** [comment]
Before anything, could you please clear your browser's cache, open the page in a anonymous page and see if it works?
In case this doesn't solve the issue, could you please share your OS, browser version and browser's extensions you're using?

**Comment by chaitalipatil** [comment]
Closing the issue as it is working on other devices.
