### ISSUE TITLE
Sass, Less or other preprocessor

### ISSUE THREAD

**Issue by AndresOchoaS** [daneden/animate.css#724]
Some developers have projects in **Sass**, **Less** or some other preprocessor. Is there any version of **animate.css** in these mentioned?

**Comment by eltonmesquita** [comment]
Yeah, there's a early WIP branch written in Sass which still need some thoughts and a lot of attention. See #277. Let's keep all the conversation about it there, ok?

**Comment by AndresOchoaS** [comment]
Ok.
