### ISSUE TITLE
Animate. CSS and JQUERY

### ISSUE THREAD

**Issue by Kelvinskin** [daneden/animate.css#725]
I used older version of animate.CSS and hover effect in JQUERY works but when I updated animate.CSS the hover effect doesn't work

$("text").hover(function() {
   $(this).addClass("animated wobble");
 }); 

but it doesn't work at all

**Comment by Kelvinskin** [comment]
$('#test').hover()*

**Comment by makshh** [comment]
Probably you have some JS errors.

https://codepen.io/makshh/pen/brgPae

**Comment by asmaulhq** [comment]
Use **mouseover** and **mouseout** both event to work this effect each time you hover. 

**DEMO:** http://demo.asmaulhq.com/hovereffect/

**Sample JS CODE:** 
$(document).ready(function(){
    $(".text").on('mouseover', function(){
        $(this).addClass('animated wobble'); 
		console.log('mouseover');
    });
	$(".text").on('mouseout', function(){
        $(this).removeClass('animated wobble');
		console.log('mouseout');
    });
});

**Comment by joshi-mehul** [comment]
@Kelvinskin can you provide fiddle?

**Comment by Kelvinskin** [comment]
I confirmed it working, however when I added it to my bootstrap 4 project I had little issues with it, I don't know maybe theres a style/js from bootstrap conflicting with it

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
