### ISSUE TITLE
Adding/removing class is not fast enought to animate.css why?

### ISSUE THREAD

**Issue by batata004** [daneden/animate.css#730]
I use animate.css in most of my websites cause it's freaking awesome but frequently I got stuck with a problem.

Please see this link -> http://quemfazsite.com.br/temp/teste8.php

I have an element already with the class "flipInX" when page loads. Ok, if you click the first button (top of the page) I simply remove this class and add it again. BUT NO ANIMATION HAPPENS! I use this:

`$('#xxx').removeClass('flipInX').addClass('flipInX');`

BUT if I use the second button (code below) the animation happens:

```
$('#xxx').removeClass('flipInX');
window.setTimeout(function(){$('#xxx').addClass('flipInX')},100);
```

Is there some bug with animate.css? I mean, it looks like the chaining in jquery is very good, they first remove the class and then it adds. Why animate.css is not doing what is supposed?

EDIT:

The code below does not work too, so dont need to waste your time using delay cause unfortunatelly it wont work :(

`$('#xxx').removeClass('flipInX').delay(1000).addClass('flipInX');`

**Comment by eltonmesquita** [comment]
Not a bug, it's just the browser's optimization kicking in. So yes, you do need a timeout for this to work or maybe (can't confirm right now) `requestAnimationFrame` can solve your problem.

**Comment by batata004** [comment]
:( bad news! In this case using .animate of jquery is way better cause I can chain it and it will respect all the chaining order! Do you know any other hack without having to use setTimeout? Is it possible to chain a timeout with jquery? Something like:

removeClass(bla).setTimeout(1000).addClass(ble)

Is it possible?

Also I have one other question: sometimes when I add some classes to the same element it animates sometimes if there are some classes it does not animate.

For example: if I have an element and add class A to it, it will animate, great! If I add class B (without removing A) it may or may not animate depending on the class that I adde before.. Why?

**Comment by eltonmesquita** [comment]
Did you try the `requestAnimationFrame` API? Did it work? I'm with a really short time to try this out.  I advise using Stackoverflow and see if someone can help you there as it's not really related to animate.css.

About the second question, just make sure you're adding both classes needed as explained in the readme and that they're not getting overwritten by any other selector.
