### ISSUE TITLE
Mouseenter mouseleave not working with animate.css

### ISSUE THREAD

**Issue by batata004** [daneden/animate.css#731]
Hi,

hOVER your mouse in the middle link at the top "links" of https://www.frasesparavida.com.br and when you move your mouse down to access the sublinks the mouseleave fires wrongly even with the mouse still over the element. Why?

**Comment by makshh** [comment]
That's because you have `margin` under the "Links" and then submenu. So when you hover over "Links" `mouseenter` event start, then if you go down with your mouse `mouseleave` event start because of that margin, and then again `mouseenter`.

**Comment by batata004** [comment]
My dear friend @makshh  I dont have any margin-bottom that could cause this problem. See the print:

![image](https://user-images.githubusercontent.com/8988923/29495705-e8997fe0-859a-11e7-99b3-a5592261b645.png)

This problem only happens with animate.css cause if you see the submenu does not close when the mouse goes from the menu to the submenu. Only the animte effect fires wronly.

**Comment by batata004** [comment]
There is indeed some very strange problem, the submenu has a margin top and that causes the mouseleave event to fire BUT the margin-top is inside the .item element! I have no idea why the even fires.

**Comment by makshh** [comment]
But you have a `margin-top` in submenu.

**Comment by makshh** [comment]
It's inside but it doesn't matter. If you have for example a div `200x200px` and `margin` 100px and you attach mouse event, it will fire only when you hover over a div (not margin).
