### ISSUE TITLE
Serious bug with animate.css

### ISSUE THREAD

**Issue by batata004** [daneden/animate.css#732]
Hi,

I realized today, after 2 hours of wasted time, that animate.css has a serious bug regarding animation speed. In many documentations online is taught how to change animate.css speed. This method works perfetcly with ALL ANIMATIONS provided by animate.css excetp the ones that start with "bounce*" like "bounceIn".

Very very simple test case where you can see the bug:

https://www.quemfazsite.com.br/temp/teste-bug-animate.php

There is a class "animated-lento" that makes the transition to last 10 seconds.  So to test the bug do this:

1) open the link above;

2) click the first button to add class fadeinup. The animation will take 10 seconds, that's expected and is alright;

3) click the second button to remove the fadeinup class;

4) now click the third button to add the bouncein class. Now you will see that the effect will transition very very fast, it will not respect the 10 seconds interval.

This bug DOES NOT HAPPEN with any other effect, it will only happen with BOUNCE* effects.

I really need to use this bounceIn effect with a slow transition, is there any chance of a bug fix shortly?

Thanks in advance, this is a great library and saved looots of line of codes.

**Comment by makshh** [comment]
This is not a bug.

```css
.animated-lento
```

This is your CSS selector and its specificity is to small to override `animated.bounceIn`. You have to use more specific selector.

**Comment by batata004** [comment]
Sorry but I really didnt understand. Anyway I think this should be treated as a bug cause any other effect works perfectly, this bug only happens with bounce* effects!

Also I didnt understand what you said about "specific selector". If you dont have time to explain could you point me to a link/external source so I can understand it better?

**Comment by makshh** [comment]
Change `.animated-lento` to for example `.animated.animated-lento` and put it AFTER `animate.css` code. Or you can use `!important rule`.

```css
.animated-lento {
  -webkit-animation-duration: 10s !important;
               -animation-duration: 10s !important;
}
```

You can read more about this here: [Link](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**Comment by batata004** [comment]
WOWO!!!! THAT WORKED MY FRIEND!!!! I like much more using the !important and it worked perfectly! I was using animate.css in this https://www.sitepor500.com.br and you can see that there is a smartphone at the middle of the page that was never respecting the effect bounceIn with the duration that I wanted. EVERY OTHER effect was working fine just BOUNCEIN was not. So I thought I was doing something stupid, I did many changes to my code and I couldnt still solve the problem. 

So after you teach me how to fix it the animation is perfectly timed! I am very happy now:

![image](https://user-images.githubusercontent.com/8988923/29621095-1dc4b056-87f6-11e7-9a5e-6008ac02347b.png)

I really thank you for your attention my friend, after I spent many hours into this you saved me lots of hours that I would still spend trying to debug this problem.
