### ISSUE TITLE
every class runs twice 

### ISSUE THREAD

**Issue by OGhawsi** [daneden/animate.css#734]
I am using Laravel and Bulma I have included the CDN for Animated.css 
The problem is, if I use zoomIn for a div it zooms in twice on reload. Any Idea. Thanks in advance.

**Comment by eltonmesquita** [comment]
It's hard to help with no example. My guess is that you have `animation-iteration-count` on your element or just a small typo.
If you didn't get to solve your problem, please post a [pen](http://codepen.io) or something like that so anyone can try to help you.

**Comment by OGhawsi** [comment]
Thanks @eltonmesquita I found the problem it was with reload of the page


`  -vendor-animation-delay: 2s;
`

**Comment by alaksandarjesus** [comment]
I am facing the same issue with Laravel 5.8 and Bootstrap 4....I use bounceIn...

`
@if(session()->has('error'))
<div class="web alert alert-danger alert-dismissible animated bounceIn">
    <div><strong  class="mr-2">Error!!</strong><span class="message">{{__('messages.'.session()->get('error'))}}</span></div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif
`

**Comment by alaksandarjesus** [comment]
I am facing the same issue with Laravel 5.8 / Bootstrap 4

**view.blade.php**


@if(session()->has('error'))
div class="web alert alert-danger alert-dismissible animated bounceIn">
    div><strong  class="mr-2">Error!!</strong><span class="message">{{__('messages.'.session()->get('error'))}}</span> /div>
    button type="button" class="close" data-dismiss="alert" aria-label="Close">
    span aria-hidden="true">&times; /span>
  </button>
</div>
@endif



Note: I need to remove < from my html code, else that line is not showing up.
