### ISSUE TITLE
Scroll Direction Up / Scroll back down

### ISSUE THREAD

**Issue by Deelite310** [daneden/animate.css#738]
How do I code it so that the animation replays when I scroll up? And then replays the animation if I scroll back down

Basically

1) scroll down, animate element to appear. Scrolls down past element, executes fade out animation

2) once reach bottom, scroll up, executes animation to appear, continue pass that section, executes fade out animation

My code below:

```
$(document).ready(function(){
 
  // hide our element on page load
  $(".element").css("opacity", 0);
 	$(".element").waypoint(function(direction) {
                  if (direction ==='down') {
            			$(".element").addClass('fadeIn');
	        }
                else {
            			$(".element").addClass('fadeOut');
                }
}, { offset: "50%" });
});
```

**Comment by eltonmesquita** [comment]
You should seek support for the scrolling animation library you're using. Animate.css only deals with the CSS part of this, not the Javascript. If you need an indication, [AOS](https://github.com/michalsnik/aos) usually is a good fit for this kind of behavior.
