### ISSUE TITLE
Animations using x-axis on Chrome Android

### ISSUE THREAD

**Issue by pierreburton91** [daneden/animate.css#741]
While integrating animate.css in my project, I noticed that animations using x-axis (i.e. fadingInLeft, fadingOutRight, etc.) cause a wierd behavior on Chrome for Android.

After triggering the animation, the browser acts as if the viewport was suddenly twice wider (exactly twice). Understand, horizontal scroll suddenly appears and never leave.
The strangest thing is this:
- The body, which is supposed to take 100% of the width, is not resized.
- Fixed elements (a navbar in my case) starts to behave oddly. The element is no longer fixed at his supposed point. It behaves the same as the address bar of the android browser.

This is the normal state of the page with the top nav being fixed :
![okay](https://user-images.githubusercontent.com/16057997/30644485-cf333b46-9e12-11e7-8e10-518dccb98c98.PNG)

This is the wide blank space it creates after the animations :
![notokay](https://user-images.githubusercontent.com/16057997/30644523-eb6495a8-9e12-11e7-8927-dcd5695a6288.PNG)

And this is the wierd scrolling behavior which hides the fixed element (aka the navbar) :
![wherefixed](https://user-images.githubusercontent.com/16057997/30644571-0de9acd0-9e13-11e7-8fc3-53fd24edaacd.PNG)

The bug appeared on my actual phone but also on chrome for desktop **using the responsive developper tool**. I precise it is with the actual tool activated, the bug does not show up if the browser window is resized. No problem on Firefox nor IE.

I believe this is more of a Chrome related issue, yet I thought you should know.

**Comment by eltonmesquita** [comment]
This is not an issue. What happens is that the element overflows the width of your viewport. It's how CSS works. The easy fix is to set `overflow-x: hidden` on the body. I would recommend to set it in a wrapper element that holds the animated element, as you'll be safer and won't risk brake something else in the process.

**Comment by pierreburton91** [comment]
Forgot to mention that body is already in `overflow-x: hidden`. (I know how css works)
The animated elements also take place in a container div with `overflow: hidden`.

What about now ?

**Comment by eltonmesquita** [comment]
Did you set a width or a max-width on the body/wrapper? Did you apply a transform on the element? Anyway, a live link would be really better to try to help.

Ps: this is the kind of issue that pops often and most of the users didn't know how CSS works... So don't take this bad 😉

**Comment by pierreburton91** [comment]
I cannot reproduce the bug since then.
Maybe that was caused from something else.
