### ISSUE TITLE
Animate.css has stopped working in Chrome

### ISSUE THREAD

**Issue by khantasha** [daneden/animate.css#742]
Hi, I have a project where I used animate css. I have done nothing to change the css/html, but all of a sudden animate.css will not work for me on these pages in Google Chrome. Still works in Safari and Firefox. I'm using Version 61.0.3163.100 (Official Build) (64-bit). Have you heard of this issue happening and can you help? Thank you.

**Comment by eltonmesquita** [comment]
Hello. I've got the same Chrome build on my Mac and everything works fine at the demo page. Probably is something like an unclosed tag on your code that broke with the update. Could you please share a link so we can help you?

**Comment by khantasha** [comment]
http://projects.publicsource.org/chartereffect/stories/higher-turnover-less-experience-in-county-charter-schools-how-they-compare-to-the-districts-and-what-it-means-for-students.html

**Comment by eltonmesquita** [comment]
Sorry, but I'm pretty sure this is a problem with the animate on scroll library you're using. I don't know which one you're using, but you should seek support for it as this is not related to animate.css.

**Comment by AMAdacto** [comment]
We have the same problem with the same version of Chrome on Mac

Chrome: 61.0.3163.100
MacOS: 10.11.6 (formerly know as El Capitan)

We managed to fix this issue by replacing the "animation-name" css key with "animation" 

![animate css](https://user-images.githubusercontent.com/5756260/31217964-0754f3e6-a9b9-11e7-8649-247e611cdec8.jpg)

**Comment by smachara** [comment]
Did someone find a solution?

**Comment by khantasha** [comment]
EltonMesquita was right in terms of my issue. It was a different scrolling library I was using that was breaking, not animate.css.

**Comment by rodrigo1990** [comment]
Hi ! Something very strange is happened to me, animate css is not working in my chrome, and in my firefox. Not even in the official repositorie of animate css the animations works.

Someone understand what's can be?

**Comment by eltonmesquita** [comment]
https://github.com/daneden/animate.css/blob/master/README.md#accessibility
Just review your OS animations configurations.
