### ISSUE TITLE
JavaScript library

### ISSUE THREAD

**Issue by manix** [daneden/animate.css#747]
I have been using animate.css for quite a while and detecting animation end events was always a problem for me because the events are not currently well supported across browsers and I don't use jQuery so I wrote myself a small library that utilizes setTimeout to trigger animation end events.

I thought it might be useful for other people as well but will be pretty hard to find so I'm dropping you this message in case you agree with me.

You can find it on [github](https://github.com/manix/css-animate) and [npm](https://npmjs.org/css-animate).

**Comment by foxnoodles** [comment]
Adding an option to detect the element.scroll would be nice.. so you could run an animation when user scrolls to the element.
Great job anyway

**Comment by mansui** [comment]
very good

**Comment by eltonmesquita** [comment]
Congrats for the job @manix ! 
I still want to keep animate.css simple and any third party library has a long way to be recommended  in the readme itself.
Thanks for the suggestion!
