### ISSUE TITLE
ZoomOut with FlexBox (Bootstrap 4) not working on Edge/IE

### ISSUE THREAD

**Issue by hardcodet** [daneden/animate.css#748]
FYI: I have  a simple card UI built upon Bootstrap 4. While `zoomIn `works just fine, `zoomOut` isn't working properly on Edge and IE - it's more of a fadeOut since no scaling occurs.

Repro:
* Go to http://www.taxi.link/jedi-rides
* click on the star-rating to initiate a `zoomOut`, followed by a `zoomIn`

Validated to be working on
* FF/Chrome
* Android Chrome
* iOS Safari

**Comment by eltonmesquita** [comment]
This looks a lot with a browser bug. Can you provide a isolated case for this? It will be easier to debug and maybe find a solution.

**Comment by eltonmesquita** [comment]
Closing this as it's stale and everything works fine on demo page and other pages. Feel free to reopen the issue if you've got news on this or a reduced case.
