### ISSUE TITLE
BounceInDown

### ISSUE THREAD

**Issue by erperejildo** [daneden/animate.css#750]
I'm trying to do an animation of a ball bouncing. The most similar animation I found was `BounceInDown` but the bounce is not like a real bounce. I tried also `Bounce` but this displays the ball first and does the animation after.

Is there any other solution?

**Comment by eltonmesquita** [comment]
If you need an accurate animation, you'll probably need a Javascript library. Animate.css has general animations. Try Bounce.js, Anime.js or Greensock.

**Comment by erperejildo** [comment]
I know them but I was wondering if it would be possible to add new animations at some point.
More a question than a issue itself

**Comment by eltonmesquita** [comment]
I think (bounce.js)[http://bouncejs.com/] might be a good option for you as it generates css keyframes.
