### ISSUE TITLE
fadeIn effects are jumping on mobile

### ISSUE THREAD

**Issue by thelefty** [daneden/animate.css#752]
on mobile all the fadeIn effects jump at the last second. all other effects are smooth as butter but the fadeIn on mobile is just choppy. any idea how i can fix this? thank you!!

![fadeinright](https://user-images.githubusercontent.com/6673900/31899407-b6d99808-b7d8-11e7-9dd5-e30951df4ee7.gif)

**Comment by eltonmesquita** [comment]
This is a perfomance problem. Probably there's something happening in your page at the same time of this animation. A script or other animation running concurrently.

**Comment by WarenGonzaga** [comment]
What is your framework to do that? Is it ionic?

**Comment by eltonmesquita** [comment]
Closing as it's stale.

**Comment by flacial** [comment]
I encountered a similar issue with the `CSSTransition` method from `react-transition-group`. The animation duration of the method was set to 2 seconds, while the default duration in the `animate.css` library is 5 seconds. As a result, the method ends the animation before the `animate.css` class animation is complete.

Although this may not be relevant to the problem you're currently experiencing, future visitors should consider checking for any mismatch in the animation duration between the methods (if you're using a component that manages them).
