### ISSUE TITLE
some conflict In bootstrapTable  

### ISSUE THREAD

**Issue by XLJ-CN** [daneden/animate.css#753]
====中文描述====
我在body中引用了动画 animated fadeInRight  这会导致一些元素位置和显示的有所偏差
代码如下
```
<body class="  animated fadeInDown  container-fluid row" >
    <div class="col-lg-6">

        <table id="data_mst" style="margin-left:5px;"></table>
     
   <div class="col-lg-6 row">
        //others
        </div>
    </div>
</body>
```
其中这个table  是bootstrap table  在FF选中元素 其实际的位置和显示所在的位置大约有4px的偏差
经过我的排查 是因为body 应用了动画导致

============English Description=============
in my project I  using the "animated fadeInRight " to “body”  it makes some position deviation
the  html code is
```
<body class="  animated fadeInDown  container-fluid row" >
    <div class="col-lg-6">

        <table id="data_mst" style="margin-left:5px;"></table>
     
   <div class="col-lg-6 row">
        //others
        </div>
    </div>
</body>
```
the table is bootstrapTable     In Firefox  I  choose the Element  i  find there are  some position deviation about 4px Between the border of i choose and the actual position(you can see that element)      when i don`t using "animated fadeInRight"  it works again

**Comment by lopo1983** [comment]
U can set position

**Comment by eltonmesquita** [comment]
Never animate the body tag, you're asking for problems! Put everything inside a tag `main` or div and animate it. Also make sure your element is not an inline element and if possible set a position to it.
