### ISSUE TITLE
Image displayed completely before the animation

### ISSUE THREAD

**Issue by elsondinardo** [daneden/animate.css#754]
My theme uses animate.css in some elements. When I was trying to add fadeIn to an image, it is being displayed completely before the animation, which should be the reverse. How do I display the image only after the animation?

**Comment by H5DevHoward** [comment]
same question

**Comment by eltonmesquita** [comment]
Use `animation-fill-mode` for this. Read more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode).
