### ISSUE TITLE
SlideInLeft not working in Opera

### ISSUE THREAD

**Issue by codecobber** [daneden/animate.css#756]
Am experiencing issues with Opera. The slideInLeft effect doesn't work.

Any ideas would be appreciated.

Opera version info:
Version 12.16 
Build 1860 
Platform Linux 
System x86_64, 4.11.12-200.fc25.x86_64

**Comment by eltonmesquita** [comment]
Sorry, but Opera 12 is considerably outdated. Its global use must be something close 0%, there's no need to support it! I can't even remember if it supports 3d transforms which are used by animate.css.

If you're using it I strongly recommend to uninstall it as it must have some serious security problems by now.

**Comment by codecobber** [comment]
Cheers, I don't use Opera. Must have been a really old version on my machine.

Thanks for the reply
