### ISSUE TITLE
Kill Bower support for V4+

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#758]
Currently Bower is being maintained but as [this announcement](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) notes it's not recommended to be used anymore. The recommendation is to use Yarn that uses the npm registry which is supported by animate.css.

Honestly, I'ver never used Bower for real and makes no sense learn it now, so I don't want to waste any effort supporting a deprecated tool. Of course, warnings and instructions would be provided.

The request is to remove the support for the new, Sass powered version only (see #277). The next minor release (v3.6.0) that will luckily see the light of the day still this year would still support it.

I need to hear people voice about this. @daneden I would love to hear your opinion about this.

Please give your opinions and arguments in favor or against it - politely :D.

**Comment by DaSchTour** [comment]
I guess removing bower.json is more work than just letting it were it is. I guess by creating this issue I already wasted more effort than in still supporting it.

**Comment by jabranr** [comment]
@eltonmesquita Just stopping by to help. If this is something we are looking forward to then I can pick this one up. Let me know.

**Comment by daneden** [comment]
Let's do it! To be perfectly honest, I'm pretty out of touch with how people would _like_ to start using Animate.css. Bower support was added by request some time ago, but happy for us to remove it.

**Comment by WarenGonzaga** [comment]
@eltonmesquita we have the GO signal now... thanks @daneden for the awesome response... currently I am adding a new feature for the animate.css will submit PR later.

**Comment by eltonmesquita** [comment]
It's on the dev branch now.
