### ISSUE TITLE
Add prefixes to compiled files

### ISSUE THREAD

**Issue by cristoferfb** [daneden/animate.css#768]
I work with Phonegap and animate.css don't work in any device, for it I need to add manually the -webkit- label in the css, other frameworks like this use webkit too for the rendering.

**Comment by eltonmesquita** [comment]
That was a small mistake in Gulp's configuration and will be fixed in the next version.

**Comment by eltonmesquita** [comment]
Fixed in the latest commits. The next version will include the fix.
