### ISSUE TITLE
Divs dissapears while using animate.css

### ISSUE THREAD

**Issue by itggot-arvid-nilber** [daneden/animate.css#769]
Hi! 
I'm trying to use animate on my project, used it before on other projects, but this time it doesn't work, the divs just dissapears, and p h2 and a.

Demonstration:
https://imgur.com/a/LyTHw

Source code
https://codepen.io/avveawesome/pen/baGwvQ

**Comment by eltonmesquita** [comment]
Lots of things are broken on that pen. Can you please provide a working example so someone can help you  with the mentioned issue?

**Comment by itggot-arvid-nilber** [comment]
Its not broken, change the screen width on codepen

**Comment by eltonmesquita** [comment]
Sorry, but it's not animate.css fault. There's this css added to the `fadeInDown` class:
```
.fadeInDown {
    opacity: 0;
    -webkit-transform: translateY(-400px);
    transform: translateY(-400px);
}
```
That's causing the div to disappear and it's not from the animate.css source.
If you need more help, I advice to post something on Stackoverflow, as this is a issue tracker related only to animate.css development (bugs, improvemnts, etc).
Closing it as it's unrelated.
Merry Christmas, BTW! 🎄
