### ISSUE TITLE
.animated class clashes with bootstrap modal

### ISSUE THREAD

**Issue by Ignitis** [daneden/animate.css#770]
"animation-fill-mode: both" attribute clashes with the boostrap 3 modal popups.

It causes the class "modal-backdrop" to appear in front of all the others

![image](https://user-images.githubusercontent.com/4703687/33996307-b9b63d96-e0d8-11e7-9808-959aaf84c5e0.png)

If you remove the css attribute, it causes the content to flicker once before loading.

n.b. I am using animate.css along with wow js. 

Any solutions?

**Comment by eltonmesquita** [comment]
Could you please share a reduced case on codepen showing the issue? It's really hard to debug anything from a screenshot.

**Comment by eltonmesquita** [comment]
Closing this as it's stale. Feel free to reopen it when you've got a reduced case.

**Comment by vndevil** [comment]
Animate.css conflict with Bootsrap Modal because it have class `animated fadeIn` in the parent `div`.
To fix this issue, you need to remove class `fadeIn` on event `show.bs.modal` and put it back on event `hidden.bs.modal`.

Here is demo fix your issue: https://codepen.io/vndevil/pen/KBZOzb
