### ISSUE TITLE
Configuring effect

### ISSUE THREAD

**Issue by rapperfitness** [daneden/animate.css#774]
Hi, I'm a beginner programmer and I'd appreciate any feedback please.

How can I make the fadeInUp effect slower? I'm trying to make it delay a little. I looked at the code in animate.css, am I supposed to edit the parameters for translate3d?

Thanks for making such a cool library.

**Comment by eltonmesquita** [comment]
You don't need to touch any code from animate.css. Just override the element's `animation-duration` with the value you need on your own CSS.
Eg.:
```
.my-animated-element {
  animation-duration: 4s;
}
```
Just make sure your code comes after animate.css code.

**Comment by rapperfitness** [comment]
Thank you @eltonmesquita  !!
