### ISSUE TITLE
Animations cause Scrollingbars

### ISSUE THREAD

**Issue by ThaumicTom** [daneden/animate.css#776]
Animations, for example, bounceInLeft, create a scrollingbar at the bottom for a short time. After Animations finished, it works fine again. This bug is minor, but would be nice if fixed.

**Comment by eltonmesquita** [comment]
Not a bug, just a expected side effect to moving elements on the screen. Just add the element to a parent element (a container) and add `overflow: hidden` to the parent.
This should always be handled by the developer using the library.
