### ISSUE TITLE
Animate text seems to stop video from playing in carousel

### ISSUE THREAD

**Issue by swbates** [daneden/animate.css#777]
Feel free to close if this isn't really an issue with animate. I have several background videos playing in a carousel, with text overlay that's animated for each slide. The first one works fine, but if i advance to the next one, for some reason the videos don't play. If I remove all the animate CSS hooks and the stylesheet link from the page, the videos work fine. 

URL: https://versoblackbox.github.io/

**Comment by eltonmesquita** [comment]
I don't think this is a problem with animate. I think there are some restriction when playing videos on browsers and sometimes the video can get paused when it's not on the viewport (I might be wrong, though. better research this further).
Anyway a simple fix is to force playing the video when the slide is active (but first, your videos have duplicated ID's, they should be unique).
Just add a listener to the slide event (see the slider documentation) and set the video element to play. Something like this:
```js
slider.addEventListenr('slider.onslide', () => {
  const video = document.getElementByI('bgvid')
  video.play()
})
```

Again, consult the slider documentation and adapt the code to it.
