### ISSUE TITLE
Animate.CSS should not repeat the animation every time on scrolling, Instead it should happen only once on the very first scroll

### ISSUE THREAD

**Issue by nasweefpn** [daneden/animate.css#778]
Hi There,

The animation happens every time when i scroll. Is it possible to happen only once?
Demo -
http://dev.ktimes.co/was20378/scroll/index-scroll.html

**Comment by eltonmesquita** [comment]
Sorry, but this isn't an issue with animate.css as it just provides the animations, not the animate on scroll feature. Please refer to the library's documentation you're using and see if there's an option to animation only once.

Closing this as it's unrelated.

**Comment by evertramos** [comment]
@nasweefpn,

How did you do it? This is what we were looking for...

https://github.com/daneden/animate.css/issues/785

https://github.com/daneden/animate.css/issues/787
