### ISSUE TITLE
Content is blurry after bounceIn effect

### ISSUE THREAD

**Issue by fredekiel** [daneden/animate.css#780]
I have a modal, that's using the bounceIn effect, and once it finishes the content is all blurry. After I move the cursor, 1 pixel it goes back to normal.. I find it to be really noticeable, what's the cause of this?

[Screenshots](https://imgur.com/a/ZKX01)
Bottom image(Blurry) is before I moved the cursor

**Comment by eltonmesquita** [comment]
Webkit browsers used to have this problem when using transforms (that are used on animated) but they have improved the rendering some time ago.
You can try to play with the `text-rendering` property. Try some values like `geometricPrecision` and `optimizeLegibility`.
If the problem persist, please post a pen so we can try to debug and hopefully help you.

**Comment by fredekiel** [comment]
Nothing changed after I aadded the property :(

**Comment by eltonmesquita** [comment]
Can you please post a reduced case on codepen so we can try to help? It's really hard to debug something without live code.

**Comment by fredekiel** [comment]
After trying with a fresh bootstrap, I think this might be something related to the theme I'm using. I still have no idea what tho :S 

I don't have access to a webserver at the moment, but I uploaded as a zip with a small modal demo.

https://www.dropbox.com/s/vh2n9hym64ronhs/demoBlurry.zip?dl=0

**Comment by eltonmesquita** [comment]
Sorry, but I can't just download a random zip file on the internet, there are services out there to share live code, like [codepen](https://codepen.io/).

**Comment by fredekiel** [comment]
https://codepen.io/anon/pen/wyKRQQ Codepen doesn't show the problem for some reason.. 

I added pastebin if you want to create the files yourself?
https://pastebin.com/qhf2j3Q4 index.html
https://pastebin.com/HZqgw1YJ custom.css

**Comment by eltonmesquita** [comment]
What browser and version the issue happened?

**Comment by fredekiel** [comment]
Seems to just be with Google Chrome Version 64.0.3282.140 (64-bit)

**Comment by eltonmesquita** [comment]
I still can't reproduce the issue. Does it still persists on your end and newer chrome's version?

**Comment by eltonmesquita** [comment]
I'm closing this as it's stale. @fredekiel , feel free to reopen it if you have any news on your side.
