### ISSUE TITLE
How to execute css animation one at a time? Coz the page load it will execute all the css animation all at once.

### ISSUE THREAD

**Issue by eamancio** [daneden/animate.css#782]
I want the animation to be executed one after another.  How could I possibly do that?

**Comment by morehardy** [comment]
try setInterval()

**Comment by eltonmesquita** [comment]
You can add delays to the animations with the `animation-delay` property, although it's kinda hard to maintain.
If you need the animations to fire on scrolling, you'll need to use a js library like [AOS](https://github.com/michalsnik/aos).

I'm closing this as it's unrelated to the project itself, you can seek help on Stackoverflow or similar.
