### ISSUE TITLE
How to apply into Ionic

### ISSUE THREAD

**Issue by robertrobertlow** [daneden/animate.css#783]
Hi, I would love to apply this animation into my ionic project. How can I do so? Please guide me thank you very much and appreciated.

As I followed your instruction, I am having this error of  core.js:1350 ERROR Error: Uncaught (in promise): Failed to load animate.min.css

**Comment by eltonmesquita** [comment]
Sorry but this is not related to animate.css. Please read Ionic's documentation or seek for help on its forums or Stackoverflow as this should be pretty straightforwards as adding the css files and the classes on the elements.

Closing this as it's unrelated.
