### ISSUE TITLE
not working with Safari 11

### ISSUE THREAD

**Issue by crixcroxgithub** [daneden/animate.css#784]
Due to trouble with the "animation-play-state"-attribute in Safari 11, the project is not working  properly any longer (in Safari 11).

**Comment by eltonmesquita** [comment]
Sorry, but I don't understand the problem. I've tested on Safari 11 and everything's working. Can you please detail the problem, or better yet, post a reduced case on codepen with the problem?

**Comment by eltonmesquita** [comment]
Closing it as its stale and animate.CSS doors work on safari.

**Comment by windware** [comment]
@eltonmesquita
It doesn't work on Safari 12 (macOS 10.13.6, Safari 12.0.3, no extensions).

https://daneden.github.io/animate.css/
Initial sliding from the bottom works but none of the other animations work.
