### ISSUE TITLE
{CSS} transform: translate not working

### ISSUE THREAD

**Issue by larry020** [daneden/animate.css#792]
Hello,
when using your animations on elements which have been positioned absolutely 
`position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%,-50%); /* ERROR */`
in that case the transform property has no effect. Is there a fix or something else to consider?

Kind regards

**Comment by jmilanovic** [comment]
Create a code snippet on codepen and I'll review.

**Comment by eltonmesquita** [comment]
Animate.css uses transforms for animations that overrides your transform. Just add the element to a parent like a div and set the animation to this parent. Or anything like that...

**Comment by yeyuguo** [comment]
how do u fix this?
