### ISSUE TITLE
How to use animate.css with Webpack 3?

### ISSUE THREAD

**Issue by crs1138** [daneden/animate.css#793]
I'm trying to load animate.css to my app using following dependencies:
https://github.com/daneden/animate.css
https://github.com/andreimc/animate-css-webpack

I'd like to achieve that I'll be able to configure what animations will load using animate-css-web-pack.

Here's a list of all my dependencies in the project
```
  "dependencies": {
    "animate-css-webpack": "^3.5.6",
    "animate.css": "^3.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.38",
    "@babel/preset-env": "^7.0.0-beta.38",
    "babel-loader": "^8.0.0-beta.0",
    "css-loader": "^0.28.9",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "postcss": "^6.0.16",
    "postcss-loader": "^2.0.10",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "uglifyjs-webpack-plugin": "^1.1.6",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.1"
  },
```

Relevant part of my webpack.config.js
```
 entry: {
    'main': [
      'animate-css-webpack!./src/animate-css.config.js',
      './src/app.js',
    ]
  }, 
```
However animate.css won't load… What am I doing wrong?

**Comment by eltonmesquita** [comment]
Sorry but this isn't an official loader maintained by the animate.css author/collaborators. We can't help much around here... Please seek help on the loader's issue tracker or even turn to Stackoverflow, there'll be much more people able to help you.
Closing this.
