### ISSUE TITLE
The animation effect is not effective after the element is disabled

### ISSUE THREAD

**Issue by zetawoo** [daneden/animate.css#794]
The animation effect is not effective after the element is disabled(css   disabled:"").（IE 11/edge）

**Comment by eltonmesquita** [comment]
Sorry, but can you please explain it better? I couldn't understand the problem. If you can, please post a reduced case on codepen or similar service.

**Comment by eltonmesquita** [comment]
Closing it as it's stale. Feel free to reopen it if you've got any news about the issue.
