### ISSUE TITLE
Animations are not well shown on firefox

### ISSUE THREAD

**Issue by GentillePlume** [daneden/animate.css#795]
Hi everyone.

I don't know if my problem is an issue, but I need help for my website.
Animations are not well shown with Firefox ! You can compare my coming soon template with few browsers for see the problem : http://melvin-lemoine.me

Regards,

Gentille Plume

**Comment by eltonmesquita** [comment]
Hello!
Could you please be more specific? What animation is not happening? What Firefox version and OS the problem occurs? Can you post a reduced case?
