### ISSUE TITLE
How do i use them with Ionic 3

### ISSUE THREAD

**Issue by crazypigs** [daneden/animate.css#797]
I was trying to use these in an ionic app. I can get them to trigger on loading a screen but i want to trigger them when a method is called. I am using typescript and ionic 3

**Comment by WarenGonzaga** [comment]
Hello there, try to go here: https://blog.thecodecampus.de/angular-2-animate-css-tutorial-use-animate-css-ng2-application/

**Comment by eltonmesquita** [comment]
Closing this.
