### ISSUE TITLE
License under MIT or under the ☺ license (http://licence.visualidiot.com/)

### ISSUE THREAD

**Issue by CristinaCismas** [daneden/animate.css#798]
Hello,

Recently i found this **animate.css** file used in one of our company project. This file contains this kind of header : 
/*_Animate.css - http://daneden.me/animate
Licensed under the ☺ license (http://licence.visualidiot.com/)
Copyright (c) 2012 Dan Eden_*/

In order to be allowed to use this code in a commercial product I would like to know if you had 2012versions under a different license, like this one http://licence.visualidiot.com/?

Thank you !!

**Comment by Diogozx** [comment]
Hello,
Im a student i just used it to for curiosity. Im not usina for commercial use.

**Comment by eltonmesquita** [comment]
Hi @CristinaCismas.
Sorry, but I didn't understand what you ment. But as you [can see on the read me](https://github.com/daneden/animate.css/blob/master/README.md#license), the library is licensed under the MIT license which is open for commercial use.

**Comment by CristinaCismas** [comment]
Hi @eltonmesquita ,
As you can see in the copyright ( _Copyright (c) 2012 Dan Eden_)the year is 2012, so i'm searching an Animate.css version from this year to see if the license it is MIT or the one found in the  header (http://licence.visualidiot.com/) .
I also saw that the latest versions are under MIT. 
Thank you for your interest.

**Comment by eltonmesquita** [comment]
Can't you just upgrade for a newer version? You'll have to check, but I believe that it shouldn't have any breaking change.

**Comment by eltonmesquita** [comment]
Closing this as its solved.
