### ISSUE TITLE
[Question] How should I use Exit Animations

### ISSUE THREAD

**Issue by ThaumicTom** [daneden/animate.css#799]
Hi,
I have a qeustion about animations for animate.css. There are some Exit Animations, but they are pretty much useless. How should I or can I use them? I had the idea to exit out animations when going to a next page, but I have no JavaScript/JQuery skills to do that. Thanks.

**Comment by WarenGonzaga** [comment]
Hey there, then the best thing to do is to learn JS if you want to use those exit animation. They are not useless it depends on the user who know how to use them based on their experience in development. My suggestion learn JS and start learning how to use these exit animation.

**Comment by ThaumicTom** [comment]
So Exit Animations only can be used using JS? Can you give me one example?

**Comment by WarenGonzaga** [comment]
Yeah because all the animation is only working when the page loads. So if you want to trigger an exit animation you need a javascript for the user experience. I will provide a quick example later.

**Comment by eltonmesquita** [comment]
May I close this as it's kinda solved? @WarenGonzaga  and @ThaumicTom

**Comment by ThaumicTom** [comment]
An example is still missing as @WarenGonzaga wanted to give me one, but I think it's done.

**Comment by WarenGonzaga** [comment]
Oh, I forget to provide example sorry guys!
