### ISSUE TITLE
[Request] `rotateInBack` and `rotateOutBack`

### ISSUE THREAD

**Issue by genemars** [daneden/animate.css#800]
It would be nice to have `rotateIn` and `rotateOut` animation with opposite direction as well.
In my specific case I needed this for a floating action button menu open/close effect.
See https://genielabs.github.io/zkit/docs/components/menu_overlay.html

**Comment by WarenGonzaga** [comment]
Hello, can you provide as codepen.io of your suggestion?

**Comment by genemars** [comment]
I realized that for modern browsers it can be used `animate-direction: reverse;` for the purpose.
https://codepen.io/genielabs/pen/xWNyaw
thanks.

**Comment by WarenGonzaga** [comment]
Hello @genemars! Thank for your suggestion, we will review that and take a look if there is a possible conflict with other animations. If there's no conflict in your suggestion I will add it immediately to our library. :) Thanks!
