### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by Showcase-Joz** [daneden/animate.css#802]
cannont get to work and can only assume its the css grid (grid areas) i'm using.

have used extensively before. but no time to test :/

**Comment by WarenGonzaga** [comment]
Can you provide us an example of your issue? It is better to provide a codepen.io and reproduce the issue. Thanks! @eltonmesquita

**Comment by eltonmesquita** [comment]
Well, it works on Chrome as you can see on https://codepen.io/eltonmesquita/pen/wjVQZK .
I'll have to investigate it more but if @Showcase-Joz could provide more info about the issue, it'd make easy to solve the issue.

**Comment by eltonmesquita** [comment]
I'm closing this as there's no info and no more report about this or any issue related to grid and animate.css. @Showcase-Joz , if you have any info about it, feel free to re-open the issue.
