### ISSUE TITLE
Animation point of origin

### ISSUE THREAD

**Issue by chrisb-pa** [daneden/animate.css#803]
I'm attempting to use slideInRight for a search bar on the right side of the page. The plan is to have the text-input field slide out from the search button upon hover.

Is it possible to anchor the animation to start from the search button rather than the right edge of the screen?

**Comment by cklab** [comment]
https://github.com/daneden/animate.css/issues/415

**Comment by chrisb-pa** [comment]
Thanks, didn't see that one.
