### ISSUE TITLE
Flip animation bug in Firefox 59.0.2

### ISSUE THREAD

**Issue by kottenator** [daneden/animate.css#805]
Hi!

Thanks for such an awesome library!

But I have a bug (or glitch) with `flip` animation in Firefox 59.0.2 on macOS 10.13.4:

![error-demo](https://user-images.githubusercontent.com/371674/38461877-a892cdb0-3aa9-11e8-8f97-fe862c8b8bf9.gif)

**Comment by WarenGonzaga** [comment]
Thanks for the awesome feedback... @eltonmesquita will help you regarding your issue.

**Comment by kottenator** [comment]
Great! Looking forward to it!

**Comment by WarenGonzaga** [comment]
sure, all contributors are busy right now even dan eden...

**Comment by gianjohansen** [comment]
@kottenator @WarenGonzaga This one was bugging me so I submitted a PR.

**Comment by WarenGonzaga** [comment]
@gianjohansen can you please tag me ? so I can look to it?

**Comment by daneden** [comment]
This should be fixed now with the merge of #825, closing optimistically.
