### ISSUE TITLE
Absolute position?

### ISSUE THREAD

**Issue by jsachs99** [daneden/animate.css#807]
I love this system, but need to make it work with absolute positioning... any ideas?

**Comment by WarenGonzaga** [comment]
what are you trying to do?

**Comment by eltonmesquita** [comment]
Closing this as it's stale.

**Comment by vijayantkatyal** [comment]
@jsachs99 

wrap the element inside another element (and apply animation to outside element)

https://github.com/animate-css/animate.css/issues/924#issuecomment-492453666
