### ISSUE TITLE
Mobile Animation was bad

### ISSUE THREAD

**Issue by Heysoulnat** [daneden/animate.css#808]
So this behavior is only for all the right animate, because when I'm testing the animation left (fadeleft,bounceleft etc.) it's working properly.  So the issue is when you scroll down and the animation trigger it become like the picture. The screen spiting into two.

![screenshot_2018-04-11-16-18-59](https://user-images.githubusercontent.com/38278661/38654178-98a80d08-3e40-11e8-8dd7-9f03dcfba0ba.jpg)

**Comment by eltonmesquita** [comment]
This probably a misuse of the library. I'll close this as it's stale.
