### ISSUE TITLE
Demo page does not work anymore because of jQuery

### ISSUE THREAD

**Issue by AndreaBoeAbrahamsen** [daneden/animate.css#810]
![image](https://user-images.githubusercontent.com/9437230/38850572-57fe2e2e-4212-11e8-9b6a-6a9a6b384ab5.png)

Maybe use cdnjs instead: https://cdnjs.com/libraries/jquery/1.10.2

**Comment by ejachang** [comment]
What browser are you using? I'm using Chrome and this is what I see. The version I'm using is Version 65.0.3325.181 (Official Build) (64-bit)
<img width="1278" alt="screen shot 2018-04-17 at 1 14 11 am" src="https://user-images.githubusercontent.com/32560445/38856923-b6210a48-41dc-11e8-9285-eca79d968ed8.png">

**Comment by eltonmesquita** [comment]
As reported it's working just fine. That was probably a connection error. Thanks for reporting.
Closing this.
