### ISSUE TITLE
Flip animation bug in Edge 16

### ISSUE THREAD

**Issue by Mendels0n** [daneden/animate.css#811]
Hi!
But I have a bug with flip animation in Edge 16 on Windows 10 :

![flip-in-edge](https://user-images.githubusercontent.com/23106697/38872283-8b7f5dc4-425b-11e8-86ee-3912692a77a6.gif)

**Comment by eltonmesquita** [comment]
I'm investigating this but it is a nasty Edge's transform engine bug that seems to be inherited from IE11. I still don't have the solution but I hope to get there 😅.

**Comment by WarenGonzaga** [comment]
@eltonmesquita awesome effort .... I might report this to edge team about this one...
