### ISSUE TITLE
Suggestion: Add animation speed class

### ISSUE THREAD

**Issue by saidbakr** [daneden/animate.css#813]
I suggest to add `.slower` and `.slow`  where `animation-duration` will be 2s and 3s respectively for each one.

**Comment by thealanbeam** [comment]
It's clunky, but this can be achieved by giving your element to be animated an ID and alter the duration with CSS. I can't get to work with a class, it seems to work only with ID.

#animate-quick {
  -moz-animation-duration: .5s;
  -webkit-animation-duration: .5s;
  -vendor-animation-duration: .5s;
}
#animate-slow {
  -moz-animation-duration: 2s;
  -webkit-animation-duration: 2s;
  -vendor-animation-duration: 2s;
}
#animate-slower {
  -moz-animation-duration: 3s;
  -webkit-animation-duration: 3s;
  -vendor-animation-duration: 3s;
}

Then use it pretty much like normal. 

`<div class="cell revealOnScroll" data-animation="fadeInLeft" id="animate-quick" data-timeout="400">`

I do agree we need a way to specify durations, but I'd suggest it passed as a parameter into the script. Maybe with a data-duration="2s"

**Comment by WarenGonzaga** [comment]
Alright! Will work on it and will bring to development! Thanks for your suggestion!

**Comment by daneden** [comment]
Closing this since it's getting addressed in #834, thanks for getting it together @WarenGonzaga!
