### ISSUE TITLE
[Nhóm#10] Lỗi phi chức năng - Lỗi không hiện thị của trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31151020883** [daneden/animate.css#816]
a. Web Browser: Côc Côc - Phiên bản 68.4.194
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang: http://online.ueh.edu.vn/
ii. #2: Thấy Khung đăng nhập của sinh viên không hiện thị số lượng truy cập
c. Kết quả thực tế: không hiện thị số lượng truy cập
d. Kết quả mong đợi:  hiện thị số lượng truy cập
![1](https://user-images.githubusercontent.com/38751373/39957675-03c34c04-5621-11e8-8d56-59869997a189.PNG)

**Comment by eltonmesquita** [comment]
Sorry, but I think you issued on the wrong repository. May I close it?

**Comment by DavidBruchmann** [comment]
BTW: number of hits are not in the HTML-source, at least not at in the shown form
```
<table border="0" width="100%">
    <tr>
        
        <td align = "left" style="color:Blue" >
            Số lượng truy cập :&nbsp; 
        </td>
           
        <td align="right" >
            <input type="submit" name="ctl00$ContentPlaceHolder1$ctl00$ctl00$btLogin" value="Đăng nhập" id="ContentPlaceHolder1_ctl00_ctl00_btLogin" class="button_dl" />
        </td>
    </tr>
</table>
```
