### ISSUE TITLE
Animate.css not active on mobile

### ISSUE THREAD

**Issue by franciisscott** [daneden/animate.css#817]
Hello, amazing work with this project, it works perfectly well on a PC, but I can't get it to work on mobiles, I tried two different browsers so I'm sure its not a Chrome problem, please what am I missing?
Thank you.

**Comment by eltonmesquita** [comment]
Hello. Can you please share a link, or better yet a pen on codepen with your code? It's probably just a small mistake as animate.CSS works perfectly fine on mobile.

**Comment by franciisscott** [comment]
Thanks for the reply, this is the link: https://codepen.io/franciisscott/pen/yjmzKm
I literally copied the exact animate.css I found online (most recent, I believe) and pasted in my folder.

Please let me know if you need any other thing. Thank you.

**Comment by eltonmesquita** [comment]
Sorry, but did you read the [readme](https://github.com/daneden/animate.css) and the instructions of how to use it? Your pen's empty. There's just the animate.css code which by itself is totally useless...

**Comment by franciisscott** [comment]
please what codes exactly should I post? I've got a index.php files and other js and css files in their folders.

**Comment by franciisscott** [comment]
[2087_kalay 2 2.zip](https://github.com/daneden/animate.css/files/2043079/2087_kalay.2.2.zip)
Hello, I uploaded the template I'm trying to use, I maybe if you could download and extract it it'll be easier for us? Thank you.

**Comment by eltonmesquita** [comment]
Sorry but I can't download an unknown zip. You can publish it and share a link, or you can post it in codepen, jsbin or any service like that.
But first make sure to follow all the instructions in the readme.

**Comment by franciisscott** [comment]
Good day, sorry for the stress I've caused so far, I've uploaded the files here on GitHub. The link to where the files are is "https://github.com/franciisscott/franciisscott.github.io", you can see the website at "franciisscott.github.io", animate.css works well on PC, but when you load "franciisscott.github.io" on a mobile, the animation doesn't occur. Thank you.

**Comment by eltonmesquita** [comment]
No need for apologies ;-)
I can't look at your code right now but by the looks of it, this seems to be a problem with the animate on scroll js library. I strongly recommend using AOS these days as it's up to date with current practices.

**Comment by franciisscott** [comment]
Sorry I've never even heard of that before, what can I do for now?

**Comment by eltonmesquita** [comment]
Just look at the [AOS](https://github.com/michalsnik/aos) instructions and switch the libraries. Alright?

**Comment by eltonmesquita** [comment]
Mind if I close this as this seems to be solved and is unrelated to animate.css?

**Comment by MichaelTheGamer** [comment]
Eltonmesquita- Hello. I actually had a very similar experience, but actually, that's not why I'm writing this. I clicked on your AOS link and it seems that the current build shows as failing. Having followed the conversation you had with franciisscott, if the current AOS is the one being used and it's the same one that is 'failing,' would that be the reason animate.css didn't work for him? I realize that this may seem like a very stupid question but for the fact that it was [according to franciisscott] working just fine on a PC (curious: did he mention the OS of the PC on which animate.css was working fine?). Also wanted to say that even though I couldn't get it to work for me either, I was very impressed with the quality of the coding. Thank you for both taking the time to read this and to make such a great product that I am sure several, SEVERAL thousand people have and are currently enjoying. Thanks again. And to all our fellow Devs out there, Happy Coding! 
Michael The Gamer

**Comment by eltonmesquita** [comment]
@MichaelTheGamer, the reason the animations didn't work on mobile was, by the look of it, the use of some outdated libraries. 3 or more years ago, mobile browsers didn't trigger the scroll events, so it was safer to just disable interactions on mobile.
Note that this doesn't mean animations didn't work on mobile, just that it wasn't feasible to trigger them on the scroll event.

**Comment by eltonmesquita** [comment]
I'm closing this as its solved. Feel free to reopen it if necessary.
