### ISSUE TITLE
Showing/hiding with jQuery

### ISSUE THREAD

**Issue by igorlopasovsky** [daneden/animate.css#818]
Hey, I was just wondering how can I combine animate.css with jQuery, specifically with jQuery show/hide methods. 

For example - clicking on button with show modal window but I would love to apply slideInLeft effect on it. 

Many thanks

**Comment by shulk** [comment]
`    $( '.left_panel' ).animateCss( 'fadeOutRight', function() {

      $( '.left_panel' ).hide();

    });`

That works fine, but I want to try better way also.

**Comment by mikegk** [comment]
That does work if you add:
`$.fn.extend({
        animateCss: function (animationName, callback) {
            var animationEnd = (function (el) {
                var animations = {
                    animation: 'animationend',
                    OAnimation: 'oAnimationEnd',
                    MozAnimation: 'mozAnimationEnd',
                    WebkitAnimation: 'webkitAnimationEnd',
                };

                for (var t in animations) {
                    if (el.style[t] !== undefined) {
                        return animations[t];
                    }
                }
            })(document.createElement('div'));

            this.addClass('animated ' + animationName).one(animationEnd, function () {
                $(this).removeClass('animated ' + animationName);

                if (typeof callback === 'function')
                    callback();
            });

            return this;
        },
    });`
And call it like:
`$("#elemend").animateCss('bounceOut',function(){
                $("#elemend").hide();
            });`

**Comment by igorlopasovsky** [comment]
Thanks shulk, works perfectly ;)

**Comment by eltonmesquita** [comment]
Closing this as it's solved.
