### ISSUE TITLE
Ask, can Vue be used?

### ISSUE THREAD

**Issue by wubodanran** [daneden/animate.css#820]

**Comment by Beanactor** [comment]
Yes ;
1. npm install animate.css ;
2. main.js :
import animated from 'animate.css' ;
Vue.use(animated)
3. <div class="box animated bounceInDown"></div>

**Comment by Beanactor** [comment]
Yes ;
1. npm install animate.css ;
2. main.js :
import animated from 'animate.css' ;
Vue.use(animated)
3. <div class="box animated bounceInDown"></div>

**Comment by Beanactor** [comment]
Yes ;
1. npm install animate.css ;
2. main.js :
import animated from 'animate.css' ;   Vue.use(animated)
3. <div class="box animated bounceInDown"></div>

**Comment by Beanactor** [comment]
YES;
1.                  npm install animate.css ;
2.  main.js :    import animated from 'animate.css' ; Vue.use(animated)
3.  <div class="box animated bounceInDown"></div>

**Comment by Beanactor** [comment]
<p>npm install animate.css ;</p>
<p>main.js : import animated from 'animate.css' ; Vue.use(animated)</p>

**Comment by Beanactor** [comment]
<p>npm install animate.css ;</p>
<p>main.js : import animated from 'animate.css' ; Vue.use(animated)</p>
<p> class="box animated bounceInDown"</p>

**Comment by Beanactor** [comment]
<ol type="1">
            <li>npm install animate.css ;</li>
            <li>main.js : import animated from 'animate.css' ; Vue.use(animated)</li>
            <li>class="box animated bounceInDown"</li>
</ol>

**Comment by Beanactor** [comment]
<ol type="1">
            <li style="color: #f00">npm install animate.css ;</li>
            <li style="color: #f00">main.js : import animated from 'animate.css' ; Vue.use(animated)</li>
            <li style="color: #f00">class="box animated bounceInDown"</li>
</ol>
