### ISSUE TITLE
jackInTheBox does not exist

### ISSUE THREAD

**Issue by omershelef** [daneden/animate.css#823]
I installed the latest version using bower and it seems that this class does not exist inside of animate.css,
its also seems by the comment at the head of the file that the release 3.5.2 is still built with version 3.5.1:

```
/*!
 * animate.css -http://daneden.me/animate
 * Version - 3.5.1
 * Licensed under the MIT license - http://opensource.org/licenses/MIT
 *
 * Copyright (c) 2016 Daniel Eden
 */

```

**Comment by eltonmesquita** [comment]
#790 fixed the versioning problem and when #833 gets fixed it'll probably fix bower too. But, bower is deprecated now and any issue will almost certainly get ignored. See #758 for more details.
