### ISSUE TITLE
Transition is not responding

### ISSUE THREAD

**Issue by jayeshsingh9767** [daneden/animate.css#824]
I just installed animate.css and when I start using it I realize that after applying animate class my 
on a <div>, my previously defined transition Properties are not Working Properly....
Actually I applied transition on three css properties viz. bg-color,border and scale, transition for bg-color and border are working but the its not scaling my div

**Comment by eltonmesquita** [comment]
This happens because animate.css uses transforms for the animations and they override what's set in the element. That's how css works.
You can put the element inside another element and set the animate's classes on this parent.

**Comment by jayeshsingh9767** [comment]
Ok thamks.....

**Comment by jayeshsingh9767** [comment]
Ok Thanks......
