### ISSUE TITLE
Instant load of modal

### ISSUE THREAD

**Issue by eavitan** [daneden/animate.css#827]
Hey, I would like to use this library for page transitions.
means I need the modal to be "on" (shown), right after the <body> and without any JS.

i tried copy passed the active modal and pass it to the body but it didnt work, is there a way to do it?

thanks

**Comment by eltonmesquita** [comment]
Sorry, but it's not possible to do such a thing without javascript. It's just not feasible. Also it's really hard to give any advice with so little.

Anyway, the best would be to elaborate more on the problem and post it on stackoverflow as this is an issue tracker for the library itself and you probably won't get much help here when the subject is not directly related to an issue in the library.
