### ISSUE TITLE
How to make heart pulse with animate.css

### ISSUE THREAD

**Issue by phlegx** [daneden/animate.css#829]
Hi!

Any idea how to make a heart pulse like [here](https://codepen.io/jlong/pen/KBhDf) but with animate.css?

Example: https://codepen.io/jlong/pen/KBhDf

**Comment by anirudhdggl** [comment]
I would love to fix this issue and add the feature. Let me know if I may go ahead.

**Comment by jamesgeorge007** [comment]
@phlegx I made some workarounds and submitted a PR  #830
> Does this serve the purpose?

**Comment by daneden** [comment]
Closed by #830
