### ISSUE TITLE
Accessibility and animations

### ISSUE THREAD

**Issue by marcysutton** [daneden/animate.css#831]
What a cool library you've got here! In the spirit of being plug-and-play, I thought it would be extra awesome if there was a way to easily turn animations on and off. For users with motion sensitivity, vestibular disorder or even just a wicked hangover, [animations can make them sick or worse](https://source.opennews.org/articles/motion-sick/)–it goes beyond simple aesthetics to become a safety issue. 

Fortunately, this is pretty easy to address using the [`prefers-reduced-motion` media query](https://webkit.org/blog/7551/responsive-design-for-motion/) (only on OSX and iOS Safari currently):

```
@media (prefers-reduced-motion) {
// do stuff
}
```

To toggle animations once this media query is in place, users can go to their system preferences and toggle "reduce motion".

![macos-sierra-reduce-motion](https://user-images.githubusercontent.com/1045233/42786445-3111f576-890b-11e8-99dc-da921587b3bf.jpg)

I have a PR ready to submit with this issue.

**Comment by daneden** [comment]
Thanks for taking this on @marcysutton!
