### ISSUE TITLE
Rewrite documentation

### ISSUE THREAD

**Issue by daneden** [daneden/animate.css#835]
The readme for Animate.css has outgrown its usefulness over the years. In addition, many of the things that were popular or important at the time of the library’s release are now outdated. In anticipation of a major 4.0 release, I'd like for us to rewrite the documentation with the following in mind:

- We should avoid jQuery examples in favor of plain CSS/HTML and JS examples
- We should use the Wiki to reference third-party libraries and more complex examples
- We should aim to drastically simplify the setup and build process for customizations and have that reflected in the docs

**Comment by WarenGonzaga** [comment]
Any updates about this one? I found a better documentation that we can use for animate.css.

**Comment by WarenGonzaga** [comment]
@eltonmesquita and @daneden this is what I'm talking for... please have time to check this...
https://docusaurus.io/ it is open source documentation for open source projects like this.

**Comment by eltonmesquita** [comment]
I like the idea of using docusauros. It's well maintained and have plenty of features that would solve our problems.

**Comment by daneden** [comment]
I’m not sure we need something as comprehensive as docusaurus: animate.css basically only has one instruction—use class names to animate stuff. I think we’d be better off with just a well-made single page documentation site.

**Comment by Manuel-Suarez-Abascal** [comment]
@daneden @WarenGonzaga  I would like to contribute to the single page documentation site. Do you have a design already that I could start working on?

**Comment by WarenGonzaga** [comment]
> @daneden @WarenGonzaga I would like to contribute to the single page documentation site. Do you have a design already that I could start working on?

Hi @Manuel-Suarez-Abascal we don't have a design at the moment we're focusing on making progress with the latest version of Animate.css which is the v4 of it. You can create a design and show it so we can decide or we can improve it. By the way, thanks for the help...

**Comment by eltonmesquita** [comment]
Just a small reminder to add a "Migration guide" as will have some major breaking changes on the next version.

**Comment by WarenGonzaga** [comment]
How about moving some parts of the README to Wiki page on this repo? Then later on planning to create a knowledge base for animate.css what do you think guys?
cc @eltonmesquita @daneden

**Comment by eltonmesquita** [comment]
That's a good idea but I'm in the process of updating the demo website adding the whole documentation. Hopefully, I can finish this new structure by the end of the week and everyone will get to contribute easily.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I love to restructure the README to much simpler one... as you can see the changes on dev branch.
