### ISSUE TITLE
Switch to Rollup

### ISSUE THREAD

**Issue by daneden** [daneden/animate.css#836]
Suggested by @eltonmesquita, [rollup with postcss](https://github.com/egoist/rollup-plugin-postcss) looks like it would give us everything we need and would simplify our build process, a goal explicitly set in #835.

**Comment by syncopated** [comment]
@daneden is the idea to replace `animate-config.json` with an `animate-config.js` that `import`s the modules the user chooses?

E.g.: 
// animate.config.js to be used with rollup

`
import 'attention_seekers/pulse.css';
// import 'attention_seekers/tada.css';
import 'bouncing_exits/bounceInDown.css';
`

I'm interested in helping.

**Comment by robsonsobral** [comment]
Have you already took a look at http://parceljs.org/ ?

**Comment by janydrozd** [comment]
@daneden is it still open? I could work on this.

**Comment by WarenGonzaga** [comment]
@janydrozd yes you can, please use the dev branch to submit your pull request since it is part of v4 feature.

**Comment by eltonmesquita** [comment]
I'm closing this as we're taking a even simpler approach and using only npx + postcss. See #900 .
