### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by daneden** [daneden/animate.css#837]
I'd like to keep the website as simple and straightforward as it currently is, but perhaps rewrite it to:

- Make it easier to maintain as new features and animations are added
- Provide more usage information upfront (as opposed to leading people to our now-gigantic readme)

**Comment by eltonmesquita** [comment]
Totally agree. A few thoughts:
* It'd nice to present the animations in a better way, as the current dropdown has overgrown itself. Maybe something like a side bar with a list of animations might be a good option.
* We could rethink about using the Animate.css title to show the animations as it doesn't show as clearly the animations. A simple element might do it better, [bouncejs](http://bouncejs.com/) is a good example, I think.
* As we don't need a branch for the website anymore, we can set up a build system that reads the configuration file (maybe we can keep the `animate-config.json`) and populates the website's animation list. That would make things simpler to update.
* In the docs part, a FAQ is really important.

**Comment by genemars** [comment]
It's good to see a new release. =)
Have a look at this build system: [zUIx web starter](https://github.com/genemars/zuix-web-starter).
It's the build system behind [zUIx](https://genielabs.github.io/zuix) library website, which of course is using *Animate.css*.

**Comment by WarenGonzaga** [comment]
@genemars looks cool... but I would prefer a more simpler one.

**Comment by mshams999** [comment]
seems a cool idea .

**Comment by WarenGonzaga** [comment]
@jamesgeorge007 yup, the update will be available on the next update which is v4.0 please stay updated :)

**Comment by jamesgeorge007** [comment]
:+1:

**Comment by eltonmesquita** [comment]
So @daneden , do we just expand the current website, adding a doc/faq page? That'll be pretty quick and could be ready for the `v4` release. What are your thoughts?

**Comment by daneden** [comment]
@eltonmesquita I think that would be great! It might be cool to have the current page take up ~80vh and then users can just scroll to see docs.

**Comment by WarenGonzaga** [comment]
@daneden @eltonmesquita alright! awesome! for @daneden it might be so cool if you have time to make an animate,css logo or icon for the v4 launch... what do you think?

**Comment by raxraj** [comment]
I have a suggestion what if we divide it into 2 Drop Downs:-
1. One to select the category!
2. Second to select the animation!!

**Comment by WarenGonzaga** [comment]
> I have a suggestion what if we divide it into 2 Drop Downs:-
> 
> 1. One to select the category!
> 2. Second to select the animation!!

Cool idea! That would help...

**Comment by raxraj** [comment]
I can work On that!!! Shall I ?? :grin:

**Comment by WarenGonzaga** [comment]
> I can work On that!!! Shall I ?? 😁

Sure just do PR ;)

**Comment by raxraj** [comment]
@WarenGonzaga !! Have a Look & Lemme Know!!

**Comment by raxraj** [comment]
@WarenGonzaga ! Just a Reminder I guess you forgot !! I have made a PR #995 
 as per my following Suggestion!
Kindly have a Look!

> I have a suggestion what if we divide it into 2 Drop Downs:-
> 
>     1. One to select the category!
> 
>     2. Second to select the animation!!

**Comment by WarenGonzaga** [comment]
Yeah I'm aware on that @raxraj let's wait @eltonmesquita to check it.

**Comment by raxraj** [comment]
@WarenGonzaga !! It's okay!
Yeah! Cool!

**Comment by WarenGonzaga** [comment]
@eltonmesquita @daneden updates on this?

**Comment by eltonmesquita** [comment]
Working on this right now :D

**Comment by WarenGonzaga** [comment]
@eltonmesquita got it... just let me know when you're done.
