### ISSUE TITLE
animate.css and bootstrap css working unusual together

### ISSUE THREAD

**Issue by DevelopedByAnurag** [daneden/animate.css#843]
hey i Love animate.css due to is animations but it is working very unusually with bootstrap fixed navigation bar resulting in changing page design is there any solution to rectify that as i love the both and want to use them in my project

**Comment by eltonmesquita** [comment]
Hello.
Can you share a link with the issue? Better yet, could you make a simplified case on codepen?

That'll make easier to help you.

**Comment by DevelopedByAnurag** [comment]
basically it is ending the mobile friendliness of the site by increasing the width of the nav bar in bootstrap and also i will create a sample and share the link just here itself

**Comment by eltonmesquita** [comment]
If I got it right, you're having overflow issues. The simple fix is just add `overflow: hidden` to the parent of the animated element. You'll probably have to adapt something, but it's the same idea.

**Comment by DevelopedByAnurag** [comment]
That means I have to add it to each element where i will use any of the animations ?????

**Comment by WarenGonzaga** [comment]
@DevelopedByAnurag it is better to provide codepen for the issue so we can check and fix it.

**Comment by WarenGonzaga** [comment]
@DevelopedByAnurag any updates? we will close this if this issue is inactive :)

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
