### ISSUE TITLE
Increase delay between infinite iterations

### ISSUE THREAD

**Issue by jaminroe** [daneden/animate.css#850]
Since using `animation-delay` for adding delays between an `infinite` loop doesn't work, would be nice to build this into this library. If you want to do it now, you have to override your animations/timing and then change the `duration`.

Not sure if there's a clever way to build this in some how. Wanted to throw this suggestion out there. Thanks! 😄

**Comment by WarenGonzaga** [comment]
@jaminroe I will look into this since I am the one who implements it... thanks for reporting!

**Comment by eltonmesquita** [comment]
Sorry, but there's no way to achieve this with CSS only as `animation-delay` only sets the staring delay and not a delay between iterations of the same animations. As @jaminroe cited, the only way would be to rewrite every animation and add a "pause" inside the keyframes themselves.  It just wouldn't make sense. 
I think that's something we can document on #835 and maybe provide a js solution there for such cases.
