### ISSUE TITLE
slideInRight not working on mobile properly

### ISSUE THREAD

**Issue by snakone** [daneden/animate.css#852]
while slideInLeft its working on Mobile, slideInRight for some reason makes the document wider and taller, you can note this because a scrollbar appears while the animation is in. slideInLeft  doesnt make any scrollbar at all. On mobile this issue deconstruct some responsive websites because its changing the actual document.width and document.height

PD: It works OK if the div sliding in is smaller than the actual window.size, anyway scrollbar still appearing

**Comment by snakone** [comment]
overflow: hidden

**Comment by coderdiaz** [comment]
same issue :(
