### ISSUE TITLE
Add Development Branch

### ISSUE THREAD

**Issue by WarenGonzaga** [daneden/animate.css#854]
Hi @daneden and @eltonmesquita can we add develop branch to this repo? So we can work on beta version of animate.css before we release the final version and merge it with current version. It will help us to manage the version 4.0 of animate.css.

**Comment by eltonmesquita** [comment]
I just added the `dev` branch. Let's keep all the new features and fixes there. The master should reflect the current release. This way we get a better dev flow.
Thanks for the suggestion 😄 .
