### ISSUE TITLE
Bug with child element with transition and animate on parent in EDGE

### ISSUE THREAD

**Issue by dreamtheme** [daneden/animate.css#857]
I have found a strange bug that happens in EDGE only. 
If you use "animated slideinleft" for example on parent div and on child div you have transition all 2s for example and then you have scale 1.1 on hover on child, the transition on mouse over get bugged with animated on, without animated its fine.

**How its bugged:** If you leave the mouse cursor over the element for the entire transition duration during hover of the child and then you move out the mouse cursor of the element there is no transition animation for mouse over anymore. If you however move the mouse before the initial hover transition is over, on mouse over normal transition works as it should. If you remove the  "animated slideinleft" from the parent, everything works fine in child transition. This happens only in EDGE, i tested on version Microsoft Edge 42.17134.1.0, it doesn't happen in IE 11.

**Video of the bug** - https://drive.google.com/file/d/1Xo88A64wPe61HYyocaycfqb9TmIUCaIa/view
**codepen link:**  - https://codepen.io/anon/pen/xJNvPm

I would appreciate a way to fix that.

**Comment by WarenGonzaga** [comment]
I look over the issue, this is might be causing the translate3d in the animation which is you can found on slideInLeft... or might be this is a browser bug on edge. I think @daneden can debug this thing.

**Comment by dreamtheme** [comment]
Hi there, 
I figured out that if add "transform: scale(1);" to the child before hover(scale(1.1)) state (inner2) fixes the issue, although i still don't know what is the exact problem other that is connected somehow with animated.

**Comment by WarenGonzaga** [comment]
@dreamtheme awesome! @eltonmesquita I think you need to close this now...
