### ISSUE TITLE
NativeScript Compatibility

### ISSUE THREAD

**Issue by ronaiza-cardoso** [daneden/animate.css#858]
Is there compatibility with NativeScript?

**Comment by eltonmesquita** [comment]
Well, that's a trick question. I can't say for sure but according to the documentation the `@keyframe` and `transform` property are supported by NativeScript, so it should work just fine. But I can't guarantee as I never tested it or heard anything about.

It'd be nice if you could try and give some feedback here!

**Comment by WarenGonzaga** [comment]
@ronaiza-cardoso hello, as long as you use animate.css only without any other animation library such a greensock then you will have no problem on it. If you found some issues on using with NativeScript please let us know.

**Comment by eltonmesquita** [comment]
So it's confirmed that animate.CSS + Native Script work together but with some performance issues? 
Can we then close this?

**Comment by WarenGonzaga** [comment]
@eltonmesquita we are safe to close this...

**Comment by eltonmesquita** [comment]
Alright. Thanks.

**Comment by davimello28** [comment]
Sorry for reopening this issue, but I had some troubles implementing NativeScript and Animate.css and I would like to share my experiences. 

In later versions of Animate.css, some proprieties of the `.animated` doesn't work with NativeScript (nor NativeScript-Vue and NativeScript-Angular). 

This:
```xml
<TextField ... class="input input-border animated fadeInRight">
```
```css
@import "~animate.css/animate.min.css"; /* This was installed via NPM. */
```
Throws this:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: TypeError: Cannot read property 'length' of undefined
```

But you can do something about it. It is reported in the [previously mentioned link](https://github.com/NativeScript/NativeScript/issues/5731). You can create your own `animated` class with the parameters accepted by the [NativeScript animation API](https://docs.nativescript.org/ui/animation), like the example.
```xml
<TextField ... class="input input-border myAnimation">
```

```css
@import "~animate.css/animate.min.css"; /* This was installed via NPM. */

.myAnimation {
    animation-name: fadeInRight; /* Select the Animate.CSS animation. */
    animation-duration: 2s;
    animation-fill-mode: forwards;
}
```
I am not sure if I am missing something about the `.animated`, but this works. Further research is needed 

Animate.CSS is something simple and awesome that I've used for a while. Thank you for this awesome tool!

**Comment by wargun02** [comment]
@davimello28 . Thanks for the suggested workaround. I helped me a great deal.
