### ISSUE TITLE
Chrome 70.x compatibility issues

### ISSUE THREAD

**Issue by nzamosenchuk** [daneden/animate.css#860]
Animate.css doesn't work as expected with Chrome Version 70.0.3530.0 (Official Build) canary (64-bit).
**Steps to reproduce**
1. Navigate to https://daneden.github.io/animate.css/ in Chrome 68.x -> works fine
![image](https://user-images.githubusercontent.com/1624855/44519283-df053600-a6cc-11e8-9a7d-d05f31e8dc71.png)
2. Navigate to https://daneden.github.io/animate.css/ in Chrome 70.x -> **effects and display is broken:**
- the text is larger as it should be;
- after any entrance animation, the text disappears.
![image](https://user-images.githubusercontent.com/1624855/44519230-bd0bb380-a6cc-11e8-93d4-9b137b41e55f.png)

**Comment by eltonmesquita** [comment]
This is a new bug with the `-webkit-text-fill-color` property. I think we'll have to use svg mask or something like that if the bug persist in Chrome's stable channel. I'll keep one eye on that.

**Comment by WarenGonzaga** [comment]
@eltonmesquita awesome!

**Comment by wbitholedotbe** [comment]
Looks like it is perfectly working now. Tested on dev channel, beta channel and canary... Issue can be closed now.

**Comment by nzamosenchuk** [comment]
Indeed, can confirm it works now fine in the canary. I think we can close.
