### ISSUE TITLE
Question: Is it possible to trigger animation on hover?

### ISSUE THREAD

**Issue by Tosken1337** [daneden/animate.css#863]
Question: Is it possible to trigger animation on hover?

Thanks

**Comment by eltonmesquita** [comment]
Yeah, of course. Jus use the keyframe names in your CSS instead of the classes directly in your HTML. Something like:
```css
.element:hover {
  animation: jackInTheBox 2s;
}

**Comment by eltonmesquita** [comment]
@Tosken1337, any news if that worked? I'm closing this soon if I get no response.

**Comment by max-favilli** [comment]
I had the same question.

Seems it works, as long as the element is a block or inline-block element. Doesn't work if it's an inline element. 

Maybe it's intended.

It works.

**Comment by bondt** [comment]
Duplicate of #170
