### ISSUE TITLE
Make animation run once time when contructor ?

### ISSUE THREAD

**Issue by danbeo95** [daneden/animate.css#866]
Hey, I using Ionic .In my page ,I add animation fadeInLeft .I want this animation olny run when constructor ?.How can I do .Thaks so much

**Comment by buggyboyz** [comment]
I dont know if its possible nice but i just link and href animated.css on
my page. You can read docs about animate.css :)

28 Eyl 2018 Cum 11:09 tarihinde danbeo95 <notifications@github.com> şunu
yazdı:

**Comment by WarenGonzaga** [comment]
Hi there, can you elaborate more on what you want to achieve with the animate.css?

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
