### ISSUE TITLE
How to run a 3s animation and wait xs for the next one

### ISSUE THREAD

**Issue by Matias-Carazzo** [daneden/animate.css#871]
Hi,

it is more a question than an issue.
I just want to run an animation , pulse for instance. Wait 10 seconds and execute it again.
I prefer to use just css, no js.

Thanks,

**Comment by buggyboyz** [comment]
Hi,
you can find on stackocerflow or codepen.com
if you dont want to use js for this animation, you should analyze that code
you can find in there :
https://codepen.io/search/pens?q=pulse&page=1&order=popularity&depth=everything&show_forks=false

See ya!

Matias <notifications@github.com>, 12 Eki 2018 Cum, 00:28 tarihinde şunu
yazdı:

**Comment by eltonmesquita** [comment]
Actually there's no easy way to do this with CSS only as the `animation-delay` property only works for the beginning of the animation.  The easiest and not-hacky way to do this is to use a few js lines to achieve the effect.

As this is an issue tracker you won't get much help here as it's focused on issues of the library. Use stackoverflow instead as there are lots of helpful people there that will gladly help you.

I'm closing this as it's solved.
