### ISSUE TITLE
Works on another block

### ISSUE THREAD

**Issue by aleksandrx** [daneden/animate.css#873]
Hi, why does the animation on the header of the site work in my mobile version, although there should be no animation there? Fixed site header. `https://clickdress.ru`

**Comment by eltonmesquita** [comment]
You probably have some strayed classes, an invalid media query, or anything else. Please recheck your code and make sure to follow all the instructions. As this is an issue tracker we can't help much when it's something not directly related to the library itself. On stackoverflow you'll get the help you need and much faster.

I'm closing this as it's unrelated to the library.
