### ISSUE TITLE
Update jQuery examples to Vanilla js

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#875]
As we're in 2018, jQuery isn't so ubiquitous as it used to be and Vanilla js is pretty safe these days, we should replace the jQuery examples by pure Javascript.

**Comment by WarenGonzaga** [comment]
@eltonmesquita why is it still open if you already push the necessary changes?

**Comment by daneden** [comment]
@WarenGonzaga it looks like that PR was just some housekeeping and doesn’t actually replace the jQuery examples with vanilla JS, so it makes sense to keep this open for now!
