### ISSUE TITLE
The wobble animation costs much CPU

### ISSUE THREAD

**Issue by szabyg** [daneden/animate.css#876]
As we figured out, the wobble animation (unlike other animations) defines keyframe translations in percentage, e.g. `transform: translate3d(-25%, 0, 0) rotate3d(0, 0, 1, -5deg);`. The animation itself is done in the GPU but calculating the exact positions stays in the CPU for each frame, causing >5% CPU for each animated element.
Any ideas other than replacing the percents by hard-coded pixels?

**Comment by eltonmesquita** [comment]
Thanks for the issue @szabyg.
Which browser and version are you using? How are you measuring it? Can you provide an isolated case? I've done some light testing on Chrome 69 on Mac and couldn't see anything unusual, but I do know that each browser deal differently with animations and transform.

I can try to help here but I really need more details.

**Comment by szabyg** [comment]
I'm also using Chrome 69 but on Windows. Measured it in the Developer tools "Performance monitor" tab (the one in the Console area).
An isolated case will come in the next days if necessary...

**Comment by eltonmesquita** [comment]
Hello @szabyg!
Any news on the reduced case?
Thanks!

**Comment by szabyg** [comment]
Sorry, I can't create an isolated case at the moment. We're working with LESS and went with the following workaround for the time being:

```
@wobble-base-width: 36px;
transform: translate3d(calc(@wobble-base-width * -0.25), 0, 0) rotate3d(0, 0, 1, -5deg);
```
That is, we copy the keyframe definitions from the library, define the base width as a LESS variable and modify the percent-sizes replacing them with a LESS calculation. This is calculated at compile-time and the browser CPU usage is low as it supposed to be.

**Comment by eltonmesquita** [comment]
Without an isolated case is really hard to investigate the issue. My guess is that you're animating some large elements and this makes them translate a lot of pixels. If that's the case I'd advice to avoid animating them as it wouldn't improve neither the UX or the performance of the website/application.

As no case was provided, I'll close the issue. Feel free to reopen it if you get at least a bit more of details.
