### ISSUE TITLE
missing releases on npmjs

### ISSUE THREAD

**Issue by DanielRuf** [daneden/animate.css#879]
3.3.0, 3.3.1 and so on are missing on npmjs. Would be good to have them there too.

**Comment by WarenGonzaga** [comment]
@DanielRuf we will update it as soon as we have updated the v4.0 for the animate.css

**Comment by WarenGonzaga** [comment]
@eltonmesquita who worked on npmjs?

**Comment by DanielRuf** [comment]
In general the owner and I can close this issue. The aforementioned tags / versions still do not exist so I'll not close it.

**Comment by DanielRuf** [comment]
You can always tag / release / push tags later.

**Comment by WarenGonzaga** [comment]
@DanielRuf I don't get it... how can we put the latest version on npm... sorry I am not familiar in submitting open source projects on npmn.

**Comment by DanielRuf** [comment]
Normally by doing `npm publish` and `npm version and so on`. See https://docs.npmjs.com/cli/publish and https://docs.npmjs.com/cli/version

And you can always travel back to an old commit with `git checkout commit-hash`.

**Comment by WarenGonzaga** [comment]
@daneden can you please update our npm package? Thanks!

**Comment by daneden** [comment]
Closing this issue, no need to update npm since the latest release is already there.

**Comment by DanielRuf** [comment]
> 3.3.0, 3.3.1 and so on are missing on npmjs. 
Well, it's not about latest but old versions (we want to lock them to these for example).

Publishing them afterwards is easy.
