### ISSUE TITLE
Firefox 63.0 breaks something in v. 3.7.0

### ISSUE THREAD

**Issue by bedo2991** [daneden/animate.css#882]
It looks like in Firefox 63.0 the event animationEnd gets never fired if using v. 3.7.0
Using v. 3.5.2 of animate.css on Firefox 63.0, it works fine.
The website was working fine with 3.7.0 and Firefox 62.0.3.

The event has been found using this suggested code:
```
var animationEnd = (function(el) {
        var animations = {
            "animation": "animationend",
            "OAnimation": "oAnimationEnd",
            "MozAnimation": "mozAnimationEnd",
           "WebkitAnimation": "webkitAnimationEnd"
        }

        for(var t in animations) {
            if(el.style[t] !== undefined) {
                return animations[t];
            }
        }
})(document.createElement("fakeelement"));
```

I can't provide a non-working minimal example at the moment, I will try to provide more information tomorrow.

**Comment by bedo2991** [comment]
Ok, it looks like the animation does not start at all in Firefox 63.0, and therefore it never ends.
Try this jsfiddle with chrome and with Firefox, make sure that Firefox is updated: https://jsfiddle.net/bxjvLnc5/

**Comment by bedo2991** [comment]
Ok, I've found the source of the issue.
In the Windows Settings, the options "Show animations in Windows" needs to be enabled.
From Firefox's changelog: _Firefox now recognizes the operating system accessibility setting for reducing animation_

**Comment by eltonmesquita** [comment]
That's probably a bug in the prefers-reduced-motion media query implementation on the Firefox side. I  think it might be worth to file a bug directly to Firefox's issue tracker.

If you can take your take to file the bug, that would be great. You can do it here: https://bugzilla.mozilla.org/

Closing this as it's not fixable in the library itself. 
Thanks for reporting!
