### ISSUE TITLE
infinite loop with pause

### ISSUE THREAD

**Issue by konstantin83** [daneden/animate.css#884]
Thank you for your wonderful CSS library. It's awesome!
Can you please explain the simplest way to make "tada" infinite loop with a pause of for example 5 seconds? It is possible to achieve that without using the JS?

**Comment by eltonmesquita** [comment]
That's not possible with CSS only unless you'd take your time to rewrite the animations to include a pause in the `keyframes` that sets the animation, which is not easy or recommended at all.
The best way is to use js. Listen to the animation end (like noted on the readme), remove the class, use a `setTimeout` and go through the whole process again.
If you need more help with the code, please use stackoverflow, as you'll get more helpful answers there as this is an issue tracker, focused on problems and improvement of the library.

**Comment by WarenGonzaga** [comment]
@eltonmesquita how about putting delay with combination of loop?

**Comment by eltonmesquita** [comment]
@WarenGonzaga, `animation-delay` only delays the initiation of the animation, it doesn't delay between iterations of it. Above I cited the only two ways I can think of how to achieve such thing. I honestly think there's no other way that will be much different from those ones.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I see, when can we start working on the animate.css v4 ?

**Comment by eltonmesquita** [comment]
Our current list for animate v4 is still a bit small, considering the library itself (excluding readme, website, docs, etc). There are somethings which I think would be nice to be added but I still couldn't propose it here. 

There isn't still any clear path or even a roadmap for the new release, but it doesn't mean that the work can't be done. Feel free to get any issue with the `v4` label and start working on it or even just discuss about the problem/proposal.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I created slack chat for the animate.css actually you want we can discuss there together with @daneden send me your email here: dev@warengonzaga.com

**Comment by WarenGonzaga** [comment]
@konstantin83 better to use it with javascript

**Comment by konstantin83** [comment]
Any ideas how to reach this with javascript?

**Comment by eltonmesquita** [comment]
> Listen to the animation end (like noted on the readme), remove the class, use a `setTimeout` and go through the whole process again.
> If you need more help with the code, please use stackoverflow, as you'll get more helpful answers there as this is an issue tracker, focused on problems and improvement of the library.

Ok? Mind if I close this as it's unrelated to the library itself?
