### ISSUE TITLE
Animation relative to the containing div

### ISSUE THREAD

**Issue by ottz0** [daneden/animate.css#886]
I'm using animate css with vue js and have an animation from left to right. However the animation goes from the whole of the window and I get bottom scrollbars.

I have tried to make a wrapping div set to absolute and the div with my animations set to relative but this does not seem to fix the issue.

How can I make my animations relative to it's parent?

**Comment by eltonmesquita** [comment]
The animations are always relative to the element as they use percentage in their transform, there's no fix for this (we did use absolute values before, using pixels but moved to percentage as it feels more flexible). What you can do is to put this element inside a container (like a simple `div`) and set `overflow: hidden` on it to avoid scrollbars.

As a side note, animating big elements is not recommended as there's a huge hit on performance and it'll hardly bring any UX benefit.

**Comment by ottz0** [comment]
Of course..Thanks!

Ok thanks for the side note

**Comment by eltonmesquita** [comment]
Mind if I close this?

**Comment by WarenGonzaga** [comment]
@eltonmesquita I think yes...
