### ISSUE TITLE
Slow, Slower, Fast, and Faster Class is a problem on iponeX

### ISSUE THREAD

**Issue by lw721** [daneden/animate.css#887]
The animation effect is not good, use the slow class, the animation speed is not uniform.

**Comment by WarenGonzaga** [comment]
we'll into this thanks!

**Comment by WarenGonzaga** [comment]
@lw721 can you please send us a screenshot on how bad it is? Thanks!

**Comment by WarenGonzaga** [comment]
@lw721 soft follow up on this... if this is an inactive issue I will let @eltonmesquita close this.

**Comment by lw721** [comment]
Not restored, maybe only in certain circumstances can be restored, I closed the problem
