### ISSUE TITLE
Bounce router-transition (bad positioning)

### ISSUE THREAD

**Issue by Trackmaniakos** [daneden/animate.css#890]
I am trying to use the transition "bounceInRight" and "bounceOutLeft" once the user clicks on the navigation buttons, however this happens:
[https://imgur.com/a/LaDfDRJ](url)
and then it slides back up like it should...
can I fix this in any way? (so that the bounceIn element will come at the same height as the bounceOut element?)
thanks in advance to anyone who checks this one out!

**Comment by WarenGonzaga** [comment]
@Trackmaniakos to further assist you and help please provide us a codepen.io version of your project so we can fix it for you. (I don't want to spoonfeed you, please don't abuse it or don't be spoonfed by others.)

**Comment by Trackmaniakos** [comment]
> 
> @WarenGonzaga 
thank you for the reply...The problem is that I am using multiple files in vuejs and the code is quite separated...so its kinda difficult to upload them on an online compiler...
In the app.vue file that vue creates, I have the navigation menu that you can see in the picture... and the transition that i`m trying to have happen:
```

    <router-link to = "/" tag="button" >Home</router-link>
    <router-link to = "/register" tag="button" >Register</router-link>
    <router-link to = "/login" tag="button" >login</router-link>
    <router-link to = "/updateUser" tag="button" >Update Data</router-link>
    <hr>
    <transition name="router-transition" enter-active-class="animated bounceInRight" leave-active-class="animated bounceOutLeft"> 
      <router-view/>
   </transition>
```

however I have other bits of code in the components as well...
I know that it might be confusing the way I`ve set it up...but its my first real project on vue and html and css(sorry you guys).

**Comment by WarenGonzaga** [comment]
@Trackmaniakos so the animation is triggered by a button or JavaScript?

**Comment by Trackmaniakos** [comment]
> 
> 
> @Trackmaniakos so the animation is triggered by a button or JavaScript?

The animation is triggered by clicking a navigation button yes.

**Comment by eltonmesquita** [comment]
It'll be very hard to help with so little information. I didn't even get to understand what's the real problem. Yet, I think this is related to the way you're using the Vue's transition component. As this is a Vue usage question this is not the right place to get help. This is an issue tracker for the animate.css library itself and should only be used when there's a real problem with the library itself (like a bug, suggestions for improvement, etc).

I strongly advice to seek for help for this kind of question on Stackoverflow as you'll get faster and better answers there. You'll probably get little help here.

I'll keep this open as @WarenGonzaga might be available to help you if he gets the time.

**Comment by WarenGonzaga** [comment]
Thanks @eltonmesquita, @Trackmaniakos  I will provide a simple demonstration or quick prototype of what you are expecting with animate.css let me do it and I'll get back to you

**Comment by Trackmaniakos** [comment]
@WarenGonzaga @eltonmesquita Thank you both for the help you`ve given me...Im sorry I posted here...I will know for future code related problems! WarenGonzaga Thanks for your time...I will check out whatever you come up with!

**Comment by Trackmaniakos** [comment]
I found the solution! you just have to give a mode for the animation:

` <transition name="bounceAnim" enter-active-class="animated bounceInRight faster" leave-active-class="animated bounceOutLeft faster" **mode="out-in"**>`

It prevents the elements to try to occupy the same space in the DOM during the animation, and when the one is "out" then the next one is "in".
thanks for the help!

**Comment by eltonmesquita** [comment]
Great news. Closing it as it's solved.
