### ISSUE TITLE
Proposed Animate.css Icon/Logo

### ISSUE THREAD

**Issue by WarenGonzaga** [daneden/animate.css#892]
Hello, @daneden and @eltonmesquita I would like to propose an icon to be used in our animation CSS library. Please see the attached image below. Let me know if it is a really good idea to provide our library with an icon. I saw many libraries and frameworks out there with their own icons and logo. Let me know your opinion thanks!

![animate css-version-1](https://user-images.githubusercontent.com/15052701/49188349-5f5ec580-f3a5-11e8-8a75-3c5689249136.png)

**Comment by daneden** [comment]
Hey @WarenGonzaga, thanks for taking the branding of Animate.css into consideration! I don’t think it’s crucial for us to have a logo for the project, and would prefer to design something myself if necessary.

As some design feedback for this particular logo, I think the Δ shape and color is good conceptually, but the typography is hard to read, particularly if the logo were displayed at smaller sizes.

**Comment by WarenGonzaga** [comment]
@daneden yup! that's only a prototype... hehe I know you are much better in design than me. If possible please let's give animate.css with an iconic logo.
