### ISSUE TITLE
Delays and position absolute not being applied on Safari Browser

### ISSUE THREAD

**Issue by dhwanils95** [daneden/animate.css#894]
Hello, 

When I am trying to animate a page with multiple components, it works fine on Chrome but not on Safari. Giving links for 3 approaches I tried to solve the issue but none of them seems to be working. 

[Approach 1](https://jsfiddle.net/dhwanilshah/m3sdewjz/)
Using static classes for animating as shown in your documentation. Tried on chrome and works perfectly but does not so on Safari.

[Approach 2](https://jsfiddle.net/dhwanilshah/yc8hd7s9/)
Using dynamic classes to assign delay values at run time because my values change on dynamic content every time the page loads.

[Approach 3](https://jsfiddle.net/dhwanilshah/gfyzh3am/)
Using JS' DOM style to inject animations.

Also, following is a post that I have put up on StackOverflow which has detailed description of the issues.
https://stackoverflow.com/questions/53813382/animations-and-animation-delay-behaving-randomly-on-safari

PS: I have copied only relevant animations from your animate.css into the fiddle and have played around with a few styling but nothing seems to work.

**Comment by eltonmesquita** [comment]
Can you make a less convoluted example? There are a lot of things going on there. Try to make it simple so it gets easier to help.
Add just two or three elements and make simple sequence so we can streamline what's happening, alright?

**Comment by WarenGonzaga** [comment]
Is this still active?
