### ISSUE TITLE
Add animation when hiding a div

### ISSUE THREAD

**Issue by eaglejohn** [daneden/animate.css#895]
I have a hidden search bar that I make active/visible by clicking on an icon (jQuery, toggleclass). I added an animation to it so it bounces down when being activated and this is working great.

Now, when I hide the active search bar again by clicking on the icon, it disappears as it should. But... there's no animation. I already tried adding an animation to the hidden search bar, but I can't get it to work so far.

Sorry, developing locally at the moment so I don't have a live example.

.search-container {
	@include bounceInUp;
	visibility: hidden;
	}

.search-container.search-active {
	@include bounceInDown;
	visibility: visible;
	}

Any suggestions?

**Comment by daneden** [comment]
@mphacker is right, you’ll have to use JS to detect when the animation is complete. Look into the `animationend` JS event for more details.

**Comment by eaglejohn** [comment]
I'll look into it later, my client has put this project on hold for at least a month. Thanks for now!
