### ISSUE TITLE
Absolute Position Element Animation

### ISSUE THREAD

**Issue by alalfakawma** [daneden/animate.css#896]
Okay, I have a bulma box element which is positioned at the center of the page, I want to animate the whole box, using the bounceInDown animation, but applying this animation is not centering the box anymore, it is moved to the right down from the center, is there a way to tackle this problem?

**Comment by alalfakawma** [comment]
Flexbox solved this.

**Comment by jeanieherold** [comment]
I had this exact same issue just recently on a site. I removed the
text-center off the div and that fixed it. I used absolute positioning for
the div to center
