### ISSUE TITLE
Bug with animate on latest firefox (even the last 2 major version of firefox)

### ISSUE THREAD

**Issue by batata004** [daneden/animate.css#898]
Pass your mouse over the red element at: https://jsfiddle.net/egaLns4j/

If you do so using chrome you will see an effect being applied. If you do so using FF, nothing happens.

The code at https://jsfiddle.net/egaLns4j/ is pretty minimmal and I cant understand how firefox does not work with it.

**Comment by eltonmesquita** [comment]
I just updated Firefox (64.0.2 (64-bit) on Windows 10) and everything's working fine. Check your FF's configurations as this might be related to #831.
If the problem persists, please share your browser and OS versions.

**Comment by batata004** [comment]
I just checked now and I am using latest FF on WIN10. See print below.

I am not using any extension/addons, no crazy confs... just plain and simple clean install of firefox. And this bug happens to me and it was also a customer of mine who told me about it and when I checked on my firefox it indeed happened.

![image](https://user-images.githubusercontent.com/8988923/51150795-2db79600-184f-11e9-929d-c758a7b29178.png)

**Comment by eltonmesquita** [comment]
Sorry, but I even tried this on FF for Linux and everything's working fine. One thing that you can try is to remove and add both classes, `animated` and `rubberBand` as this might be related.

**Comment by eltonmesquita** [comment]
Hey @batata004 any news on this? I still thinks it's not an animate.css issue.

**Comment by batata004** [comment]
@eltonmesquita I tried on 2 other computers with latest FF and Win 10 and this bug happens. BUT I think it may not be related to animate.css but with FF for some reason. I ended up formating my WIN10 and after that FF worked with animate.css. BUT on computers that UPGRADED from older versions of FF showed this problem. I am convinced that animate.css is not curlprit for this but I woud like to keep this open just for a few days cause I opened a bug report on mozilla so they can check this thread.

**Comment by eltonmesquita** [comment]
Was there any active extension when you ran into the problem?

**Comment by batata004** [comment]
No, I had no extension installed. I never use FF, I always use only Chrome.
A customer of mine told there was a problem on his FF, so I gave it a try
on mine (I had an old installation, so before testing I upgraded firefox)
and verified the problem. Anyway, I told already to mozilla about the
problem and I am waiting their verification.
--
*GLAUCO PERON*


Em dom, 20 de jan de 2019 às 19:18, Elton Mesquita <notifications@github.com>
escreveu:

**Comment by eltonmesquita** [comment]
I'm closing this as it isn't related to the library. Feel free to reopen it if needed.

**Comment by batata004** [comment]
Problem solved! It's indeed an issue with ANIMATE.CSS library! It is not using MOZ vendor prefix! Some Firefox distributions (even the latest one with Portuguese) for some reason requires MOZ prefix! Animate.css only prefix with "webkit" and nothing else! Is it possible to get it to work with moz?

**Comment by batata004** [comment]
That's indeed odd but I think animate should not drop MOZ support since many people use still outdated version AND even the latest version in portuguese demands using MOZ for some reason. Maybe FF will fix this soon but as I speak with you, my latest version of FF has this issue.

**Comment by eltonmesquita** [comment]
Nope. I've got the BR version in portuguese on three systems (Windows 10, Mac and Linux) and they all work just fine. There should be no changes in the browser's engine based on the language.

It might be a long shot, but I've seem cases where some malware/adware substituted the installed browser for some older and modified versions of them, believe it or not.

Maybe that's the case? As you can see [here](https://caniuse.com/#search=animation) and [here](https://caniuse.com/#search=transform), there's no need for the `-moz` since version 16.

**Comment by batata004** [comment]
THIS BUG THAT I REPORTED SEVERAL MONTHS AGO WAS JUST ACKNOWLEDGED RIGHT NOW at https://github.com/daneden/animate.css/issues/928

Anyway, at least now it's clear I am not crazy or doing something completely weird.
