### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#902]
Right now we don't have any Code of Conduct. I think this is necessary and we should adopt one as soon as possible.
To me the standard **Contributor Covenant Code of Conduct** fits well for this project.
What do you think @daneden?

**Comment by daneden** [comment]
Fantastic idea, let’s do it! The Contributor Covenant looks great.

**Comment by eltonmesquita** [comment]
Nice! The only thing to decide is the e-mail that will receive the reports, which will be publicly available. Should I put yours or mine?

**Comment by WarenGonzaga** [comment]
That's cool! Willing to contribute....
