### ISSUE TITLE
Only bounceIn class works, the rest dont...

### ISSUE THREAD

**Issue by tifDev** [daneden/animate.css#905]
Only the bounceIn effect works, the others dont. Here is my code:

```
          <div class="col-md-12 col-sm-12 animate bounceIn slow">
            </div>
```

If i change bounceIn to any other it doesn't works...

This might be help also: https://github.com/daneden/animate.css/issues/293

Browser: Chrome and Mozilla

**Comment by eltonmesquita** [comment]
This is probably some CSS clash on your code base. Probably those other classes (`col-md-12 col-sm-12`) are overwriting some of animate.css declarations. Just add everything inside other element and add the animate's classes to it.

**Comment by tifDev** [comment]
Still not working :/

**Comment by eltonmesquita** [comment]
Hello. Did it work? May I close this?

**Comment by tifDev** [comment]
Yes it worked, thanks !
