### ISSUE TITLE
Can't fadeInUp doesn't work in website how to use it please suggest me?

### ISSUE THREAD

**Issue by skchinna7** [daneden/animate.css#907]
Please help how to use ur css in the page?

**Comment by eltonmesquita** [comment]
Please use the instructions on the [readme page](https://github.com/daneden/animate.css#installation). If you're having a hard time using it, you won't get much help here as this is an issue tracker and we're focused on improve and solve issues of the library itself and just can't help everyone.

Open a question on stackoverflow as there you'll probably get all the help you need.

I'm closing this as it's unrelated to the library itself.
