### ISSUE TITLE
Hinge animation does not work with rotated elements

### ISSUE THREAD

**Issue by Terrafire123** [daneden/animate.css#908]
When I try to apply the hinge animation to an element that's already rotated, the animation completely falls apart, because the animation doesn't start with a rotate of 0 degrees.

Which normally is fine, that's not the library's fault.... but there's no reason why it shouldn't work. Simply by adding the following lines to the beginning of the Hinge animation, everything will work smoothly:

    -webkit-transform: rotate3d(0, 0, 1, 0deg);
    transform: rotate3d(0,0,1, 0deg);

like so:

@keyframes hinge {
  0% {
    -webkit-transform-origin: top left;
    transform-origin: top left;
    -webkit-animation-timing-function: ease-in-out;
    animation-timing-function: ease-in-out;
    **-webkit-transform: rotate3d(0, 0, 1, 0deg);**
    **transform: rotate3d(0,0,1, 0deg);**
  }

**Comment by eltonmesquita** [comment]
You can't have multiple transform declarations on the same element, they'll just get overwritten. The best workaround is to put the transformed element inside other element and animate this parent so you won't override the child's transform.

Your fix is bespoken, it will only work in your case. We can't consider adding it in the library itself as it'll probably just brake things.

I'm closing this as it isn't a real issue with the library.

**Comment by Terrafire123** [comment]
In what possible case could the fix I recommended possibly break anything? Like you say, all of the transforms will get overwritten anyway.

My fix is just overwriting the transform a little earlier so that if there WAS an old transform:rotate3d on it, it gets reset to 0 with an animation, instead of jumping directly to the new **transform** in an extremely ugly way..
