### ISSUE TITLE
Version 3.7 Does Not Support Firefox

### ISSUE THREAD

**Issue by sungdzda** [daneden/animate.css#910]
I am using the zoom-in effect from animate.min.css and firefox (desktop) is not responding to it.

Here are my test results:
Firefox latest: 3.5.2 works fine, 3.7 doesn't work
Chrome latest: both versions work

Please let me know if this is a glitch on my part. Thanks.

**Comment by eltonmesquita** [comment]
Hello.
Can you elaborate more? I just tested on FF 64.0.2 and 65.0 on Windows and everything worked just fine.

**Comment by sungdzda** [comment]
Hi. I am using Firefox 65.0 (64-bit) on Windows and the only variable seems to be the version of my animate.css file.

I have tried the following:
- alternate betweed CDN and local file (doesn't work)
- use animate.css instead of animate.min.css (doesn't work)
- start in safe mode with extensions disabled (doesn't work)

I can confirm that 3.7 works with FF 64.0.2 on my other computer. Just not sure about 65.
It works on FF 65 as soon as I swap 3.7 for 3.5.2.

**Comment by eltonmesquita** [comment]
I'm pretty sure this is related to #831. Please check your configurations on Windows to see if animations are off.
(Go to: "Configuration > Screen > Show animations on Windows" and check if this on)

**Comment by sungdzda** [comment]
Thank you. It turns out that Firefox is just being presumptuous.
