### ISSUE TITLE
div takes two clicks to show animation

### ISSUE THREAD

**Issue by laurencefass** [daneden/animate.css#912]
I have a wrapper div with hidden content which shows/hides on click of an adjacent button. animate.css appears to only work on the second (show) click, and then works indefinitely for subsequent hide/show clicks.

thanks

**Comment by eltonmesquita** [comment]
Hello.
Could you please share a live example with the problem on codepen?

**Comment by WarenGonzaga** [comment]
@laurencefass any updates? If it is possible please provide us a codepen so we can check it and solve it.

**Comment by laurencefass** [comment]
cannot reproduce

**Comment by WarenGonzaga** [comment]
okay thanks! Any issues please find a way to reproduce so we can check it and debug it.
