### ISSUE TITLE
[Improvement] Set opacity to 0 on all elements with `out` classes when media is set to `prefers-reduced-motion`

### ISSUE THREAD

**Issue by jadurani** [daneden/animate.css#914]
The intention of "-Out" classes (fadeOut, zoomOut, slideOut, rollOut, and the like) is to stylize the _disappearance_ of the element which uses this variation of "-Out" class. However, for browsers that have set `prefers-reduced-motion`, all these animations are not executed. Hence, during the instances that these elements need to disappear from the UI (opacity set to 0), _they do not disappear as intended_.

I found this issue while testing my website on Firefox v65 and Chrome Canary v74 on Windows 10 while I was checking for cross-browser compatibility.

To address this, I highly suggest addressing it like this:

```
@media (prefers-reduced-motion) {
  .fadeOut,
  .zoomOut,
  .slideOut,
  .rollOut {
    opacity: 0;
  }
}
```

If you have a better approach, just ignore mine, but kindly share in this thread too. Thank you.

**Comment by WarenGonzaga** [comment]
Hello, @jadurani thank you for your suggestion, I will review this one together with @eltonmesquita and we'll get back to you... ;) what can you say about this @daneden

**Comment by eltonmesquita** [comment]
You clearly have a point. I'll take some time and review your request and its side-effects. I'll keep this open as a referral to the request.

**Comment by eltonmesquita** [comment]
@WarenGonzaga , would you mind to PR this into the dev branch?

**Comment by WarenGonzaga** [comment]
@eltonmesquita just set all the animation with out classes to 0?

**Comment by eltonmesquita** [comment]
Yep.  I couldn't think in a scenario where this could be a problem, do you?

**Comment by WarenGonzaga** [comment]
@eltonmesquita how about something like ``slideOutLeft`` is this included or just those classes with Out only?
