### ISSUE TITLE
Change direction

### ISSUE THREAD

**Issue by front-bittencourt** [daneden/animate.css#918]
How can I change the direction of transition in the middle of the process?

**Comment by eltonmesquita** [comment]
While that would be possible, that would be a lot of work, honestly. If you have that kind of need, a javascript animation library would be a better suit for you.

Have a look on [anime.js](https://animejs.com/). It's a great and lightweight js library that works really well and will probably fulfill your needs.

Mind if I close this?

**Comment by front-bittencourt** [comment]
Ok, pode fechar
