### ISSUE TITLE
bounce in some DIVs sequentially

### ISSUE THREAD

**Issue by peterremote1980** [daneden/animate.css#926]
Hi, how to bounce in some DIVs sequentially?
thanks
Peter

**Comment by khadro** [comment]
Assuming you have a containing DIV element, with only the items you want to bounce in inside it, you can use the following:

**HTML**
```
<div class="container">
  <div class="item animated bounceInRight"></div>  
  <div class="item animated bounceInRight"></div>  
  <div class="item animated bounceInRight"></div>  
  <div class="item animated bounceInRight"></div>  
  <div class="item animated bounceInRight"></div>  
</div>
```

**SCSS**
```
.item {
    // alignment and positioning styles in here.

    @for $i from 1 through 6 {
      &:nth-child(#{$i}) {
        animation-delay: #{$i * 0.35}s;
      }
    }
  }
```

This will increment the animation delay for each item by 0.35s. Obviously that value is modifiable to whatever makes sense to you, as is the animation class you attach.

If you're not using SCSS you can still achieve it, but you will need to be explicit in your CSS for each `:nth-child`, which means you cannot add more elements than you originally code for.

**Comment by eltonmesquita** [comment]
Closing this as it's unrelated and got a proper answer.
