### ISSUE TITLE
Animating element out (in React)

### ISSUE THREAD

**Issue by FredyC** [daneden/animate.css#927]
First of all, thanks for this little lib. I was always kinda afraid animations to be something hard to do. This was an amazing experience. Just add the class and it works 🎉 

I am wondering if some ReactJS people are around here and how to achieve animation on unmounting component. I've figured out to animate on a change I can just set the `key` prop. Unmount feels like a much harder beast because the element is gone sooner than animation even begins. I am not even sure how I would delay unmounting of component.

**Comment by eltonmesquita** [comment]
Hello @FredyC.
You have to use [React Transition Group](https://github.com/reactjs/react-transition-group) or a similar library. It's no trivial task to handle the mounting and unmounting of a Component in React.
Just adapt the instructions on the documentation of RTG and you're good to go.

**Comment by FredyC** [comment]
Ah, that sounds promising. Thanks.
