### ISSUE TITLE
from css to mp4

### ISSUE THREAD

**Issue by matteoraggi** [daneden/animate.css#930]
Do you have soe suggestions to tranform these wonderfull css animations in mp4?

**Comment by WarenGonzaga** [comment]
I work as an HTML5 banner ad developer before and if you want to convert an animation from the web to mp4 (video/gif) I would suggest using this tool https://www.screentogif.com/ I've been using this to convert web animation into video or gif... and it is easy to use you just capture your screen and record it then edit and if you satisfy enough you can convert it to GIF or Video of your choice. ;)

If this helps, please close the issue thanks!

**Comment by matteoraggi** [comment]
I am supposing to use ccapture.js , it works only with canvas html, btu it it a limit large emough for me.

**Comment by matteoraggi** [comment]
Thanks! But I don't feel so sure that it will be able to keep a costant framerat, instead this other tool looks to have a perfect framerate if working with html canvas: https://github.com/spite/ccapture.js/

**Comment by WarenGonzaga** [comment]
> Thanks! But I don't feel so sure that it will be able to keep a costant framerat, instead this other tool looks to have a perfect framerate if working with html canvas: https://github.com/spite/ccapture.js/

Are you going to create a web animation based editor/ and they are going to export it into mp4 format? Is that right?

**Comment by WarenGonzaga** [comment]
I think this one will help you... http://www.tysoncadenhead.com/blog/exporting-canvas-animation-to-mov/

**Comment by matteoraggi** [comment]
yes, I would create a svery simple html editor to customize mp4 videos starting from html.
Actually adobe after effects and adobe animate cc can export in canvas html but is hard to find online commercial demos usin html canvas I see..

**Comment by eltonmesquita** [comment]
Mind if I close this @matteoraggi ? It's way off topic and you've got your answers, I think.

**Comment by matteoraggi** [comment]
yes, thanks a lot :-)
