### ISSUE TITLE
[Chrome 74] @media(prefers-reduced-motion) rule

### ISSUE THREAD

**Issue by sivot** [daneden/animate.css#932]
`@media(prefers-reduced-motion)` rule updated, please check:
https://developers.google.com/web/updates/2019/03/prefers-reduced-motion

Please extend the rule:
`@media (prefers-reduced-motion) ` -> `@media (prefers-reduced-motion: reduce)`

**Comment by WarenGonzaga** [comment]
Hello @sivot  thank you for the update!
@eltonmesquita can you please check this one and add a proper label for this. Thank you!

**Comment by yellow1912** [comment]
I can confirm this. With the release of the new Chrome, this rule causes all my elements to stop being animated even when the users do not set the mode to reduce. This issue is critical and should be fixed asap.

**Comment by jomho** [comment]
I have added 
```
@media (prefers-reduced-motion: reduce) {
  .animated {
    animation: unset !important;
    transition: none !important;
  }
}
```
to styles.css in my angular app. Also, I have attempted to update the library to include `@media (prefers-reduced-motion: reduce)` instead of `@media (prefers-reduced-motion)`. Neither has worked in Chrome for iOS V74.0.3729.121. What should I do?

**Comment by sivot** [comment]
@jomho that block inlcuded to `animate.css` library, so if you include that block to your style it doesn't matter. :) Need to fix that block in `animate.css` library.

**Comment by eltonmesquita** [comment]
I'll close this as it's a duplication of #928 .
