### ISSUE TITLE
Issue installing with Node v12 (fsevents)

### ISSUE THREAD

**Issue by fitztrev** [daneden/animate.css#938]
I believe that `fsevents` is only used for MacOS so this issue may only be on that OS.

```bash
# on latest version of Node.js
$ node -v
> v12.3.1
$ npm -v
> 6.9.0
```

## Steps to Reproduce

`package.json` contents:
```json
{
  "private": true,
  "dependencies": {
    "animate.css": "^3.7.1"
  }
}
```

Then, using latest Node 12.3.1 on MacOS, run `npm install`.

## Output

```bash
$ npm install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)

[... continues with a long log of syntax errors and deprecation notices ...]
```

The issue may lie with a dependency and not this project. If that's the case, I apologize for opening an issue here. I wasn't able to track down what the fix is. I do see `fsevents@1.2.4` in the shrinkwrap for this package, though.

**Comment by eltonmesquita** [comment]
The current building system/dependencies is being totally rewritten, as you can see in [this branch](https://github.com/daneden/animate.css/tree/new-build). So we probably won't give much attention to the current one.

But if it's currently working but throwing some warning in the console, there should be no problem in just ignoring it.

Thanks for reporting!

**Comment by fitztrev** [comment]
@eltonmesquita Ok, thanks for the reply. I did manage to get rid of the error by rebuilding the shrinkwrap. I believe the issue was fixed in `fsevents@1.2.4` so if it is changed to pull that in, it works.

### With Error
```bash
git clone https://github.com/daneden/animate.css.git with-error
cd with-error
npm install
# > error occurs here
```

### No Error
```bash
git clone https://github.com/daneden/animate.css.git no-error
cd no-error
rm npm-shrinkwrap.json
npm install
npm shrinkwrap # rebuild the npm-shrinkwrap.json
```

Would updating the `npm-shrinkwrap.json` be the correct fix?

**Comment by eltonmesquita** [comment]
I honestly don't know what's the best fix. But I'll try to get to it and update the dependencies if it's causing trouble for people.

**Comment by Mackignacio** [comment]
@fitztrev  try this

1. Run `npm audit` .
2. You will see a list of vulnerabilities and suggestions on how to fix them. At the very end you will see a command like this `npm update fsevents --depth 4`. Run the command and it will update `npm-shrinkwrap.json` .

This works for me.

**Comment by fitztrev** [comment]
@Mackignacio Yes, but this is a library that I'm including via my main project's `package.json`. I can't rebuild a package's shrinkwrap.

**Comment by Mackignacio** [comment]
@fitztrev  You are adding animate.css on your `package.json`? You can add it by simply `npm install animate.css --save`. I think you don't need shrinkwrap to add animate.css on your project.

**Comment by fitztrev** [comment]
@Mackignacio yes, I'm aware. See my original post above with steps to reproduce.

**Comment by Mackignacio** [comment]
@fitztrev I think we might want to wait for version 4.0 because it will not use gulp as a dependency.

**Comment by fitztrev** [comment]
@Mackignacio It doesn't need to wait. At the very least all that has to happen is the npm-shrinkwrap needs to be rebuilt. I've explained a little more [in the comment on my PR](https://github.com/daneden/animate.css/pull/939#issuecomment-498276447).

Here are some other projects that have had to upgrade their `fsevents` dependency in order to work with Node 12:

https://github.com/nervosnetwork/neuron/pull/397
https://github.com/daief/jugg/commit/b9550f790e6235f83753ccab63bce903a321d64a
https://github.com/rentpath/react-ui/pull/462
https://github.com/hypothesis/lms/commit/bad0be41e53e37f5b2a61b63f636fe7d66879024

Before I continue with any more discussion, I'll wait to hear what a maintainer says.
