### ISSUE TITLE
Items visible before the animation

### ISSUE THREAD

**Issue by massimilianocom** [daneden/animate.css#944]
Hi everyone.
I am using the animate.css plugin in my project, except that something strange is going on before the animation starts when I go to the animated section, before the animation starts, you can see the visible element and then disappear and perform the animation. 'animation.
How can I make the element not visible before the animation?
Reading the animate.css file I see that the animated class always has opacity in 1 so I guess the problem is this and so it's a bug?
Then again if I try to put an initial class with "opacity: 0" to keep it hidden initially, after the animation ends the element disappears even if animated is in 1, another bug?

**Comment by Taytay884** [comment]
Please let me see an example of a code that showing it. Then I could try to help and maybe we will create a bugfix.

**Comment by sivot** [comment]
Suggestions for your problem:
- JS `animationstart` and `animationend` Events
- JS CSS and DOM manipulating like `display: none`, `display: block`

**Comment by eltonmesquita** [comment]
Closing this as it's unrelated and got no feedback from @massimilianocom .
