### ISSUE TITLE
Animate.css Conflict With Perspective & Preserve-3D properties

### ISSUE THREAD

**Issue by AdventurouslySocial** [daneden/animate.css#945]
Environment Details:
1-WordPress install
2-Elementor Page Builder (Includes Animate.css)
(Have also tried dequeuing Elementor's animate.css and enqueuing it separately, no joy, same following result)
3-Specific animations tested don't use 3d space themselves, they are fadeIn and fadeInUp

Successful Scenario 1:
When using animate.css to animate an element within an Elementor built page - the element successfully animates.

Failed Scenario 2:
When attempting to achieve the same results as from Scenario 1 within a page that employs the following page structure and CSS, animate.css never animates. Animated Element exists within the . ContentContainer class.  It also keeps the element 'hidden' in a pre-animated state. (The same happens with AOS.js/css and while that is a different library, I feel the issue is shared between animate and AOS).

    <div class="MainContainer">
       <div class="ParallaxContainer">
             // Headlines for the page
       </div>

       <div class="ContentContainer">
           <div class="Content">
           // Put the rest of my page content here
          </div>
       </div>
    </div>

CSS:
    .MainContainer {
      perspective: 1px;
      transform-style: preserve-3d;
      height: 100vh;
      overflow-x: hidden;
      overflow-y: scroll;
      }

    .ParallaxContainer {
    display: flex;
    flex: 1 0 auto;
    position: relative;
    height: 100vh;
    transform: translateZ(-1px) scale(2);
    z-index: -1;
    }

    .ContentContainer {
    display: block;
    position: relative;
    background-color: white;
    z-index: 1;
    }

Is animate.css capable of operating within the above page structure? Is the failure due to operator error or is there an actual problem?

Any and all information, insight, and help is much appreciated.

**Comment by sivot** [comment]
**I think this is not the right place for this problem.**
Try it Community or Support of Wordpress / Elementor Page Builder.
Otherwise I suggest you the [CodePen](https://codepen.io/) in order to test your problem.

**Comment by eltonmesquita** [comment]
Closing as it's unrelated to the library.
