### ISSUE TITLE
Demo website not working

### ISSUE THREAD

**Issue by kosvrouvas** [daneden/animate.css#948]
Or is it just me?

When I select an animation from the dropdown and click animate nothing happens.

Chrome and Firefox, MacOS

**Comment by Tokenyet** [comment]
It's also not working for me recently, but working in Edge.

Specs:
System: Win10
Chrome: 75.0.3770.100

**Comment by chetanmadaan** [comment]
Tested on Chrome & Firefox. not working.

**Comment by chetanmadaan** [comment]
Working fine on Chrome version 74.0 but not on (75.0.3770.100).

**Comment by chetanmadaan** [comment]
It looks like this is the fix.
https://github.com/daneden/animate.css/pull/931

**Comment by eltonmesquita** [comment]
See this:
https://github.com/daneden/animate.css#accessibility

Animations are disabled on your OS and will make animate get disabled on its new versions.
