### ISSUE TITLE
Support for repeating animation ever x seconds

### ISSUE THREAD

**Issue by 1000martians** [daneden/animate.css#949]
I know there is an 'infinite' class but that just keeps the animation going on for forever without any delay. I'd like, let's say, a button to shake every 3 seconds.

**Comment by eltonmesquita** [comment]
Javascript is the only option in this case as there no CSS support for delays between a animation's iterations. If you need help, stackoverflow is the best place for this, as this is a issue tracker focused on the library's issues.

Closing this as unrelated.
