### ISSUE TITLE
Provide a compatibility version with v4

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#950]
[animate's next version](https://github.com/daneden/animate.css/tree/dev) will include a major breaking change, class prefix (aka namespace), and this will make a direct update from previous versions harder and I see a lot of issues popping on this issue tracker related to this feature in the future.

It would be easy to provide a file for compatibility with previous versions (like animate.compat.css). The question is, **should we provide this file out of the box in the new release**?

We need as much feedback as we can get relating to this as it will be one of the biggest change in the whole library's story.

**Comment by eltonmesquita** [comment]
@WarenGonzaga, what do you think about this?

**Comment by WarenGonzaga** [comment]
@eltonmesquita it would be nice to add that one since as you said it is a breaking changes for the entire library I saw some website is highly dependent on animate.css as their animation library. For that's okay.

**Comment by WarenGonzaga** [comment]
@eltonmesquita I don't see this update in the current build...

**Comment by eltonmesquita** [comment]
It's now available on the dev branch.
