### ISSUE TITLE
我用zoomIn和zoomOut他的缩放中心怎么不在中间呢？怎么控制？

### ISSUE THREAD

**Issue by Guidozijef** [daneden/animate.css#953]

**Comment by eltonmesquita** [comment]
Hi. If you don't write in English, it'll be really hard to help...

**Comment by xiongyubin** [comment]
> Hi. If you don't write in English, it'll be really hard to help...

It doesn't make any difference. Sometimes I have to translate English.

**Comment by eltonmesquita** [comment]
Sorry but Google translator didn't help me much with a translation to your question. I'd love help but first I've got to understand the question...

**Comment by Guidozijef** [comment]
> Hi. If you don't write in English, it'll be really hard to help...

I use zoomIn and zoomOut. Why isn't his zoom center in the middle? How?

**Comment by Guidozijef** [comment]
> Sorry but Google translator didn't help me much with a translation to your question. I'd love help but first I've got to understand the question...

I use zoomIn and zoomOut. Why isn't his zoom center in the middle? How?

**Comment by Guidozijef** [comment]
I use zoomIn and zoomOut. Why isn't his zoom center in the middle? How?

**Comment by eltonmesquita** [comment]
Sorry but we'd need more details to try to help here. Anyway, this is an issue tracker dedicated to problems and improvements in the library itself, it's a place to get help about usage and CSS problems (which the question seems to be related).
Please use Stackoverflow to this kind of help.

**Comment by Guidozijef** [comment]
> Sorry but we'd need more details to try to help here. Anyway, this is an issue tracker dedicated to problems and improvements in the library itself, it's a place to get help about usage and CSS problems (which the question seems to be related).
> Please use Stackoverflow to this kind of help.

When I use zoomIn and zoomOut animations, what if I want to control where they pop up?

**Comment by Guidozijef** [comment]
> > Hi. If you don't write in English, it'll be really hard to help...
> 
> It doesn't make any difference. Sometimes I have to translate English.

When I use zoomIn and zoomOut animations, what if I want to control where they pop up?

**Comment by Guidozijef** [comment]
When I use zoomIn and zoomOut animations, what if I want to control where they pop up?

**Comment by eltonmesquita** [comment]
Positioning an element is a developer's reasonability, not a library's. The library will animate the element where it is.

There are many techniques to achieve positioning in CSS and each one will be better for each situation depending on your layout and how the page is built. There's no way to help you around here in this situation.

My advice is to elaborate a little more on your problem, create a demo somewhere (codepen, Kevin, etc) and seek for help on stackoverflow or any other developer focused website. You'll probably get help from there.
