### ISSUE TITLE
Move animate's Github page  to master

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#955]
If we move gh-pages to the master branch we can do some automated things we can't do now, like building the animation list automatically into the website and keeping the versions in sync.

Today everything's done manually and is prone to errors.

**Comment by WarenGonzaga** [comment]
@eltonmesquita any references on how to do it?

**Comment by eltonmesquita** [comment]
Don't worry @WarenGonzaga, I've already got a working branch on this. I'll update the `dev` branch with it as soon as I finish working on it. I'll also need @daneden help as he's the only person with permission to configure this setting on Github.

**Comment by WarenGonzaga** [comment]
Alright! Thanks @eltonmesquita just mention me if you need extra hand...

**Comment by eltonmesquita** [comment]
Closing this as by now as it'll be easier to just maintain the same structure.
