### ISSUE TITLE
Add compile step to commit hooks

### ISSUE THREAD

**Issue by eltonmesquita** [daneden/animate.css#956]
Today the compiling step must be run manually and most of the time people just forget it. Let's add a commit hook to compile it automagically!

**Comment by eltonmesquita** [comment]
@WarenGonzaga , do you think you can do this on the `dev` branch?

**Comment by WarenGonzaga** [comment]
@eltonmesquita I think I can if I understand how the process works... possible I can make it automagically.

**Comment by eltonmesquita** [comment]
Well, we've already got a hook for Prettier set up, so I think that should be pretty straight forward.

**Comment by WarenGonzaga** [comment]
@eltonmesquita is this done? is it late for me to do this?

**Comment by eltonmesquita** [comment]
Hi @WarenGonzaga . Nope, not done yet. Too many things happening in personal life right now so I had to pause a bit on working on the new version.

**Comment by WarenGonzaga** [comment]
Hi @eltonmesquita do you have the backlogs? any task list for this? So that I can take a look on it?

**Comment by eltonmesquita** [comment]
Sorry, no backlogs :|
But I'll take the job, don't worry about this!

**Comment by eltonmesquita** [comment]
That's done in some lost commit. Closing!
