### ISSUE TITLE
animation-fill-mode breaks width on ul>li ltems

### ISSUE THREAD

**Issue by terryupton** [daneden/animate.css#958]
So I have an animated list item (li) that then has a sub menu (div) that will display a full width flex megamenu. However, if I apply the class of .animated to the parent (li) it breaks the child div width. 
Here is a much simplified codepen to illustrate:
https://codepen.io/amasci/pen/NZZzYQ

Here it is with the animated class removed:
https://codepen.io/amasci/pen/dBBKBq

How can I stop this from occurring?

**Comment by off-uk** [comment]
I think, you can apply the class .w-full to the li element

**Comment by terryupton** [comment]
Thanks @off-uk - that seems to work.
