### ISSUE TITLE
Animate.css doesn't work on its demo page.

### ISSUE THREAD

**Issue by timur-svoboda** [daneden/animate.css#959]
Animate.css doesn't work on its demo page https://daneden.github.io/animate.css/

No animation works. I thought it might work in another browser, but Animate.css doesn't work either in Chrome or Firefox. 

If you need more details, I will gladly answer.

**Comment by eltonmesquita** [comment]
Hi @timur-svoboda!
Please visit the website again, I've added a warn about this.
