### ISSUE TITLE
FlipInX Effect and horizontal scroll bar

### ISSUE THREAD

**Issue by buttflattery** [daneden/animate.css#962]
when using the `flipInX` effect it adds a horizontal scrollbar on the bottom while it is flipping, if the element i am trying to flip has width equal to half of the screen, and disappears as soon the animation stops which makes the page wobble and isnt nice. 

I am creating a menu widget with a bigdrop effect for the menu where i am using it 

![image](https://user-images.githubusercontent.com/1536454/62574081-07238000-b8b1-11e9-850b-a390affbb889.png)

Is there anyway to avoid the scroll bar when using the effect on relatively large elements.

**Comment by eltonmesquita** [comment]
This is a simple overflow problem. Just set `overflow: hidden` on the container or any parent element to avoid scroll bars.

If you need more help, stackoverflow is the place to ask for help as this is an issue tracker and is dedicated to issues related to the library itself and not about CSS usage.

Closing this as it's unrelated.
