### ISSUE TITLE
bouncein effects not working

### ISSUE THREAD

**Issue by paterik4** [daneden/animate.css#965]
```
<div style="font-family: 'Roboto'; font-weight: 400; font-size: 23px;" class=" wow bounceInRight w3-col m6 w3-padding-large">
        <p>Hello! Engedd meg hogy bemutatkozzak, Keszei Patriknak hívnak, 21 éves vagyok és Veszprémben élek.</p>
        <p>Programtervező Informatikusnak tanulok épp a Pannon Egyetemen, és jelenleg a Promera Menedzsment kft.-nél vagyok fejlesztő/tesztelő.</p>
        <p>Ha éppen nincs feladatom, a saját weboldalamat szoktam csinosítgatni, valamint ha van megrendelésem azzal törődöm.</p>
        <p>Ezen kivül még játékfejlesztéssel foglalkoztam 2017-2018-ig.</p>
     </div>
```

The bordered div and the picture with the paragraphs should bounce in, but it don't do it.

Any css overwrites that can affect that? or any js overwrites that can cause it? 

Help wanted!

**Comment by eltonmesquita** [comment]
Yeah, it certainly has a conflicting declaration overwriting animate's transforms. Unfortunately we can't help here as this issue tracker is dedicated to the library's issue, there's no way we can provide support for usage besides the docs.

Stackoverflow is the best place for this type of question. Try to detail more the issue including a live example and post it on stackoverflow, you should get some help there.
