### ISSUE TITLE
Ui event expired

### ISSUE THREAD

**Issue by HelenTim** [daneden/animate.css#968]
The element is fixedly positioned, using the bounceInRight animation, scrolling the mouse wheel, the content inside this element is not scrolling

**Comment by eltonmesquita** [comment]
Sorry but can you elaborate more on the question? I couldn't understand what's the actual issue.

**Comment by WarenGonzaga** [comment]
It is good to add a sample link on codepen so that we can fix it... ;) hi @eltonmesquita good to see you here... I've been busy the past months.

**Comment by eltonmesquita** [comment]
I think this can be closed as there's no response or clear info about the issue.
Good to see you too @WarenGonzaga and welcome to the Busy Club Inc ;D
