### ISSUE TITLE
animated Class affects overflow-y?

### ISSUE THREAD

**Issue by snakone** [daneden/animate.css#969]
I have a big content on my site, a post. Anyway i had **animated fadeIn** class on the parent element. At some point of the content you see this:

https://media.discordapp.net/attachments/467293737530425346/616734462662934528/Screenshot_20190829-224214.png?width=169&height=301

It cuts the content off. (There should be more content under the highlighted code)

Seems like overflow is affecting the parent div at some **height**, it works well if the class **animated fadeIn** its removed.

Only happens on Chrome and on mobile

**Comment by eltonmesquita** [comment]
Most of the animations can cause elements to overflow as they are literally moved across the screen. How to handle this is up to the developer using the library. This is just how CSS works.

Make sure to use the overflow property when needed to avoid such situation.

Closing this as it's not a issue with the library.
