### ISSUE TITLE
Overflow issue on elements with animated classes

### ISSUE THREAD

**Issue by subotin94** [daneden/animate.css#970]
I have an issue where i have a div which has "animated bounceInDown fast" set of classes and i also have overflow on that div. What happens is the scrollbar is fully visible and its working but only if i drag the scrollbar itself. If i use the mouse wheel i cannot scroll on that speciffic element. Sometimes it even works but in 90% cases it doesnt work. When i click and drag the scrollbar itself it always works normal. And when i took off the animated classes it works just normal.

**Comment by eltonmesquita** [comment]
Most of the animations can cause elements to overflow as they are literally moved across the screen. How to handle this is up to the developer using the library. This is just how CSS works.

Make sure to use the overflow property when needed to avoid such situation.

Closing this as it's not a issue with the library.

**Comment by subotin94** [comment]
It is not an overflow it is transitions and transform. It is the library
issue.

**Comment by eltonmesquita** [comment]
Sorry but any overflow issue is the developer's responsibility as it's impossible for the library to deal with  it and we can not give individual support about CSS usage.
You can get help on Stackoverflow but I'd advice you to prepare a reduced case and post it live on codepen, jsbin or any other place so people can help you.
