### ISSUE TITLE
Chrome on iOS animation problem

### ISSUE THREAD

**Issue by leone510es** [daneden/animate.css#973]
I know that some similar issues have bean posted, but I still don't understand that if there is a solution for this. A video is worth more than a 1000 words, so here it is:
https://drive.google.com/drive/folders/1TKiq6zxBWyFB40awDTLYbLae66JEW0kK

On the left: iPhone 5S - iOS 12.4 - Chrome 76.3809.123
On the right: iPhone 7 - iOS 12.4 - Chrome 76.3809.123

I'm testing a react based web app with animate.css (3.7.2). But as you can see, the iPhone 5S handles animation with ease but the iPhone 7 is very sloppy (like no animations at all). 
Both iPhone has a Reduce motion setting OFF. In Safari, both phones are working great.

Is there anything I can do about it? I saw a @media (print), (prefers-reduced-motion: reduce) css option somewhere in a post, how can I use that? Where should I put it? Will that solve the issue?

Thank you in advance!

**Comment by leone510es** [comment]
Anybody? Am I the only one having these issues?

**Comment by eltonmesquita** [comment]
Please see https://github.com/daneden/animate.css/blob/master/README.md#accessibility
