### ISSUE TITLE
"pulse" property creating recurring overflow on page using Firefox

### ISSUE THREAD

**Issue by Lper258** [daneden/animate.css#976]
Just noticed this. Not sure if that behavior is normal.
The issue does not appear in Chrome or Chromium.

Pure HTML code is:

```
<body>
    <h1 class="animated pulse">Some text!</h1>>
</body>
```

This is the result:

![Peek 2019-09-22 10-49](https://user-images.githubusercontent.com/21357625/65384798-e8752d80-dd26-11e9-8930-9416296978eb.gif)

OS: Debian 10
Browser: Firefox 60.9.0esr
Resolution: 1366*768

Let me know if more info is needed.

Cheers

**Comment by eltonmesquita** [comment]
Most of the animations can cause elements to overflow as they are literally moved across the screen. How to handle this is up to the developer using the library. This is just how CSS works.

Make sure to use the overflow property when needed to avoid such situation.

Closing this as it's not a issue with the library.
