### ISSUE TITLE
Puff in/out?

### ISSUE THREAD

**Issue by rlaferla** [daneden/animate.css#988]
Looking for the equivalent of Magic's puff in/out in Animate.

https://www.minimamente.com/project/magic/

**Comment by WarenGonzaga** [comment]
Hi there! That's awesome! We will create one for this... thanks for your suggestion.

**Comment by WarenGonzaga** [comment]
@eltonmesquita assign this to me... I can work on it...

**Comment by eltonmesquita** [comment]
Sorry, but I don't think this is a good idea as animating blur is still too laggy and there is a library that provides this yet. So, I'm closing this.
