### ISSUE TITLE
 I want to use aniamtion.css but I don't understand the licence

### ISSUE THREAD

**Issue by signgitgit** [daneden/animate.css#991]
Hello,

Please I want to use some animations in my web application using aniamtion.css but I don't understand the licence of the library  exactly this point:

**"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, .........     "**

Must I include this copyright notice and the permission notice in my web application?

Thanks in advance.

**Comment by motifiy** [comment]
I have the same problem

**Comment by mrvnmchm** [comment]
Hi, not sure if I understand the context but, just include the license and copyright within the codebase.

**Comment by eltonmesquita** [comment]
You don't even need the license within your project, just make sure you don't strip out the header with the copyright notice on the CSS file and you're good to go.

**Comment by motifiy** [comment]
I think  I know how to use it,it can be used by link or download
package(ps:you can't only copy this css file)

Elton Mesquita <notifications@github.com> 于2019年11月15日周五 上午2:18写道：

**Comment by motifiy** [comment]
thank you for your help

xiangyong wang <wangxiangyong1996@gmail.com> 于2019年11月15日周五 下午4:16写道：
