### ISSUE TITLE
Animation not working on safari

### ISSUE THREAD

**Issue by d3v4s** [daneden/animate.css#997]
I test on iOS Safari 13.0.3 version, and the animation not working.  
I resolve it using the whole percentage.
Example with `flipOutY`:
> This not working:
> ```
> @-webkit-keyframes flipOutY {
>  from {
>    -webkit-transform: perspective(400px);
>    transform: perspective(400px);
>  }
>  30% {
>    -webkit-transform: perspective(400px) rotate3d(0, 1, 0, -15deg);
>    transform: perspective(400px) rotate3d(0, 1, 0, -15deg);
>    opacity: 1;
>  }
>  to {
>    -webkit-transform: perspective(400px) rotate3d(0, 1, 0, 90deg);
>    transform: perspective(400px) rotate3d(0, 1, 0, 90deg);
>    opacity: 0;
>  }
> }
> ```
> This work on safari and other browser:
> ```
> @-webkit-keyframes flipOutY {
>    0% {
>        -webkit-transform: perspective(400px);
>        transform: perspective(400px);
>    }
>    30% {
>        -webkit-transform: perspective(400px) rotate3d(0, 1, 0, -15deg);
>        transform: perspective(400px) rotate3d(0, 1, 0, -15deg);
>        opacity: 1;
>    }
>    100% {
>        -webkit-transform: perspective(400px) rotate3d(0, 1, 0, 90deg);
>        transform: perspective(400px) rotate3d(0, 1, 0, 90deg);
>        opacity: 0;
>    }
> }
> ```

**Comment by andrewbarnesweb** [comment]
I'm experiencing this too. I'll try the workaround mentioned above and confirm if that resolves it :-)

**Comment by d3v4s** [comment]
I've created a [fork](https://github.com/d3v4s/animate.css) of this repo , where I'm trying to fix the animations

**Comment by WarenGonzaga** [comment]
hello guys! still persist the issue? @d3v4s

**Comment by d3v4s** [comment]
Hy, I've tested the css on epiphany (it's a web-kit based browser), and the animations work.  
I'm waiting for confirmation from others.

**Comment by andrewbarnesweb** [comment]
In iOS this seems to be related to having reduced motion turned off in the accessibility settings. ![image](https://user-images.githubusercontent.com/20924669/71769127-e1a8aa00-2f14-11ea-9ec4-71d22244b248.jpg)

When it’s not ticked, the animations work fine :-)

**Comment by WarenGonzaga** [comment]
@andrewbarnesweb based on what I know about animate.css the reduce motion has been set to as optional when you customizing the stylesheet. This is available in dev version of animate.css...

**Comment by WarenGonzaga** [comment]
@eltonmesquita kindly review and close if necessary thanks!
