### ISSUE TITLE
Add Iteration-Count CSS utility classes

### ISSUE THREAD

**Issue by mathisjay** [daneden/animate.css#998]
Similar to the 'infinite' utility class:
```
animated.infinite {
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
}
```
or the 'delay' utilities:
```
.animated.delay-1s {
  -webkit-animation-delay: 1s;
  animation-delay: 1s;
}

.animated.delay-2s {
  -webkit-animation-delay: 2s;
  animation-delay: 2s;
}
```

It would be great if there were some iteration utilities. Something like:

```
.animated.iterations-1 {
  -webkit-animation-iteration-count: 1;
  animation-iteration-count: 1;
}

.animated.iterations-2 {
  -webkit-animation-iteration-count: 2;
  animation-iteration-count: 2;
}
```

**Comment by WarenGonzaga** [comment]
hmm awesome suggestion ;) I like it let me handle this one...

**Comment by eltonmesquita** [comment]
Hi @WarenGonzaga , maybe we could do this with css custom properties instead?

**Comment by WarenGonzaga** [comment]
@eltonmesquita maybe we can use a predefined CSS class for this...

**Comment by WarenGonzaga** [comment]
@mathisjay done! @eltonmesquita kindly review my pull request to dev...

Introducing... loop utility class ... commit #1029
