### ISSUE TITLE
Add FadeInSmall classes

### ISSUE THREAD

**Issue by mathisjay** [daneden/animate.css#999]
We already have classes like FadeInLeft and FadeInLeftBig but the shift is often too big.

Consider add some "Small" classes to just move the shift the item like 50px for a more subtle feel.

**Comment by WarenGonzaga** [comment]
hmmm good idea... let me work on that ;) @mathisjay

**Comment by eltonmesquita** [comment]
#1009 could fix this too.

**Comment by eltonmesquita** [comment]
Let's keep the discussion on #1009 .
